### ISSUE TITLE
the problem I met when I used the command of yarn init.

### ISSUE THREAD

**Issue by QuoniamYIF** [yarnpkg/yarn#1036]
the system I use: win7 64bit

when I type in `yarn init`,the problem occurred:
```
$ yarn init
yarn init v0.15.1
error Can't answer a question unless a user TTY
    at ConsoleReporter.question (C:\Program Files (x86)\Yarn\lib-legacy\reporters\console\console-reporter.js:201:59)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\lib-legacy\cli\commands\init.js:97:38)
    at next (native)
    at step (C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at run (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```
what's the reason of it?

**Comment by FLGMwt** [comment]
Try using PowerShell or cmd.exe.

**Comment by QuoniamYIF** [comment]
@FLGMwt thank you,the problem is solved.

**Comment by pedzed** [comment]
Using an alternative does not fix the initial problem. I am using MINGW64 (Git Bash) and do not want to use PowerShell/CMD...

**Comment by shadow512122313** [comment]
I encounted the same problem with git bash. (yarn version 0.20.3)

**Comment by pedzed** [comment]
@shadow512122313 That's what I said ;)

The most annoying thing is that `npm init` _does_ work, so I tend to use that and then continue with Yarn.

**Comment by ScottyFillups** [comment]
Try adding the following to your .bashrc file:

`alias yarn='node "C:\Program Files (x86)\Yarn\bin\yarn.js"'`

Running `yarn init` should work now.

**Comment by ROCKBOOM** [comment]
when i used Git bash here, I met the same question, you can use CMD to solve this problem

**Comment by pedzed** [comment]
@ROCKBOOM You ain't solving any problem. You are just using a workaround.

When your teeth hurt, you can use paracetamol to lessen the pain. But you are not fixing the issue. The disease is still there, you are just ignoring it.

This issue is a bug that needs to be fixed.

**Comment by BriFuture** [comment]
@ScottyFillups  Thank You;
But I think if you use `npm install -g yarn` to get  yarn, it's better to alias yarn like this:
```bash
alias yarn='node C:\\Users\\UserName\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\yarn.js'
```

**Comment by ScottyFillups** [comment]
@BriFuture You're welcome :smile: 

You're probably right about the alias; I'm not a Windows expert, and at the time I was just scrambling to find a hotfix. These days I use Arch Linux instead.

I'll keep your comment in mind though if I need to help some friends install yarn on their PCs; thanks :wink:

**Comment by RAJUKESAVAN** [comment]
i am facing error when i init yarn in my project       {   
{
  name: 'Backend',
  packageManager: 'yarn@3.2.2'
}
Internal Error: Process git failed to spawn
    at ChildProcess.<anonymous> (C:\Users\SAM\.yarn\releases\yarn-3.2.2.cjs:392:5693)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.Xge.r.emit (C:\Users\SAM\.yarn\releases\yarn-3.2.2.cjs:4:7024)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) }
