### ISSUE TITLE
Doesn't refresh git repo

### ISSUE THREAD

**Issue by ronag** [yarnpkg/yarn#1171]
**Do you want to request a _feature_ or report a _bug_?**

_bug_

**What is the current behavior?**

Doesn't re-fetch git repo if branch revision has changed.

**If the current behavior is a bug, please provide the steps to reproduce.**

`"mydep": "github:myrepo/mydep#mybranch"`
`"mydep2": "github:myrepo/mydep2"`

`yarn upgrade`
`yarn`

**What is the expected behavior?**

Check if the correct revision is local and otherwise fetch the latest

**Please mention your node.js, yarn and operating system version.**

OSX Sierra
yarn 15.1

**Comment by markstos** [comment]
Possibly related to #1017.

**Comment by jfirebaugh** [comment]
I'm seeing this even when using hashes of commits, and explicitly updating `package.json` to a newer hash.

E.g., first `yarn install` with:

```
"dependencies": {
  "module": "user/module#deadbeef"
}
```

Then update to:

```
"dependencies": {
  "module": "user/module#badf00d"
}
```

`yarn install` again. `yarn.lock` will say that it's now at `badf00d`, but the installed version will still be `deadbeef`.

**Comment by jfirebaugh** [comment]
I was hoping that this might have been fixed by #1641, but I tested yarn 0.17.3 and the bug still occurs.

**Comment by bestander** [comment]
Should be fixed now #2074

**Comment by liywjl** [comment]
I get the same issue on OSX High Sierra v10.13.4, yarn 1.6.0

**Comment by shorif2000** [comment]
i am still getting this issue on v1.17.3. `yarn cache clean && rm -rf node_modules && yarn install` did not work

**Comment by faxioman** [comment]
same issue on v1.22.4

**Comment by kaligrafy** [comment]
Same issue on v1.22.10

**Comment by markstos** [comment]
@faxioman @kaligrafy There are two versions of the issue described here whic are different:

  1. Failure to update with a Git branch when the content of the branch changes but the URL in package.json / yarn.lock does not.  
  2. Failure to update when an explicit Git SHA changes in package.json/yarn.lock

Please clarify which case you are still reproducing. I think these two cases should be split into separate issues, each with a clear title. Case 2 described by @jfirebaugh feels like an clear bug that seems easier to fix.

**Comment by kaligrafy** [comment]
1. Failure to update with a git hash in a fork. It just fetches the original repo and not the fork with a specific hash.

**Comment by faxioman** [comment]
Sorry @markstos but I can’t remember the problem I was facing🤷‍♂️

**Comment by shawnwang-avl** [comment]
facing 1. on yarn 1.22.19

Git private repo branch dependency not refreshed to branch HEAD

**Comment by shawnwang-avl** [comment]
Following this worked https://github.com/yarnpkg/yarn/issues/1573#issuecomment-369557725
