### ISSUE TITLE
Reversion bug: yarn 0.16 no longer able to install scoped packages from private registry

### ISSUE THREAD

**Issue by tyrsius** [yarnpkg/yarn#1274]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn` fails with

```
Trace: 
  TypeError: Cannot use 'in' operator to search for 'latest' in undefined
      at /usr/local/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:62:24
      at next (native)
      at step (/usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/usr/local/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:191:7)
      at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at Function.findVersionInRegistryResponse (/usr/local/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:72:7)
      at /usr/local/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:89:34
      at next (native)
      at step (/usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a private registry, which also has a scope. 

```
$ yarn config get registry
http://artifactory.nike.com/artifactory/api/npm/npm-nike//
```

```
"dependencies": {
    "@nike/lambda-node-logger": "^0.2.0"
  }
```

Yarn `0.15.1` can handle this, but yarn `0.16.(0|1)` fails. 

**What is the expected behavior?**
Installation should succeed

**Please mention your node.js, yarn and operating system version.**
```
Node: 5.7.1
yarn: 15 and 16
OS: Mac Sierra
```

**Comment by jcmorrow** [comment]
I'm experiencing this as well. If I debug the `body` received on line 60 of `npm-resolver.js` it looks like the response is: 

```
package-name@1.0.0{ errors: [ { status: 401, message: 'Invalid basic authentication token' } ] }
```

**Comment by wyze** [comment]
Solved by #1356.

**Comment by jcmorrow** [comment]
@wyze #1356 does provide a cleaner error message, but it doesn't solve the problem causing the error.

**Comment by wyze** [comment]
I guess solved wasn't the correct word to use there. But it does touch on the error reported in this issue.

In regards to your specific error you mention above, might want to follow the discussion in #521 in regards to the authentication token.

**Comment by jcmorrow** [comment]
It does look like that's a better place to track this issue! Thanks @wyze!
