### ISSUE TITLE
Install with 'latest' tag, installs as version string 'latest'

### ISSUE THREAD

**Issue by kwelch** [yarnpkg/yarn#1306]
Yarn: v0.16.1
Node: v6.2.0

Command ran: 
`yarn add <package>@latest`
Actual result (in `package.json`)
`"<package>": "latest"`
Expected Result
`"<package>": "^7.0.0"`

I would lean on the side of this is a feature request to gain parity with this command: `npm install --save <package>@latest`

**Comment by aethant** [comment]
Ill see if I can take a look.

**Comment by aethant** [comment]
@samccone I'm working on implementing this, however, I'm wondering where (if anywhere) I might be able to access the requested repo's dist tags, i.e. - `npm info <package> dist-tags`.

**Comment by akshbn** [comment]
Hi! i have fixed this issue. @aethant Is it ok if i send a PR for this? or do you want to do this on your own? 
I am fine with both. 

Apologies for going ahead with the fix even though you had taken it. I was very excited to contribute to this project and this seemed like a low hanging fruit.

**Comment by aethant** [comment]
Just submit your PR.

**Comment by DenisGorbachev** [comment]
@akshbn this bug is still unfixed - could you please submit your PR?

**Comment by FredyC** [comment]
Yarn version 0.18.0 and bug is still present.
