### ISSUE TITLE
Yarn resolves ^dependency to a version that's too high.

### ISSUE THREAD

**Issue by sephie** [yarnpkg/yarn#1404]
Hi all,

I'm a bit apprehensive, because this issue appears to be caused in principle by having the latest version of Browserify, which seems a very common thing to have, but here goes:

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Fails to install an existing package.json that works fine with NPM install.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ npm ls punycode
`-- browserify@13.1.0 // requests punycode@^1.3.2
  +-- punycode@1.4.1 
  `-- url@0.11.0     // requests punycode@1.3.2
    `-- punycode@1.3.2 
```
```
$ yarn
...
[2/4] 🚚  Fetching packages...
error punycode@2.0.1: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
```
Yarn should not resolve any Punycode dependency to 2.x.x, yet it does, to 2.0.1, which causes the engines error.

**What is the expected behavior?**
Punycode should install 1.4.1, the last before bump to 2.x.x, and not give an error.

**Please mention your node.js, yarn and operating system version.**
OS X 10.11.6
Node 5.12.0
Yarn 0.16.1

*the amount of version is too damn high meme*
Tom

**Comment by davidmerrique** [comment]
Yep! Also has a problem with `>=` #1158

**Comment by mrichards-mdsol** [comment]
This can be a blocker for adoption.

swagger doesn't install with yarn for a similar reason.
Using Node 4.6.1 (latest recommended release) I get the following:
```
error swagger-editor@2.10.4: The engine "node" is incompatible with this module. Expected version ">=5.8.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Swagger has a dependency of ^2.9.2, but swagger-editor has an engine limitation, so yarn should try an older version (eg; 2.9.9) or make it easy to manually provide an alternative preferred version.

**Comment by kittens** [comment]
Fixed via #1477.

**Comment by Foxhoundn** [comment]
Hello @kittens ,

Sorry, but I am still experiencing this with yarn v0.16.0:

```
npm ls punycode
qorus-web-app@0.9.2 /Users/filipwitosz/Code/Projects/qorus
+-- jsdom@9.8.3
| `-- tough-cookie@2.3.2
|   `-- punycode@1.4.1 
`-- webpack@1.13.0
  `-- node-libs-browser@0.5.3
    `-- url@0.10.3
      `-- punycode@1.3.2 
```

When I try ```yarn install``` it dies on:

```
error punycode@2.0.1: The engine "node" is incompatible with this module. Expected version ">=6".
```

I have also updated to latest version of Node.

Is there anything else I should do?

Thank you.

**Comment by sephie** [comment]
The PR that was referenced should contain the fix, but there has not been a new release yet. I experienced this issue on 0.16.1, so I guess we have to wait for 0.16.2 or 0.17.0.

**Comment by Foxhoundn** [comment]
Okay, thanks. Thought it was fixed in one of the latest builds.

**Comment by jasonk** [comment]
I'm still seeing this bug in the current nightly (yarn install v0.19.0-20170105.1735)

**Comment by bunster** [comment]
I'm seeing this issue as well.
