### ISSUE TITLE
Yarn install fails when scoped packages are required

### ISSUE THREAD

**Issue by ingro** [yarnpkg/yarn#1581]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
When I try to run `yarn install` or `yarn upgrade` commands and my `packages.json` include some scoped packaged I got an error like this:
```
Trace: 
  Error: https://registry.yarnpkg.com/@kadira%2freact-storybook-addon-info: Could not authenticate ingruz
      at Request.params.callback [as _callback] (c:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\lib\util\request-manager.js:294:18)
      at Request.self.callback (c:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\node_modules\request\request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (c:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\node_modules\request\request.js:1060:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (c:\Users\Emanuele\AppData\Roaming\npm\node_modules\yarn\node_modules\request\request.js:980:12)
      at IncomingMessage.g (events.js:291:16)
      at emitNone (events.js:91:20)
```

I'm correctly logged with npm:
```
$ npm whoami
ingruz
```

I also tried to use the `login` command of yarn and tried to clear its cache without success.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add some scoped package like `@kadira/storybook` to package.json and try to install.

**What is the expected behavior?**
Scoped packages should be installed without errors.

**Please mention your node.js, yarn and operating system version.**
```
Yarn version: 
  0.16.1

Node version: 
  6.9.1

Platform: 
  win32 x64
```

**Comment by wyze** [comment]
This is fixed on master and will be available in the next release.

**Comment by timoxley** [comment]
@wyze which version? I can confirm this is still an issue for the latest release candidate `yarn@0.19.0`, released January 7.

**Comment by tjwebb** [comment]
any updates? not supporting scoped packages is a pretty egregious blocker...

**Comment by ingro** [comment]
For me this was fixed in 0.17 if I remember correctly. Make sure you're
logged in npm and it should just work!

On 21 Jan 2017 23:06, "Travis Webb" <notifications@github.com> wrote:

any updates? not supporting scoped packages is a pretty egregious blocker...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/1581#issuecomment-274291311>, or mute
the thread

**Comment by adriancooney** [comment]
Problem still seems to be occurring for me. `npm whoami` succeeds yet I receive `Could not authenticate <username>` when trying to install scoped package with Yarn.

**Comment by chee** [comment]
i am experiencing this on `0.21.3`.

i am authenticated on npm, i have `npm login`'d again just to make sure. 

```sh
error An unexpected error occurred: "https://registry.yarnpkg.com/@glimmer%2fcomponent: Could not authenticate chee".
```

**Comment by ming-codes** [comment]
I'm getting this too on `0.22.0`. But my situation is slightly different.

I have 2 npm accounts. One is an old one that I had and since transferred a lot of modules to new account. `yarn` errors and report that it can't auth from the old account. `npm whoami` reports I'm logged-in in new account.

Now, I'm using `nvm` to manage difference node versions. It could be the old login info is cached somewhere where `nvm` did not clean up correctly when switching between node versions. `yarn` could be reading from this cache.

**Comment by ming-codes** [comment]
I am able to fix my problem. @adriancooney and @chee comment above gave me some hint. It seems like `npm logout` still leaves some things behind. I did a `npm logout`, then deleted the `_auth` line in `.npmrc`. Log in again, and everything is fine now.

**Comment by DevSide** [comment]
@ming-codes Thanks, this fixes my "User not found" problem with @babel scope packages
