### ISSUE TITLE
.roadrunner.json error

### ISSUE THREAD

**Issue by zeke** [yarnpkg/yarn#1724]
:wave:

I just installed a nightly build of yarn to get all the latest goodies. Following the instructions at https://github.com/yarnpkg/yarn/issues/1474 and https://github.com/yarnpkg/website/pull/245:

```sh
wget https://yarnpkg.com/install.sh
chmod +x install.sh
install.sh --nightly
```

The install script told me to remove `~/.yarn` so I did, then re-ran it. Now I get this error when I run `yarn`:

```
❯ yarn -V
0.17.0-20161107.1501
/Users/zeke/.yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/Users/zeke/Library/Caches/Yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /Users/zeke/.yarn/node_modules/roadrunner/index.js:25:6
    at /Users/zeke/.yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/Users/zeke/.yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/Users/zeke/.yarn/node_modules/commander/index.js:825:13)
```

Once I've actually used yarn to `add` a dep somewhere, this error goes away, pesumably because this directory is created as a side-effect of the installation process?

**Comment by Daniel15** [comment]
I suspect this is due to #1638. @kittens

**Comment by develar** [comment]
workaround: `mkdir /Users/develar/Library/Caches/Yarn`

**Comment by Daniel15** [comment]
I just encountered this on Linux too (Windows Subsystem for Linux on Windows 10):
> Error: ENOENT: no such file or directory, open '/home/daniel/.cache/yarn/.roadrunner.json'

**Comment by sapegin** [comment]
I have the same on Travis CI with a stable version (`npm install -g yarn`).

**Comment by jbruni** [comment]
It just happened to me using Ubuntu inside Virtual Box (host is Windows 10). 
As suggested above, I installed any package using `yarn add` and the error goes away.

**Comment by reederz** [comment]
Same here on Archlinux and yarn@v0.17.0

**Comment by shaneog** [comment]
Same here when installed on CI via curl/bash:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

results in:

```bash
 curl -o- -L https://yarnpkg.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    94  100    94    0     0    637      0 --:--:-- --:--:-- --:--:--   639
100  3531  100  3531    0     0  22083      0 --:--:-- --:--:-- --:--:-- 22083
Installing Yarn!
> Downloading tarball...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    92  100    92    0     0    665      0 --:--:-- --:--:-- --:--:--   666
  0     0    0   595    0     0   3105      0 --:--:-- --:--:-- --:--:--  3105
100 3531k  100 3531k    0     0  13.3M      0 --:--:-- --:--:-- --:--:-- 56.5M
> Extracting to ~/.yarn...
> Adding to $PATH...
> We've added the following to your /home/ubuntu/.bashrc
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$PATH"

/home/ubuntu/.yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/.cache/yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /home/ubuntu/.yarn/node_modules/roadrunner/index.js:25:6
    at /home/ubuntu/.yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/home/ubuntu/.yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/home/ubuntu/.yarn/node_modules/commander/index.js:825:13)
> Yarn was installed, but doesn't seem to be working :(.

```

**Comment by amasad** [comment]
Hitting this issue on heroku too. (ref https://github.com/heroku/heroku-buildpack-nodejs/issues/337#issuecomment-255140610)

**Comment by Gpx** [comment]
A temporary solution is to rollback to 0.16.1

**Comment by imontiel** [comment]
Having the same problem on CircleCI.

**Comment by Daniel15** [comment]
If you're on Ubuntu or Debian, you can temporarily roll back by doing:
```
wget https://yarnpkg.com/downloads/0.16.1/yarn_0.16.1_all.deb
sudo dpkg -i yarn_0.16.1_all.deb
```

I'll work on keeping multiple versions of Yarn in the Debian repo to make it easier in the future.

Similarly, if you're using a tarball, you can download the tarball from https://yarnpkg.com/downloads/0.16.1/yarn-v0.16.1.tar.gz to get 0.16.1.

**Comment by MoeSattler** [comment]
is there a way to lock the yarn version, like in a `.yarnrc`? (similar to `.nvmrc`)

**Comment by bbak** [comment]
On Debian, when upgrading a globally installed yarn 0.16.1 through npm, the path is: `'/usr/local/share/.cache/yarn/.roadrunner.json'`. There's no `cache` or `.cache` in `/usr/local/share`; however, the directory `'/usr/local/share/.yarn'` exists and is empty.

**Comment by imontiel** [comment]
Ended up just doing `npm install -g yarn@0.16.1`.

**Comment by Daniel15** [comment]
I'm going to work on adding a --version flag to the installer, and also having multiple versions in the Debian repo. That'll allow you to more easily lock down the version of Yarn.

**Comment by Daniel15** [comment]
I've updated the Debian repo to contain all releases, not just the latest one. I think we'll start suggesting locking the Yarn version for CI environments (such as CircleCI, TravisCI, etc). You can update the `apt-get` line in your build script to something like this:
```
sudo apt-get install -yy yarn=0.16.1-1
```

Which will **always** install 0.16.1, even if a newer version comes out. This should prevent your builds from breaking due to new Yarn releases! 😄

**Comment by Zhomart** [comment]
Yarn creates `MODULE_CACHE_DIRECTORY/. roadrunner .json`, where `MODULE_CACHE_DIRECTORY` can be `~/.cache` or `~/Library/Caches/Yarn` depending on the system. 

- https://github.com/yarnpkg/yarn/blob/92399c4b323ce8033685b170f74a566e7879a266/src/constants.js#L55
- and https://github.com/yarnpkg/yarn/blob/553e55f146a465a4e773b53b0a93752163c4b039/bin/yarn.js#L12

I think either yarn should use temporary directory for roadrunner or read config file to get cache directory.
I'm having the same problem while setting `--cache-folder`, e.g.

`$ yarn install --cache-folder ./tmp/yarn-cache`.

**Comment by msmfsd** [comment]
Mac OSX fix: ```mkdir -p ~/Library/Caches/Yarn```

**Comment by wellyshen** [comment]
Hi @msmfsd How to fix if the yarn was installed through nvm `npm -g -i yarn`?

**Comment by MoeSattler** [comment]
@wellyshen 
Same thing, change to the nvm version that contains yarn globally and `npm -g -i yarn@0.16.1`

**Comment by MoeSattler** [comment]
@wellyshen `nvm clear-cache`

**Comment by wyze** [comment]
Fixed via #1902.

**Comment by wellyshen** [comment]
Hi @wyze The problem still exist, I install the yarn through nvm and I also clear cache as @MoeSattler mentioned before run `yarn --version`, and the error occurs:

<img width="938" alt="2016-11-17 11 09 16" src="https://cloud.githubusercontent.com/assets/21308003/20394607/15861ae4-ad1b-11e6-87eb-adc18f889eb5.png">

**Comment by wyze** [comment]
There hasn't been a release with this fix included yet. See #1859 to follow along our progress 0.17.x.

**Comment by wellyshen** [comment]
@wyze OK, thanks. I will waiting for the new version

**Comment by sejoker** [comment]
@wellyshen 0.17.4 includes exactly the fix for https://github.com/yarnpkg/yarn/issues/1859

**Comment by wellyshen** [comment]
@sejoker COOL I have verified, it fixed, thanks

**Comment by tomitrescak** [comment]
I just installed 0.17.10 and I have the very same error:

```
Error: EACCES: permission denied, open '/Users/tomi/.yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /usr/local/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/usr/local/lib/node_modules/yarn/updates/0.17.10/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/usr/local/lib/node_modules/yarn/updates/0.17.10/node_modules/commander/index.js:825:13)
```
