### ISSUE TITLE
[0.17.0] Issues with node-sass

### ISSUE THREAD

**Issue by hassankhan** [yarnpkg/yarn#1832]
**What is the current behavior?**
```
yarn install v0.17.0
info No lockfile found.
error npm-shrinkwrap.json found. This will not be updated or respected. See https://yarnpkg.com/en/docs/migrating-from-npm for more information.
[1/4] 🔍  Resolving packages...
warning istanbul > istanbul-api > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⡀ fsevents: sh: node-pre-gyp: command not found
[2/2] ⡀ node-sass
[-/2] ⡀ waiting...
[-/2] ⠐ waiting...
[2/2] ⠐ node-sass:     at Timer.unrefdHandle (timers.js:312:14)
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
error /Users/hassankhan/Projects/react-dashboard/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/install.js
Directory: /Users/hassankhan/Projects/react-dashboard/node_modules/node-sass
Output:
http node-sass install Downloading binary from https://github.com/sass/node-sass/releases/download/v3.12.4/darwin-x64-46_binding.node
/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/render-template.js:67
          throw new error.MissingTemplateValue(cloned, values)
          ^

Error: Missing template value "progressbar"
    at cloneAndObjectify (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/render-template.js:67:17)
    at Array.map (native)
    at prepareItems (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/render-template.js:83:25)
    at module.exports (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/render-template.js:16:15)
    at Object.Plumbing.show (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/plumbing.js:45:10)
    at Object.Gauge._doRedraw (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/index.js:219:40)
    at null.<anonymous> (/Users/hassankhan/Projects/react-dashboard/node_modules/gauge/index.js:15:19)
    at wrapper (timers.js:275:11)
    at Timer.unrefdHandle (timers.js:312:14)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Have a package that uses `node-sass` as a dependency, then run `yarn install`. Running it a second time will complete the install, but `node-sass` will not work.

**What is the expected behavior?**

No errors, just fun.

**Please mention your node.js, yarn and operating system version.**
Node v4.6.0
Yarn v0.17.0
macOS 10.11.6

**Comment by bestander** [comment]
Can't reproduce this with latest master:
```
~/work/yarn/artifacts/dist/bin/yarn add node-sass
yarn add v0.18.0-0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 180 new dependencies.
├─ abbrev@1.0.9
...
```

**Comment by bestander** [comment]
@hassankhan, can you checkout master and try on it?

**Comment by asprouse** [comment]
I can confirm this is happening with our CI build with yarn 17. It works when I clear the cache but like @hassankhan mentioned it happens on the second run.

Node v6.1.0
Yarn v0.17.0
ubuntu 14.04

**Comment by jswanner** [comment]
I just tried with the latest master, and while I do see `Building fresh packages...` in the output, I need to run `npm rebuild node-sass` afterwards in order for the app to run.

Node 7.1.0
Yarn 0.18.0-0
OS X 10.11.6

**Comment by jswanner** [comment]
This is now resolved for me with Yarn 0.17.2.

**Comment by torifat** [comment]
Closing this. Please feel free to let us know if you face this problem in `>= v0.17.2`

**Comment by jswanner** [comment]
I'm sorry, I spoke too soon. I thought I tested this with my `postinstall` work-around removed, but apparently not. I am still experiencing this problem with v0.17.2.

**Comment by torifat** [comment]
@jswanner no worries. Thanks for reporting it back though 😄

**Comment by hassankhan** [comment]
Sorry, late to the party, but yeah same thing, no dice 😢

**Comment by jesperronn** [comment]
FYI on my project (which has a lot of dependencies, but I think this is the problem). 

I can see that Yarn (0.17.2) removes some dependencies after a run. Notice the lines stating `unbuild ...` below:

```
$ yarn
yarn install v0.17.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "eslint@>=0.16.0".
warning Unmet peer dependency "jasmine-core@*".
warning Unmet peer dependency "request@^2.34".
warning Unmet peer dependency "request@^2.34".
[4/4] 📃  Building fresh packages...
$ bower install && npm prune && bower prune
(node:2271) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

bower tinymce-dist    extra-resolution Unnecessary resolution: tinymce-dist#4.3.12
unbuild uid-number@0.0.6
unbuild fstream-ignore@1.0.5
unbuild tar-pack@3.3.0
unbuild node-pre-gyp@0.6.31
(node:2298) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
✨  Done in 18.13s.
```

So, the dependencies being unbuilt in the final step are as far as I can see not being removed by npm prune. Somehow `npm prune` and yarn's `unbuild` do different things??

**Comment by bestander** [comment]
So I am trying to repro on master branch:
```
$ yarn add node-sass
yarn add v0.18.0-0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 180 new dependencies.
├─ abbrev@1.0.9
...
✨  Done in 8.94s.
$ ls -al node_modules/node-sass/vendor/darwin-x64-48/
total 5088
drwxr-xr-x  3 bestander Domain Users      102 Nov 17 16:02 .
drwxr-xr-x  3 bestander  Domain Users      102 Nov 17 16:01 ..
-rw-r--r--  1 bestander  Domain Users  2602136 Nov 17 16:02 binding.node
```
Everything seems in place.
Can anyone give me a 100% list of commands to reproduce this?
Is it linux/windows only?

I think binding.node is downloaded instead of being rebuilt.
Could that be a reason?

Anyway, we need a step by step guide to repro this

**Comment by torifat** [comment]
@bestander it wasn't working me for either. The build step wasn't happening. After a `yarn cache clean`, it worked.

**Comment by lime** [comment]
> Can anyone give me a 100% list of commands to reproduce this?

This seems to be very difficult to reproduce consistently. 😕 It easily brings up red herrings, since it's likely that something you try at first seemingly fixes it, and then it only resurfaces later.

@STRML has some ongoing work in https://github.com/yarnpkg/yarn/issues/1852#issuecomment-261273692 / https://github.com/STRML/yarn-install-lifecycle-bug if someone else manages to get a reliable repro case.

As far as I can see, this looks like the same root issue as #1848, #1852 and #1872, right? Or has there been some indication that there are two separate things going on?

> Is it linux/windows only?

OS X 10.11.6 here.

**Comment by STRML** [comment]
These all seem related.

For those of you currently experiencing it, could you please make copies of your local and homedir `.npmrc` and `.yarnrc`, if any, and then try removing them and reinstalling? See if that clears it up. If it does, let's see if there's a common thread among them.

In my case, removing and recreating my `.npmrc` fixed the issue, even though the new `.npmrc` had the same content. I can no longer reproduce the bug.

**Comment by hassankhan** [comment]
So just updated to Yarn 0.17.4 and running `yarn` doesn't result in any errors. I would close but others seem to still be having issues.

**Comment by bestander** [comment]
Yes they all seem related.
#1817, related as well, got fixed between 0.17.0 and 0.17.3

**Comment by wyze** [comment]
@hassankhan, if you run `yarn cache clean && rm -rf node_modules`, it should reproduce this.

**Comment by victornoel** [comment]
I had the same problem, removing `node-sass` from the cache fixed it on the next run.

I also noticed some segmentation fault while running yarn on projects with a lot of dependencies and the cache was empty, and after it happened, node-sass had been put in the node_modules folder, but vendor wasn't there. So I suspect that the segmentation fault happens when the post install scripts are run.
And then people re-run yarn and yarn thinks node-sass is properly installed, which is not the case.

Something like that... but I can't find the error log anymore with yarn 0.17.3....

**Comment by hassankhan** [comment]
@wyze Nope, did what you said but I can't reproduce the error any more. Seems to be working fine now 👍

**Comment by bestander** [comment]
https://github.com/yarnpkg/yarn/issues/1912 is important to fix - Yarn silences build errors and this leaves us with inconsistent state

**Comment by dbashford** [comment]
Is this still a thing with `0.17.4`? Hard to track if it is fixed or not.

Had started seeing something along these lines with the bump to `0.17.2`.

**Comment by wyze** [comment]
I was unable to reproduce this on `0.17.4`.

**Comment by STRML** [comment]
Bizarrely, now I have the sass error with `0.17.4`. So something's still broken for sure. Trying to figure it out.

**Comment by STRML** [comment]
Clearing cache fixed the node-sass issue.

**Comment by kevinzwhuang** [comment]
Just tested on OS X El Capitan with v0.17.4, seems to be fixed in `latest`. I'm curious, what fixed this bug?

**Comment by wyze** [comment]
I think it was #1663 that fixed this. Closing as it is resolved.

**Comment by Danita** [comment]
FYI It wasn't working for me right after upgrading yarn to v0.17.4, but this fixed it:

```
yarn cache clean
rm -rf node_modules
yarn install
```

**Comment by xzyfer** [comment]
Still getting reports of this in 0.17.6 - https://github.com/sass/node-sass/issues/1804#issuecomment-261876302

**Comment by STRML** [comment]
https://github.com/karma-runner/karma-phantomjs-launcher/issues/120 is related as well

**Comment by oyeanuj** [comment]
Same as @Danita. Was seeing it in 0.17.9, just doing `yarn cache clean; yarn install` didn't help until I removed the `node_modules` folder as well and tried again.

**Comment by STRML** [comment]
I had this bite me on a Jenkins server after an upgrade to from v0.16.1 to v0.17.10; it appears the symlinks in `node_modules/.bin` are getting confused:

After upgrade before clearing cache & `node_modules`:

```
root@jenkins /v/l/j/w/proj $ ll ./node_modules/.bin/
total 80K
lrwxrwxrwx 1 jenkins jenkins  98 Dec  1 16:25 babel -> ../../../../.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel.js*
lrwxrwxrwx 1 jenkins jenkins 105 Dec  1 16:25 babel-doctor -> ../../../../.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel-doctor.js*
lrwxrwxrwx 1 jenkins jenkins 115 Dec  1 16:25 babel-external-helpers -> ../../../../.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel-external-helpers.js*
lrwxrwxrwx 1 jenkins jenkins 103 Dec  1 16:25 babel-node -> ../../../../.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel-node.js*
lrwxrwxrwx 1 jenkins jenkins 101 Dec  1 16:25 babel-watch -> ../../../../.cache/yarn/npm-babel-watch-2.0.3-39f5eac86dd6374010723784911f17695a665d53/babel-watch.js*
```

After clearing:

```
root@jenkins /v/l/j/w/proj $ ll ./node_modules/.bin/
total 0
lrwxrwxrwx 1 jenkins jenkins 25 Dec  1 16:44 babel -> ../babel-cli/bin/babel.js*
lrwxrwxrwx 1 jenkins jenkins 32 Dec  1 16:44 babel-doctor -> ../babel-cli/bin/babel-doctor.js*
lrwxrwxrwx 1 jenkins jenkins 42 Dec  1 16:44 babel-external-helpers -> ../babel-cli/bin/babel-external-helpers.js*
lrwxrwxrwx 1 jenkins jenkins 30 Dec  1 16:44 babel-node -> ../babel-cli/bin/babel-node.js*
lrwxrwxrwx 1 jenkins jenkins 29 Dec  1 16:44 babel-watch -> ../babel-watch/babel-watch.js*
```

**Comment by STRML** [comment]
Actually, I didn't post the full list: weirdly, this is still happening in CI (maybe another bug), but only devDeps are getting mixlinked:

```
root@jenkins /v/l/j/w/proj $ ll node_modules/.bin
total 80K
lrwxrwxrwx 1 jenkins jenkins  98 Dec  1 16:49 babel -> ../../../../.cache/yarn/npm-babel-cli-6.18.0-92117f341add9dead90f6fa7d0a97c0cc08ec186/bin/babel.js*
...
lrwxrwxrwx 1 jenkins jenkins  19 Dec  1 16:49 jade -> ../jade/bin/jade.js*
lrwxrwxrwx 1 jenkins jenkins  33 Dec  1 16:49 markdown-it -> ../markdown-it/bin/markdown-it.js*
lrwxrwxrwx 1 jenkins jenkins  90 Dec  1 16:49 mocha -> ../../../../.cache/yarn/npm-mocha-3.1.2-51f93b432bf7e1b175ffc22883ccd0be32dba6b5/bin/mocha*
lrwxrwxrwx 1 jenkins jenkins  91 Dec  1 16:49 _mocha -> ../../../../.cache/yarn/npm-mocha-3.1.2-51f93b432bf7e1b175ffc22883ccd0be32dba6b5/bin/_mocha*
```

**Comment by MatthiasKuehneEllerhold** [comment]
Still happenening with yarn 0.19.1 :/

**Comment by intellix** [comment]
0.20.0 fixed it for OSX, but still getting this on Linux with Codeship. The vendor folder just isn't there :(

**Comment by lekkerduidelijk** [comment]
@intellix Check https://github.com/sass/node-sass/issues/1579#issuecomment-279062990

**Comment by Tiendq** [comment]
Still not fixed with 0.21.3 on macOS 10.12 :(

**Comment by xiaoyu2er** [comment]
```
// package.json
"scripts": {
    "update": "yarn install && npm rebuild node-sass"
  },
```
😢

**Comment by bestander** [comment]
For those who still have this issue please open a new one with steps to reproduce and cc me

**Comment by Tiendq** [comment]
FYI, I no longer see this issue with yarn 22 and now 23 on macOS. Including fresh install for new project.

**Comment by elimcjah** [comment]
@kittens has taken notice to the issue and with issue #3224 hopefully we have a fix in the near future.

**Comment by virgofx** [comment]
How to reproduce consistently:

CircleCI 2.0 Docker program.

1) Create your project as is with a package.json. Create yarn lock file via yarn install/upgrade.
2) Add `node-sass` or `gulp-sass` into project (Currently testing with `gulp-sass`)
3) Ensure proper tokens are hooked into repository to allow webhooks for CircleCI
4) Ensure project is configured to use CircleCI Beta 2.0 (Apply on their website)
5) Add the following into `.circleci/config.yml`. 
6) Check in code.

The first run, the docker container will be built, no cache will exist, yarn will run an install, and then perform a successful compilation of sass using gulp-sass. It will **succeed**.

Do another noop checkin. The following build will pull the cache, and then attempt to install dependencies. Upon compiling the sass, it will consistently with:

```
yarn run css
yarn run v0.23.4
$ gulp css
fs.js:914
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/root/website/node_modules/node-sass/vendor'
```


**./.circleci/config.yml**
```yml
version: 2
jobs:
  build:
    working_directory: ~/project
    
    docker:
      - image: node:7.10

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --pure-lockfile --no-progress
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
# ADD THIS COMMAND HERE THAT USES NODE-SASS / GULP-SASS
#      - run:
 #         command: yarn run css  
```

Refs:
* https://github.com/sass/node-sass/issues/1804

**Comment by bestander** [comment]
Commenting on old closed issue won't help, please create a new one if you have repro steps with latest yarn
