### ISSUE TITLE
[0.17] NODE_PATH problem when using Yarn from repo: can't find module yarn/node_modules/detect-indent/node_modules/repeating/index.js

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1854]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

If you use yarn from `<github>/bin/yarn` it has a problem with node_modules path.

Yarn 0.16.1
```
$ yarn build
yarn build v0.16.1
$ gulp build
[15:57:22] Using gulpfile ~/yarn/gulpfile.js
[15:57:22] Starting 'build-modern'...
[15:57:22] Starting 'build-legacy'...
[15:57:22] Finished 'build-modern' after 200 ms
[15:57:22] Finished 'build-legacy' after 185 ms
[15:57:22] Starting 'build'...
[15:57:22] Finished 'build' after 34 μs
✨  Done in 1.19s.

$ cd ~/<TEMP_FOLDER>
$ ~/yarn/bin/yarn init
yarn init v0.16.1
question name (yarn-init):
question version (1.0.0):
question description:
question entry point (index.js):
question git repository:
question author:
question license (MIT):
success Saved package.json
```

In latest master:

```
$ yarn build
yarn build v0.16.1
$ gulp build
[15:57:22] Using gulpfile ~/yarn/gulpfile.js
[15:57:22] Starting 'build-modern'...
[15:57:22] Starting 'build-legacy'...
[15:57:22] Finished 'build-modern' after 200 ms
[15:57:22] Finished 'build-legacy' after 185 ms
[15:57:22] Starting 'build'...
[15:57:22] Finished 'build' after 34 μs
✨  Done in 1.19s.

$ cd ~/<TEMP_FOLDER>
$ ~/yarn/bin/yarn init
/Users/bestander/yarn/bin/yarn.js:47
      throw err;
      ^
Error: ENOENT: no such file or directory, open '/Users/bestander/yarn/node_modules/detect-indent/node_modules/repeating/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.Module._extensions..js (module.js:549:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Please mention your node.js, yarn and operating system version.**
Node v6.2.1
Mac OS

**Comment by hpurmann** [comment]
Cannot reproduce this with current `master` (b84fde34600bc6bf91a01ea4796ebf3bd8bff0d3).

**Comment by bestander** [comment]
Looks like it was roadrunner issue, now fixed in 0.17.7

**Comment by markusv** [comment]
we still have this problem on Windows Server 2012 R2 with yarn 0.19.1
