### ISSUE TITLE
Issue with post install scripts

### ISSUE THREAD

**Issue by avetisk** [yarnpkg/yarn#1932]
**What is the current behavior?**
Currenty, I'm running into an error with the package `node-sass`, but when using `npm install` instead of `yarn` it works.

**If the current behavior is a bug, please provide the steps to reproduce.**
Well, it will be easier to check this comment https://github.com/sass/node-sass/issues/1579#issuecomment-251002136

**What is the expected behavior?**
Post install scripts to run properly, and thus in my case, getting the `vendor` directory with its proper content (cf. linked issue).

**Please mention your node.js, yarn and operating system version.**
node: `7.1.0`
yarn: `0.17.3` (latest version available from `brew`)
OSX: `10.11.6`

**Comment by DevSide** [comment]
**What is the current behavior?**
post-install script is not called 

**If the current behavior is a bug, please provide the steps to reproduce.**
- yarn init
- yarn add imagemin-optipng
- (yarn install ?)

**What is the expected behavior?**
optipng which is a dependency of imagemin-optipng should execute its postinstall script and get as @avetisk a vendor folder

**Please mention your node.js, yarn and operating system version.**
Node 6.4
Yarn 0.17.4
Os: Linux/Ubuntu 16, arch 64

**Comment by SimenB** [comment]
#1852

**Comment by avetisk** [comment]
@SimenB : just upgrade to `0.17.4` but still having the same issue.

**Comment by avetisk** [comment]
My bad, just had to clean the cache, etc.

**Comment by avetisk** [comment]
Well, now I'm having issues with `sass-lint`...

And of course `npm i` solves it...

```
$ ./node_modules/.bin/sass-lint --no-exit --verbose --syntax scss --config ./.sass-lint.yml
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './node_modules/sass-lint/lib/config/sass-lint.yml'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.loadDefaults (./node_modules/sass-lint/lib/config-helpers.js:13:27)
    at module.exports (./node_modules/sass-lint/lib/config.js:80:26)
    at Function.sassLint.getConfig (./node_modules/sass-lint/index.js:31:10)
    at Object.<anonymous> (./node_modules/sass-lint/bin/sass-lint.js:76:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
error Command failed with exit code 1.
```

**Comment by DevSide** [comment]
Ok, it's weird that `yard cache clean` fix my problem since i never use yarn before.

**Comment by bestander** [comment]
Can you check on 0.17.5, we have fixed how we purge build artifacts in caches, that should help

**Comment by avetisk** [comment]
@bestander: just tried with the new version (after cleaning cache and all), but still not working.

**Comment by bestander** [comment]
@avetisk, please provide a gist how to reproduce this.
Is this a regression since 0.16.1?

**Comment by avetisk** [comment]
`0.17.6` fixed it.

@bestander: I tried to reproduce the bug with a scoped env, but failed to do so.

Maybe it's the combination of my dependencies which made it?

Here is the list:

```javascript
  "dependencies": {
    "express": "5.0.0-alpha.2",
    "morgan": "^1.7.0",
    "react": "^15.4.0",
    "react-addons-css-transition-group": "^15.4.0",
    "react-dom": "^15.4.0"
  },
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-plugin-transform-dirname-filename": "^1.1.0",
    "babel-plugin-transform-object-rest-spread": "^6.19.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "css-loader": "^0.26.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.1.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.6.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "json-loader": "^0.5.4",
    "node-sass": "^3.13.0",
    "nodemon": "^1.11.0",
    "sass-lint": "^1.10.2",
    "sass-loader": "^4.0.2",
    "source-map-support": "^0.4.6",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.3"
  }
```

**Comment by DevSide** [comment]
If one `postinstall / install` script failed during install, the other `postinstall / install` scripts are not executed. So, some dependencies break the complete install process, is it what we yarn want ? @avetisk

**Comment by avetisk** [comment]
@DevSide the thing is that if anything failed during the `postinstall` / `install`, then it was completely silent...which sounds very bad (no pun intended).

**Comment by DevSide** [comment]
There is also a problem with the path where are executed the scripts, here is an exemple with sprity-lwip:

lwip has a install script: `node-gyp rebuild`

**npm execute the script in [MY_PATH]/node_modules/lwip **
```
> lwip@0.0.9 install [MY_PATH]/node_modules/lwip
> node-gyp rebuild
make: Entering directory '[MY_PATH]/node_modules/lwip/build'
```

**yarn execute the script in [MY_PATH]/node_modules/sprity/node_modules/lwip **
```
error /home/thomas/dev/m6web/site-6play-v4/node_modules/sprity/node_modules/lwip: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/thomas/dev/m6web/site-6play-v4/node_modules/sprity/node_modules/lwip
```
