### ISSUE TITLE
Yarn places organization-scoped "bin" links wrong

### ISSUE THREAD

**Issue by LinusU** [yarnpkg/yarn#2004]
**Do you want to request a *feature* or report a *bug*?**

I want to report a **bug**

**What is the current behavior?**

When installing a package scoped under an organization (e.g. `@org/pkg`), that has a "bin" exposed, that bin gets placed in the folder `node_modules/.bin/@org`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn` on a package that has a scoped dependency, that has a "bin" field in it's `package.json`.

**What is the expected behavior?**

I expect the bin to be placed in the folder `node_modules/.bin`.

**Please mention your node.js, yarn and operating system version.**

Node.js `7.1.0`
Yarn `0.17.6`
macOS `10.12.1`

**Comment by johansteffner** [comment]
I'm having the same issue.

Node.js `6.9.1`
Yarn `0.17.6`
macOS `10.12.1 (16B2555)`

**Comment by SimenB** [comment]
#1885

**Comment by lgeiger** [comment]
I think this issue is already fixed by #2163

**Comment by mike-engel** [comment]
I'm still having this issue with a private scoped package that includes a binary.

```
yarn: 0.18.1
node: 6.9.2
npm: 3.10.9 (default with 6.9.2)
```

**Comment by LinusU** [comment]
#2313 was merged to the 0.18.x branch so it should be released in 0.18.2

**Comment by olingern** [comment]
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.
