### ISSUE TITLE
Yarn attempts to rebuild fsevents even on incompatible operating systems

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#2051]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`fsevents` is only relevant on Mac OS, it does not compile on Linux or Windows. Yarn appears to try and compile it even on incompatible operating system. This is a waste of time as it's always going to fail.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is the `package.json` from one of my sites:
```json
{
  "name": "sitename",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "devDependencies": {
    "assets-webpack-plugin": "~3.0.0",
    "babel-core": "~5.8.25",
    "babel-loader": "~5.3.2",
    "exports-loader": "~0.6.2",
    "expose-loader": "~0.7.0",
    "imports-loader": "~0.6.4",
    "webpack": "~1.12.2"
  },
  "repository": {
    "type": "git",
    "url": "daniel@host.dan.cx:/var/local/git/sitename"
  },
  "author": "Daniel Lo Nigro <daniel@dan.cx> (http://dan.cx/)",
  "scripts": {
    "build-dev": "NODE_ENV=development webpack -d",
    "build-prod": "NODE_ENV=production webpack -p",
    "watch": "NODE_ENV=development webpack --progress --colors --watch -d",
    "update-babel-helpers": "babel-external-helpers -l get,inherits,create-class,class-call-check,extends,interop-require-default > ./public/assets/js/babel-external-helpers.js"
  },
  "dependencies": {
    "array.prototype.find": "~1.0.0",
    "babel-runtime": "~5.8.25",
    "classnames": "^2.1.5",
    "fbemitter": "^2.0.0",
    "flux": "~2.1.1",
    "react": "~0.14.0",
    "react-onclickoutside": "git://github.com/Daniel15/react-onclickoutside.git"
  }
}
```

Running `yarn` gives me this as part of the output:
```
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
```

However, in the "Building fresh packages..." stage of installation, it still attempts to build the dependency, which obviously fails as it should only be built on Mac OS.

The installation still succeeds so this is not a blocker, it's just very odd behaviour.

The second time I run `yarn`, it shows that everything is up-to-date:
```
yarn install v0.17.8
warning sitename@0.0.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.28s.
```

However, when I add another dependency, it tries to build fsevents again.

**What is the expected behavior?**
Yarn should not attempt to build a native dependency if it's incompatible with the current OS

npm handles this correctly:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
```

**Please mention your node.js, yarn and operating system version.**
Yarn 0.17.8
Windows 10
Node.js 6.9.1

**Comment by nsgundy** [comment]
Having the same issue... makes the output look like there was an issue when running 'yarn install' and eats some extra seconds.

**Comment by schue30** [comment]
this problem should be solved with https://github.com/yarnpkg/yarn/pull/1997

**Comment by Daniel15** [comment]
Yes, confirmed fixed in latest nightly build:
```
yarn install v0.18.0-20161129.2058
info No lockfile found.
warning sitename@0.0.0: No license field
[1/4] Resolving packages...
warning babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
```

**Comment by bevacqua** [comment]
Doesn't seem to be fixed for linux.

```
Successfully built 926b219559f2
+ docker run --rm -v /var/jenkins_home/workspace/cloud-ui@2/cloud-ui:/src adminconsole-node:latest /bin/sh -c '
    set -ex;

    npm prune;

    npm install yarn >/dev/null;
    npm run yarn > /dev/null;

    npm run verify-deps;
    npm run lint;
    CI=true npm test;
  '
+ npm prune
+ npm install yarn
npm WARN prefer global yarn@0.18.0 should be installed with -g
+ npm run yarn
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
```

**Comment by renatoi** [comment]
What's progress on this bug? It makes `yarn` very slow to use for development.

**Comment by PowrSlave** [comment]
I am getting this error on a windows 7 machine and IT IS blocking me since I can't get any packages to install when it hits.

**Comment by mattbishop** [comment]
Still seeing this issue with yarn 1.9.4 on Azure DevOps (formerly VSTS)

**Comment by net** [comment]
Same issue on 1.9.4 with:

```json
"resolutions": {
  "**/fsevents": ">=1.2.4"
}
```

**Comment by madroneropaulo** [comment]
It seems that this issue is back.

**Comment by joeytwiddle** [comment]
Possibly related: I am on macOS, and fsevents is _rebuilding_ every time I run `yarn`, even if the correct version is already installed.

I don't think that used to happen. I think `yarn` used to finish immediately with the message "success Already up-to-date."

**Comment by inversion** [comment]
Getting this issue with 1.10.1 too on linux

**Comment by joeytwiddle** [comment]
People getting this problem, you might try upgrading from 1.10.1 to 1.12.1. That has fixed it for us.

**Comment by adamreisnz** [comment]
Getting this issue with 1.12.3, the install aborts with an error:

```
error fsevents@1.2.4: The platform "linux" is incompatible with this module.
error Found incompatible module
```

Used to be a warning and the module used to be ignored.

**Comment by Daniel15** [comment]
Are you sure fsevents is listed as an optional dependency? If it's not
optional, it'll fail on Linux, which is expected.

**Comment by adamreisnz** [comment]
It is a nested dependency, but I discovered that the problem was due to the following added lines in `package.json`:

```
"resolutions": {
    "nodemon/chokidar/fsevents": "1.2.4"
  }
```

This was needed to make it work with Node 10, but apparently manually adding the resolution forces yarn to try and install the package, even if it's an optional dependency.

**Comment by snewcomer** [comment]
Also saw this error.  Updating node from 6 to 8 fixed it for us.

https://travis-ci.org/ember-infinity/ember-infinity/jobs/478166551

**Comment by adamreisnz** [comment]
This is once again an issue on Node 10 with Yarn 1.14.0. Build on Heroku fails:

```
error fsevents@1.2.4: The platform "linux" is incompatible with this module.
error Found incompatible module
```

**Comment by adamreisnz** [comment]
I also encoutnered this again, we had fsevents in resolutions because of some prior issue, but that wasn't necessary anymore. However, I still think yarn shouldn't fail on an optional package, even if it's specified in the resolutions. Those resolutions should only be used if the package is actually installed (which it shouldn't on linux).

**Comment by nbaua** [comment]
Yarn still got this

> PROMPT>yarn global add @nestjs/cli
> yarn global v1.13.0
> 
> [1/4] Resolving packages...
> 
> [2/4] Fetching packages...
> 
> **info fsevents@1.2.7: The platform "win32" is incompatible with this module.**
> info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
> 
> [3/4] Linking dependencies...

I had to use npm force install for this.

**Comment by iemwill** [comment]
But did it worked afterwards? In my case not.

**Comment by jcollum-nike** [comment]
Still seeing it in 1.15.2 

```
+ yarn --network-timeout 100000 install

yarn install v1.15.2

[1/5] Validating package.json...

[2/5] Resolving packages...

[3/5] Fetching packages...

info fsevents@1.2.9: The platform "linux" is incompatible with this module.

info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
```

**Comment by ericlery** [comment]
Same on `node:lts-alpine / node:10.16.3-alpine` **docker images** that include **yarn** `1.17.3`.

Isn't it people on macOS and Windows this module without compatibility regards?

**Comment by jacorachan** [comment]
Windows 10 Build 16299 system output:

```console
λ yarn install
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 61.98s.
```
My package.json:

```json
{
    "name": "Test",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "serve": "vue-cli-service serve",
        "build": "vue-cli-service build",
        "lint": "vue-cli-service lint"
    },
    "dependencies": {
        "core-js": "^2.6.5",
        "vue": "^2.6.10",
        "vue-router": "^3.0.6"
    },
    "devDependencies": {
        "@vue/cli-plugin-babel": "^3.7.0",
        "@vue/cli-plugin-eslint": "^3.7.0",
        "@vue/cli-service": "^3.7.0",
        "@vue/eslint-config-standard": "^4.0.0",
        "babel-eslint": "^10.0.1",
        "eslint": "^5.16.0",
        "eslint-plugin-vue": "^5.0.0",
        "tailwindcss": "1.1",
        "vue-template-compiler": "^2.6.10"
    }
}
```

**Comment by ryantando** [comment]
Try this 

`yarn config set ignore-engines true`

**Comment by KiruthikaMKS1617** [comment]
> Try this
> 
> `yarn config set ignore-engines true`

Thanks, this worked in my case too.

**Comment by pgnd** [comment]
@ryantando 

> Try this
> `yarn config set ignore-engines true`

Should that^^ stop the incessant, every-time-yarn-execs noise,
```
...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
...
```

as well?

If not, any hints as to what can/does?

**Comment by syedzubairahmed001** [comment]
I am still facing this issue with v1.22.4
`yarn add notistack
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".`

**Comment by syedzubairahmed001** [comment]
I am still facing this issue with v1.22.4

`
 yarn add notistack
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
`

**Comment by adisher** [comment]
I believe it somehow effects my surge deployment process. I'm creating a workflow in github actions but it fails. 

yarn remove v1.22.4
[1/2] Removing module cra-template...
[2/2] Regenerating lockfile and installing missing dependencies...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
success Uninstalled packages.

**Comment by Daniel15** [comment]
@adisher It's just a warning and shouldn't actually break anything.

**Comment by papadi** [comment]
> Try this
> 
> `yarn config set ignore-engines true`

What are the side effects of this call?

**Comment by ianchanning** [comment]
@papadi Well, this is the yarn documentation for [`yarn install --ignore-engines`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-ignore-scripts):

> Do not execute any scripts defined in the project package.json and its dependencies.

So I assume that somewhere in the install chain there is some script that tries to install fsevents. But turning this off for ever seems a bit more than required. You could just try running `yarn install --ignore-engines` for this case.

**Comment by CeruttiMaicon** [comment]
I need to switch to a specific node version and it worked. :)

**Comment by smcelhinney** [comment]
> I need to switch to a specific node version and it worked. :)

And what version of `node` was that?

**Comment by thinnakrit** [comment]
> Try this
> 
> `yarn config set ignore-engines true`

It's work !!!

**Comment by ferenczy** [comment]
I have executed the `yarn` command in the [GitHub Desktop app's repository](https://github.com/desktop/desktop/) and got the following "info" severity messages:

> info fsevents@2.2.1: The platform "win32" is incompatible with this module.
> info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.

I'm not sure what exactly is the "optional dependency" and what consequences the fact that it's not being installed may have. Should I just ignore it? I have tried to use the option `--ignore-engines` with both `yarn` and `yarn install` but those messages are still being produced. I'm not sure I want to set it globally in the config as I don't know what consequences it may have (e.g. what potential errors I may miss).

**Comment by nbaua** [comment]
@ferenczy ,
FS Events is kinda pain in ***, if you are facing issues in your project creation or build at any point of time, consider using `npm install --no-optional` flag while installing your package(s) which are producing this error. If you're not facing any issues but freaked out (like me, few months back), you have 2 options, 

Option A) - Simply ignore as it is optional dependency(most of the time) 

OR 

Option B) - Switch to other supported OS, if you are comfortable working in non-windows OS enviornment.

**Comment by locofocos** [comment]
> It is a nested optional dependency, but I discovered that the problem was due to the following added lines in `package.json`:
> 
> ```
> "resolutions": {
>     "nodemon/chokidar/fsevents": "1.2.4"
>   }
> ```
> 
> This was needed to make it work with Node 10, but apparently manually adding the resolution forces yarn to try and install the package, even if it's an optional dependency.

This is fixed in yarn v2 https://github.com/yarnpkg/yarn/issues/7590 🎉 

For those of who are still using yarn v1..... instead of pinning `fsevents` directly in resolutions, you can pin a newer version of whatever dependency is pulling in fsevents. In our case, chokidar was listing fsevents as an optional dependency. So I found the newer version of chokidar that began consuming the fsevents version I need, then I set this version in package.json:
```
  "resolutions": {
...
    "chokidar": "^3.5.0"
  },
```

**Comment by nbaua** [comment]
After 1000+ days, the saga still continues..
Sometimes developers get so much caught in the dependency drains.
@locofocos . Thanks for posting this.

**Comment by nbaua** [comment]
BTW, as far as I recall, 
When I switched to PNPM, I never got this issue. 

@locofocos 
Can you please check that option as well ! If you have provision for checking the alternative package manager.
That would be a great help. Thanks.
