### ISSUE TITLE
--production seems to miss packages?

### ISSUE THREAD

**Issue by sontek** [yarnpkg/yarn#2141]
```
$ yarn --version
0.18.0
```
**What is the current behavior?**
Currently I'm using `npm` and I have these steps:

```
    npm install --progress=false --only=production
    npm run build:prod
```

and I'm trying to switch to yarn:

```
    yarn --production
    yarn run build:prod
```

The build prod command is just this:

```
NODE_ENV=production webpack --bail
```

With npm this succeeds but with yarn I get:

```
$ NODE_ENV=production webpack --bail
module.js:440
    throw err;
    ^

Error: Cannot find module 'domutils'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sontek/venvs/eventray/src/eventray/node_modules/css-select/lib/pseudos.js:14:19)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sontek/venvs/eventray/src/eventray/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sontek/venvs/eventray/src/eventray/node_modules/css-select/index.js:5:21)
    at Module._compile (module.js:541:32)
error Command failed with exit code 1.
```

But you can see here that css-select does have `domutils` as a dependency:
https://github.com/fb55/css-select/blob/master/package.json#L22

How can I get it to pull in all the proper dependencies?  When I do a `yarn list` I see that it was listed as a dependency:

```
─ css-select@1.2.0
│  ├─ boolbase@~1.0.0
│  ├─ css-what@2.1
│  ├─ domutils@1.5.1
│  └─ nth-check@~1.0.1
```

which is only one time it was listed, here is all the times:

```
$ yarn list|grep domutils
│  ├─ domutils@1.5.1
├─ domutils@1.5.1
│  ├─ domutils@1.5
│  ├─ domutils@1.1.6
│  │  ├─ domutils@1.1
```

but it isn't in `node_modules/`:

```
$ ls node_modules/|grep dom
dom-converter
domain-browser
domelementtype
pseudomap
react-dom
```

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v6.1.0

$ uname -a
Darwin Johns-MBP 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64
```

**Comment by kittens** [comment]
This is fixed by #2116 in 0.19.0.

**Comment by sontek** [comment]
ahh, when is `0.19.0` coming out?  I just upgraded to `0.18.0` today (I try whenever new versions come out, I've been having this issues since its release)

**Comment by todd** [comment]
@kittens It appears that #2116 is included in 0.18.0. However, I'm still seeing these issues when using that version. If there are more changes coming in 0.19.0, that's great, but it does look like the current ones have already shipped and the behavior hasn't been fixed.

**Comment by crisu83** [comment]
I also encountered this issue, even after upgrading to yarn **0.18**.

**Comment by sontek** [comment]
@kittens Hey, all of us are still experiencing this issue so the solutions that went into 0.18.0 (which was implemented in #2116) doesn't seemed to have addressed this specific problem. Could we re-open this issue to get it some attention?

**Comment by havenchyk** [comment]
it looks like this issue duplicates https://github.com/yarnpkg/yarn/issues/761

**Comment by bestander** [comment]
As #761 this should have been fixed by 0.19.0.
There is no package.json here for me to verify.
Please share a package.json to reproduce if it still does not work.

The best way to help is to run this:
```
yarn install --production --verbose
yarn check --production --verify-tree
```
With latest master branch.

**Comment by ebaynaud** [comment]
Should be re-open, see https://github.com/yarnpkg/yarn/issues/2263#issuecomment-273836173

**Comment by bestander** [comment]
Reopening this issue does not help much because this issue does not provide a test case to reproduce.
Feel free to open a new issue with a specific case that does not work for you

**Comment by ebaynaud** [comment]
Yep, ok it's in #2263 and seems fixed through https://github.com/yarnpkg/yarn/pull/2537. I'll test it when it will be released.
