### ISSUE TITLE
Log package which throws unmet peer dependency warning

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#2153]
**Do you want to request a *feature* or report a *bug*?**

_feature_

**What is the current behavior?**

`warning Unmet peer dependency "react-dom@^0.14.2 || ^15.0.0".`

**What is the expected behavior?**

`warning react-stickynode@1.2.1: Unmet peer dependency "react-dom@^0.14.2 || ^15.0.0".`

Similar to other warnings like this one:

`warning @mercateo/ws > karma-webdriver-launcher > wd > archiver > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

**Please mention your node.js, yarn and operating system version.**

```
$ node -v
v6.9.1

$ yarn -V
0.18.0

macOS 10.12.1
```

**Comment by donaldpipowitch** [comment]
I'd try to solve this with a PR. Notes for myself:

- Happens for "unmet" and "incorrect" peer dependency.
- Messages can be found here: https://github.com/yarnpkg/yarn/blob/cdfe06c59d7a17af2906d2e3c2e231d8115fdea6/src/reporters/lang/en.js#L149

**Comment by donaldpipowitch** [comment]
@bestander Did you fixed this already with [this commit](https://github.com/yarnpkg/yarn/commit/546c970551f47ae4ced2e4d90386ec434607009c)?

**Comment by bestander** [comment]
Yeah, looks like it was fixed

**Comment by donaldpipowitch** [comment]
Okay, thanks. But #2207 was not released yet, right? I can't find it on the releases page and `0.18.1` still shows me the same warning.

**Comment by bestander** [comment]
Yeah, it is on master branch now.
We'll do a release early next week
