### ISSUE TITLE
Bin files for transitive dependencies not created

### ISSUE THREAD

**Issue by borela** [yarnpkg/yarn#2341]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
If a package is not a direct dependency, its bin files are not added to the .bin directory.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add [this package](https://www.npmjs.com/package/del) as a dependency, it depends on `rimraf` which would normally generate binaries in the .bin directory but in this case it won't as it is not a direct dependency.

**What is the expected behavior?**
All binaries of all dependencies should be created and this is npm's current behaviour. This is important as it allows us to create dependency presets and just have the project linked to that preset instead of tons of packages.

**Please mention your node.js, yarn and operating system version.**
0.18.1 Windows 7

**Comment by philostler** [comment]
Same here, I've had to rewrite the script section of many of my package.json files due to this bug. I've a shared core in my platform that multiple projects are children of, and I've patched over this for now by referencing the bin with the node_modules directly, messy though.

**Comment by adhamhf** [comment]
same here...  eslint is in a transitive dependency in our setup and the binary in ./node_models/.bin is not getting setup.

**Comment by pluma** [comment]
This also affects users of [snazzy](https://www.npmjs.com/package/snazzy) who haven't installed [standard](https://www.npmjs.com/package/standard) as a direct dependency.

**Comment by bestander** [comment]
This is fixed now

**Comment by philostler** [comment]
I'm still encountering this bug with v0.24.6. Is the fix yet to be released?

**Comment by bestander** [comment]
Try 0.25.4
