### ISSUE TITLE
Using yarn 0.21.3 in docker got warning: You don't appear to have an internet connection

### ISSUE THREAD

**Issue by nickeljew** [yarnpkg/yarn#2850]
Using official docker image node:6.10.0, and yarn 0.21.3 is included. The docker environment is running on CentOS7.

The network of the docker image is ok, coz both of 'agt-get xxx' and 'npm install -g xxx' work well.

However when running yarn, I got the following warning:

Step 7/9 : RUN yarn
---> Running in 7dbcdcfcb8b9
yarn install v0.21.3
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...

-------
After several failed tryouts, I completed the building successfully finally. 
https://github.com/nodejs/docker-node/issues/353

But I still wanna know if this warning is a bug or something else should be noticed?

**Comment by flocsy** [comment]
I have pretty much the same problem. On different docker containers it works/fails, but not all the time, however there are containers where it happens 90% of the time, and on others 10%

**Comment by JohnnyEstilles** [comment]
Still present in 0.27.5

**Comment by tristanpemble** [comment]
Relevant: https://stackoverflow.com/questions/40186104/yarn-warning-on-docker-build

**Comment by BYK** [comment]
This should be resolved via 1.1.0 with the addition of DNS caching. Reopen if it persists with the latest version of Yarn please.

**Comment by antono** [comment]
Having the problem on Google App Engine (uses docker):
```
A  yarn run v1.3.2
 
A  warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
 
```

**Comment by neXorianus** [comment]
problem still present 
Docker version 17.12.0-ce, build c97c6d6
Yarn version 1.5.1

In my case even after several minutes (like 4 to 5 info lines) it would not get anything.

**Comment by rickonji** [comment]
problem still present
