### ISSUE TITLE
Cannot set version-tag-prefix to empty string

### ISSUE THREAD

**Issue by FissionCat** [yarnpkg/yarn#2856]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
```
$ yarn config set version-tag-prefix ''
yarn config v0.21.3
success Set "version-tag-prefix" to true.
✨  Done in 0.04s.
```

When running `yarn version`, this then adds a tag of the form `true<version>`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `yarn config set version-tag-prefix ''` as above.

I've tried `yarn config set version-tag-prefix false` and `yarn config set version-tag-prefix null` to see if they produce the desired result, but they gave me tags of the form `false<version>` and `null<version>`, respectively (not surprised there, just being thorough).

I have also tried running `yarn config delete version-tag-prefix`, but that just sets its value back to the default, `'v'`.

**What is the expected behavior?**
`yarn config set version-tag-prefix ''` should set the value of `version-tag-prefix` to `''`

**Please mention your node.js, yarn and operating system version.**
node: v6.7.0
yarn: v0.21.3
OS: macOS Sierra (10.12.3)

**Comment by arcanis** [comment]
Should be fixed in master (#3018)

**Comment by FissionCat** [comment]
@arcanis I've tested with 0.23.3, it's still failing on my machine:

```
$ yarn config set version-tag-prefix ''
yarn config v0.23.3
success Set "version-tag-prefix" to true.
✨  Done in 0.04s.
$ yarn config list
yarn config v0.23.3
info yarn config
{ 'version-tag-prefix': true,
...etc.
```

**Comment by arcanis** [comment]
The fix will be released along with the 0.24 build, which will be published somewhere this week.

**Comment by FissionCat** [comment]
Ah, okay - my bad, I assumed the fix had been released. Thanks for letting me know!

**Comment by retog** [comment]
Still having this issue. First experienced it with yarn v1.3.2 now updated to v1.5.1 but the problem is still there, exactly as described by @FissionCat
