### ISSUE TITLE
`yarn licenses generate-disclaimer` via `child_process` Creates Trimmed Output

### ISSUE THREAD

**Issue by dwighthouse** [yarnpkg/yarn#2967]
Apologies if this is somehow a Node or `child_process` related issue. I have been experimenting and googling for hours, and I can't find a solution to this very odd behavior. The evidence below leads me to, somewhat skeptically, infer that this is Yarn's problem.

**Bug**
This is probably a bug, and probably specific to Yarn.

**Current Behavior**
Running `yarn licenses generate-disclaimer` results in a full license disclaimer for the current directory, including my own projects, just fine. This output can be piped to a file using something like `yarn licenses generate-disclaimer > out.txt`. As a test, I ran this command on `origin/master` of Yarn's repository itself (latest log sha: 6e9a9a6596ca8f177f68f6672a1ef4ff16705336). The resulting file contains 460943 characters.

However, when running `yarn licenses generate-disclaimer` via a `child_process` `spawn`, the data returned is severely trimmed. The output contains only the first 7903 characters of the previously discussed `out.txt`. That is, the total characters returned through the stdout's buffers is 7903. Viewing the text output, it is as if the data just stops at some arbitrary point. The number of characters actually returned is consistent from run to run, but how many are returned appears to be related to the project the command is being run in.

It's as if the program stops right in the middle of the stream of data, sentences getting cut off in the middle.

Note that increasing the buffer size (maxBuffer option) and explicitly setting the current working directory (cwd option) has had no effect in my testing.

Furthermore, both the `spawn` and `exec` forms of `child_process` produce differently sized, but still wrongly trimmed, outputs. When running something equivalent via `exec`, the output size is 49961 characters, still almost 10 times shorter than normal.

I believe this is a Yarn-specific issue because other commands do not appear to have this restriction or otherwise end arbitrarily early. For example, if running the command `cat out.txt` via `child_process` on the `out.txt` file generated earlier, the resulting character count is 460943, exactly the correct number.

**Steps to Reproduce**

1. Git clone my fork of Yarn: https://github.com/dwighthouse/yarn.git
2. Move to the newly created yarn directory.
3. Execute: `yarn licenses generate-disclaimer > out.txt`
4. Observe the character count of this `out.txt` file (460943).
5. Execute: `node testSpawn.js`
6. Observe that the total character count of the data streams is only 7903 characters.
7. Execute: `node testExec.js`
8. Observe that the total character count of the data buffer is only 49961 characters.
9. Execute: `node testCat.js`
10. Observe that the total character count of the data buffer is exactly 460943 characters, the correct number.

**Expected Behavior**
The character count from `node testSpawn.js`, `node testExec.js`, and `node testCat.js` should all be identical to the character count of the `out.txt` file.

**Versions**
Running latest stable Yarn (0.21.3) (6e9a9a6596ca8f177f68f6672a1ef4ff16705336), installed globally. Mac OS 10.11.6 (15G1217). Node version 6.9.1.

**Additional Info**
When testing my own project in which I discovered this issue, our build server (running some version of Linux) produces still different output. It appears to output a different set of disclaimers, but still appears to be somewhat trimmed. No hard confirmation, however. Also, it adds this to the top of the file which is not present when building on Mac:
```
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
```

**Theory**

* Could it be that Yarn is triggering an end or close signal on the `child_process`?
* Is Yarn doing something that assumes it is being run from the command line, and not via a `child_process`?
* Is there some kind of timeout on either the `child_process` (unlikely, I explicitly set a 10 second timeout, and the program ended prior to that duration).
* Is there some kind of timeout on Yarn's `generate-disclaimer` when run as a `child_process`?

**Comment by arcanis** [comment]
It seems that this issue is resolved, can you confirm? I'm going to close it in the meantime.

**Comment by dwighthouse** [comment]
@arcanis I can confirm IT IS NOT RESOLVED on my system. I get exactly the same results as described, running yarn version 0.22.0 (the latest version available via NPM) and 0.23.3 (the latest release of yarn period). I get almost identical results with the latest version. The output being a different length by one character, which is not significant in this case

**Comment by merceyz** [comment]
Closing as this has probably been fixed since then, if not there is a feature request (ish) for this in v2 https://github.com/yarnpkg/berry/issues/1164
