### ISSUE TITLE
yarn init freeze

### ISSUE THREAD

**Issue by hudsonof** [yarnpkg/yarn#3613]
I am using Windows 10 and PowerShell as console

I installed yarn normally by the installer downloaded from the official website
When I do a yarn --version it returns me the normal version
But when I do a yarn init I type the name of the project and press Enter, then the version line appears but does not enter anything because the console is frozen.

**Comment by rally25rs** [comment]
Could you please specify:

* Version of Yarn
* Version of NodeJS

Thanks!

**Comment by hudsonof** [comment]
Yarn 0.24.6
NodeJS 8.1.0

**Comment by hakanderyal** [comment]
Same thing happening to me on macOS.

Yarn installed with brew, using --ignore-dependencies option.
Yarn 0.24.6
NodeJs 8.1.0, using nvm.

**Comment by hakanderyal** [comment]
Just tried with Node 8.0.0, using nvm, everything works. There seems to be a problem with node 8.1.0.

**Comment by Dbuggerx** [comment]
Same problem here on Fedora 25.
Yarn v0.24.5
NodeJs v8.1.0 (using nvm)

**Comment by Lytol** [comment]
Same on Debian strectch (testing)
Yarn 0.24.6
Node 8.1.0

**Comment by thenoen** [comment]
Same on Windows 10
Yarn 0.24.6 (msi installer)
Node 8.1.0 (msi installer)

**Comment by erwinw** [comment]
Seems to be a Node v8.1.0 bug, triggered via read and readline: https://github.com/nodejs/node/issues/13557 .

To quote: "it'll be fixed in the next v8.x release, scheduled for next Tuesday"  (June 20th).

**Comment by bestander** [comment]
Ok, closing as it should be fixed by latest Node.

**Comment by cosola** [comment]
Yarn still not working properly with Powershell as console. It freezes at "Question (version 1.0.0):" I using Windows 7 Prof.

**Comment by BYK** [comment]
https://github.com/yarnpkg/yarn/issues/3613#issuecomment-308656174 actually implies the solution which is upgrading Node. You mentioned you are using 8.1 and the latest is 8.5 so try upgrading your Node :)

**Comment by cosola** [comment]
Thanks. Will try today. Actually, both yarn init and npm init freeze at the same level, regardless of the shell use - Powershell, CMD, Git-shell, Git-CMD.  In several occasions I got a long message that others have received : yarn init ...."can't answer a question unless a user TTY" info ....
