### ISSUE TITLE
Git Archive Fails on Private Gitlab Repo

### ISSUE THREAD

**Issue by migeorge** [yarnpkg/yarn#4172]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Run
```
yarn add git+ssh://git@gitlab-server.example:user/repo.git#tag
```

Result
```
yarn add v0.28.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive --remote=git@gitlab-server.example:user/repo.git master
Directory: /Users/user/projects/project
Output:

info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Another thing I've noticed looking at the git archive command it looks like yarn is attempting to pull an archive of the master branch even though I specified a tag.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Host private repository on Gitlab CE
2) Attempt to add to another yarn project
3) Hopefully see this error

If someone needs access to a hosted repo on Gitlab CE I can set something up and invite per request.

**What is the expected behavior?**

The dependency should be downloaded and added to the project.

**Please mention your node.js, yarn and operating system version.**
node: v6.10.2
yarn: v0.27.5 (also v0.28.4)
macOS: 10.12 (16A323)

**Comment by migeorge** [comment]
Hacking on this a bit with my local yarn installation I found that adding my Gitlab installations hostname to the map defined at the following line (26) in `/src/util/git.js` allowed the dependency to be installed.

https://github.com/yarnpkg/yarn/blob/67dfc7af80bad0034a1f23e9ef4da8c696e134c7/src/util/git.js#L26

This isn't a good solution, or even a good workaround but I believe it does highlight the issue.

Is there some configuration that can be set to disable `git archive` for a specific host from within the project?

**Comment by BYK** [comment]
@migeorge this part should be catching situations like these: https://github.com/yarnpkg/yarn/blob/67dfc7af80bad0034a1f23e9ef4da8c696e134c7/src/util/git.js#L95-L101

Either it is a bug or this is not related to the archive capabilities and something else. Since you mention private repos, I suspect it may be related with credentials etc?

**Comment by migeorge** [comment]
@BYK It could be something with credentials. Before I ran into this error I was getting a "Public key denied" error. I solved that by adding my key to the ssh agent.

If I run the `git archive` command that yarn is attempting myself it seems to work. Is there some other configuration that is needed for `git archive` to use my ssh key?

**Comment by BYK** [comment]
>If git archive fails for a reason other than the repository not supporting it should yarn attempt a normal pull / fetch anyways? The reason I ask is in this case a normal pull via yarn will work.

I think it tries first and then stores the setting and never checks again, which also implies a credentials problem to me. May be your keychain gets locked (if you are on macOS), or your ssh agent dies or something?

**Comment by migeorge** [comment]
@BYK I'm not sure that this is an authentication issue. Along with a coworker I was able to reproduce it on another machine so I think that rules out a local configuration issue.

For what it's worth NPM handles the dependency properly but I'm not sure how git fetching works in NPM, maybe they aren't using `git archive`

**Comment by migeorge** [comment]
If I were to work on a PR that creates a fallback for a `git archive` failure is there a chance for it to be pulled in?

**Comment by migeorge** [comment]
@BYK It looks like it may have been a `git` problem. I noticed that everything was working properly on our CI server so I updated `git` from 2.12.x to 2.14.1 and everything worked!

Thanks for jumping in on the conversation!

**Comment by BYK** [comment]
@migeorge glad it was fixed!

>Along with a coworker I was able to reproduce it on another machine so I think that rules out a local configuration issue.

Now you have "use the CI machine too" on your list of things to check for local config issues :P

**Comment by migeorge** [comment]
It turns out that I'm still experiencing this issue with Yarn v1.1.0 on MacOS. Everything works as expected on linux.

Maybe the mac is having trouble authenticating for the git archive call?
