### ISSUE TITLE
Install generates warnings: The case-insensitive file shouldn't be copied twice in one bulk copy

### ISSUE THREAD

**Issue by artlogic** [yarnpkg/yarn#4363]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When installing with cordova as a dependency, I receive lots of warnings in the form of: `warning The case-insensitive file /Users/artlogic/Code/random/yarn-issue/node_modules/npm/node_modules/readable-stream/lib/internal/streams/BufferList.js shouldn't be copied twice in one bulk copy`

These files all seem to be related to npm.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a simple `package.json` with cordova as a dependency:
```json
{
  "name": "yarn-issue",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "cordova": "^7.0.1"
  }
}
```

Run `yarn install`.

See a lot of warnings that look like this: `warning The case-insensitive file /Users/artlogic/Code/random/yarn-issue/node_modules/npm/node_modules/readable-stream/lib/internal/streams/BufferList.js shouldn't be copied twice in one bulk copy`

**What is the expected behavior?**
I don't expect to see all these error messages - they were not appearing before.

**Please mention your node.js, yarn and operating system version.**
Node 6.11.3, Yarn 1.0.1, Mac OS 10.11.6

**Comment by OmgImAlexis** [comment]
Same issue here. I wasn't getting this until one of the last few yarn updates but I'm also getting it for other packages.

```
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/CHANGELOG.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/appveyor.yml shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/bin shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/.npmignore shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/.travis.yml shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/bin shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/examples shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/test shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp.cmd shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/build.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/clean.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/configure.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/info.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/package.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/pre-binding.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/publish.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/rebuild.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/reinstall.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/reveal.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/testbinary.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/testpackage.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/unpublish.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/bin/nopt.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/examples/my-program.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/lib/nopt.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/nopt/test/basic.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/abi_crosswalk.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/nw-pre-gyp shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/s3_setup.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/.config/yarn/global/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/package.json shouldn't be copied twice in one bulk copy
```

```
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex/browser.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/xo/code/@lad/logger/node_modules/nyc/node_modules/md5-hex/readme.md shouldn't be copied twice in one bulk copy
```

**Comment by adamreisnz** [comment]
Also happening for the `serialport` package. What is the reason for this warning?

**Comment by OmgImAlexis** [comment]
Seems this is happening with more and more packages as I update my deps.

**Comment by BYK** [comment]
Duplicate of #3751.

**Comment by aichholzer** [comment]
Yep, same here.

**Comment by AnthoniG** [comment]
Likewise I am getting it for all packages in my package.json. 
Did not happen on previous versions of yarn, so why now ?

Here is my package.json :-
```
{
  "name": "leadfinderlocal",
  "version": "3.3.0",
  "private": true,
  "proxy": "http://localhost",
  "dependencies": {
    "async": "^2.5.0",
    "axios": "^0.16.2",
    "classnames": "^2.2.5",
    "google-maps": "^3.2.1",
    "lodash": "^4.17.4",
    "mobx": "^3.2.2",
    "mobx-react": "^4.2.2",
    "mobx-react-devtools": "^4.2.15",
    "mobx-react-router": "^4.0.1",
    "moment": "^2.18.1",
    "object-hash": "^1.1.8",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-dropzone": "^3.13.1",
    "react-modal": "^1.7.7",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts-ts": "^2.6.0",
    "react-transition-group": "1.2.0",
    "reactstrap": "^4.8.0",
    "safe-eval": "^0.3.0",
    "scriptjs": "^2.5.8"
  },
  "devDependencies": {
    "@types/google-maps": "^3.2.0",
    "@types/scriptjs": "^0.0.2",
    "@types/classnames": "^2.2.3",
    "@types/lodash": "^4.14.74",
    "@types/moment": "^2.13.0",
    "@types/node": "^8.0.26",
    "@types/object-hash": "^0.5.29",
    "@types/prop-types": "^15.5.1",
    "@types/react": "^16.0.5",
    "@types/react-dom": "^15.5.4",
    "@types/react-dropzone": "^0.0.32",
    "@types/react-modal": "^1.6.6",
    "@types/react-router": "^4.0.15",
    "@types/react-router-dom": "^4.0.7",
    "@types/reactstrap": "^4.3.13",
    "concurrently": "^3.5.0",
    "node-sass-chokidar": "^0.0.3",
    "npm": "^5.3.0"
  },
  "scripts": {
    "start-ts": "set PORT=4000 && concurrently \"react-scripts-ts start\" ",
    "start": "set PORT=4000 && concurrently \"npm run watch-css\" \"react-scripts-ts start\"",
    "build": "npm run build-css && react-scripts-ts build",
    "build-css": "node-sass-chokidar src/styles/scss -o src/styles/css",
    "build-scripts": "react-scripts-ts build",
    "watch-css": "npm run build-css && node-sass-chokidar src/styles/scss -o src/styles/css --watch --recursive"
  }
} 
```

**Comment by aichholzer** [comment]
And back to `npm` I go...
👍

**Comment by RafaPolit** [comment]
Same problem here, really annoying, this message appears for most if not all packages!  Any info regarding this?

**Comment by aaronatmycujoo** [comment]
I can't tell which package this is coming from, it just appeared after upgrading yarn to v1

**Comment by sergii-tkachenko** [comment]
Seems like [`nyc`](https://github.com/istanbuljs/nyc) package is also affected.

**Comment by hmtri1011** [comment]
Same problem here :( so any solutions for resolving this annoy warning :(

**Comment by BYK** [comment]
We have merged a patch that silences this warning. If you are interested you can try getting the latest nightly: https://yarnpkg.com/en/docs/nightly

**Comment by bajras** [comment]
Any update on this fix? I tried using nightly and still get those warning? Thanks.

**Comment by IAMtheIAM** [comment]
the yarn owner said they're [working on it](https://github.com/yarnpkg/yarn/issues/3751#issuecomment-332166987)
