### ISSUE TITLE
Yarn install fails during docker build because of private package

### ISSUE THREAD

**Issue by thib-rdr** [yarnpkg/yarn#4391]
Hi,

When I run `yarn install` on my machine, everything works. When I try to run it in docker, with a dockerfile image based on Node 8.4, the download and install of one of our private package fails, while it used to work before (I don't exactly know when it started). 

Here is the error that is thrown : 
`error An unexpected error occurred: "https://registry.npmjs.org/@private/private-package/-/private-package-1.1.1.tgz: Request failed \"404 Not Found\"".`

I noticed that if I manually remove the yarn.lock file manually before running docker build, it works. But it is not practical, as we would need to exclude our yarn.lock from version control, and be careful not to recreate one during our local builds.

I tried adding various things to my .npmrc, like this : 

```
registry=https://registry.npmjs.org/
//registry.npmjs.org//:_authToken=XXXXX
@private:registry=https://registry.npmjs.org/
```

But it changed nothing. 

Thanks for your help,

Node JS 8.4 and 6.11.3 (on my machine)
Node 8.4 (in docker)
Yarn 1.0.0
Mac OS X Sierra

**Comment by thib-rdr** [comment]
Allright, just found out why it worked on my machine... because of the cache ! Once I ran `yarn cache clean`, it does not work anymore on my machine or on docker.

**Comment by BYK** [comment]
Can you try with one of the latest nightlies? There were two issues reported very similar to this and they are resolved on latest nightlies. If this is the same then we can just close the ticket and you can switch to 1.0.2 when it is out.

**Comment by lux-capacitor** [comment]
Is there an ETA on the 1.0.2 release?

**Comment by jquense** [comment]
I'm getting the same error using the lastest nightly (`v1.0.1-20170911.1958`)

in CI we do `"//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc` and its suddenly failing with 404's on our scoped packages.

**Comment by thib-rdr** [comment]
The problem is still present with yarn v1.0.1-20170911.1958

It started to fail suddenly for us to, no changes has been made on our end...

**Comment by thib-rdr** [comment]
I just downgraded yarn, it used to work on version `0.27.5`, but not on version `0.27.3`

**Comment by BYK** [comment]
>Is there an ETA on the 1.0.2 release?

We are hoping to release it in a few days.

@thib-rdr we've merged another fix. Would you mind trying it again? Sorry for all the trouble and many thanks for helping us with this!

**Comment by thib-rdr** [comment]
Yep, looks like it works with yarn `v1.0.1-20170912.1314` !

**Comment by jquense** [comment]
I just tried `v1.0.1-20170912.1314` as well, but it did not fix it :(

**Comment by BYK** [comment]
@jquense there's not https://nightly.yarnpkg.com/yarn-1.0.1-20170912.1438.js (1438) with a new patch in it. Can you try that?

**Comment by BYK** [comment]
@thib-rdr closing since it is resolved on master.

@jquense if it still doesn't work with the latest nightly. Can you open a new issue with more details about reproducing it?

**Comment by jquense** [comment]
I can I didn't want to flood the tracker with more of the same

**Comment by BYK** [comment]
@jquense It is a different issue though (although the symptoms are same/similar) :)
