### ISSUE TITLE
"babel-loader@7.1.2" has unmet peer dependency "webpack@2 || 3"

### ISSUE THREAD

**Issue by alansouzati** [yarnpkg/yarn#4589]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

The following structure in peerDependency does not show any warning with `npm install`.

```
  "peerDependencies": {
    "babel-core": "6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc",
    "webpack": "2 || 3"
  },
```

https://github.com/babel/babel-loader/blob/master/package.json#L19

Replacing `"webpack": "2 || 3"` with `"webpack": "^2.0.0 || ^3.0.0"` removes the warning.

FYI the peer webpack version is set to `3.4.1`
**If the current behavior is a bug, please provide the steps to reproduce.**

Run yarn install

**What is the expected behavior?**

No warnings

**Please mention your node.js, yarn and operating system version.**

Node: 6.11.x
Yarn: 1.1.0
OSx 10

**Comment by edmorley** [comment]
Hi!

Using yarn 1.2.1, node 8.6.0, MSYS2 under Windows x64, I cannot reproduce (I get two react releated peer dependency warnings instead, but they seem legit).

@alansouzati, could you confirm this is fixed in latest yarn? :-)

For reference, I used the following STR:
1. `git clone https://github.com/babel/babel-loader`
2. `cd babel-loader`
3. `yarn install`

**Comment by BYK** [comment]
I think we've fixed this with the 1.2.0 line. Thanks a lot @edmorley for checking :)

**Comment by reinseth** [comment]
I can still reproduce this error.

Steps to reproduce:
```
mkdir yarn-test
cd yarn-test
yarn init
yarn add -D babel-loader
```

Gives the following output:
```
yarn add v1.2.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "babel-loader@7.1.2" has unmet peer dependency "webpack@2 || 3".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 17 new dependencies.
├─ babel-loader@7.1.2
├─ big.js@3.2.0
├─ commondir@1.0.1
├─ emojis-list@2.1.0
├─ find-cache-dir@1.0.0
├─ find-up@2.1.0
├─ json5@0.5.1
├─ loader-utils@1.1.0
├─ locate-path@2.0.0
├─ make-dir@1.0.0
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ p-limit@1.1.0
├─ p-locate@2.0.0
├─ path-exists@3.0.0
├─ pify@2.3.0
└─ pkg-dir@2.0.0
Done in 1.15s.
```

Node: v8.6.0
Yarn: 1.2.1
OS: Ubuntu 16.04

**Comment by edmorley** [comment]
@reinseth, the error is correct in that example - those dependencies are missing (that example doesn't install them, unlike the STR in the original post). babel-loader 7.1.2 has a `peerDependencies` that includes babel-core and webpack, but you're not installing them:
https://github.com/babel/babel-loader/blob/v7.1.2/package.json#L17-L20

See the installation instructions here:
https://github.com/babel/babel-loader#install

**Comment by reinseth** [comment]
Ah, thanks, I missed that. But there is still something interesting going on:
If I install `webpack babel-core babel-loader` everything is fine. If I also install `babel-cli`, however, I get the same error:

```
$ cat package.json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "webpack": "^3.8.1"
  }
}

$ yarn add babel-loader
yarn add v1.2.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
├─ babel-loader@7.1.2
├─ commondir@1.0.1
├─ find-cache-dir@1.0.0
├─ make-dir@1.0.0
└─ pkg-dir@2.0.0
Done in 1.64s.
```

**Comment by florianbepunkt** [comment]
Same here. I also get this error as soon as I also install babel-cli.

**Comment by hpg-mheck** [comment]
Me three.  Reprouced this today in a sterile development environment being set up from scratch with @latest everything.  babel-core, babel-loader, babel-cli.  Getting complaints as if babel-core 7.x is a requirement, when it isn't out yet.

**Comment by CodeSigils** [comment]
This solved it for me on linux-ubuntu, node v8.9.0 lts/carbon, npm 5.5.1:
`yarn add  babel-loader@8.0.0-beta.0  @babel/core@next  @babel/preset-env@next  webpack`

**Comment by hpg-mheck** [comment]
Yeah, that shut the yarn complaints up, but left me with a bunch of other problems.

Groan.  Anything with references to "@next" "@latest" and crap like that is going to break in about a week.  In the interests of preserving the sanity of anyone finding this while pulling their hair out, here is a consistent package.json hard version set that seems to work for me at the moment, with yarn, in a Visual Studio 2017 environment, writing Office Add-in stuff, right now, today, 03OCT2017:

`{
  "name": "yadda-whatever",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "babel-loader": "6.4.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-1": "6.24.1",
    "webpack": "2.6.1",
    "webpack-dev-server": "2.4.5"
  },
  "dependencies": {
    "alt": "^0.18.6",
    "babel-core": "6.24.1",
    "jshashes": "^1.0.7",
    "office-ui-fabric-react": "^5.18.0",
    "react": "15.4.2",
    "react-dom": "15.4.2"
  }
}
`

Hopefully that at least helps some people landing on this problem.

**Comment by xstable** [comment]
Have the same issue react-native 0.55.2  :

```
bundle.js:9 Uncaught (in promise) Error: DeltaPatcher should receive a fresh Delta when being initialized
    at e.applyDelta (bundle.js:9)
    at Wn (bundle.js:9)
    at <anonymous>
applyDelta	@	bundle.js:9
Wn	@	bundle.js:9
```

My dependenciesn in _package.json_ are:
```
"dependencies": {
    "eslint-plugin-react-native": "^3.2.1",
    "native-base": "^2.4.1",
    "npm": "^5.8.0",
    "react": "16.3.1",
    "react-devtools": "^3.2.1",
    "react-native": "0.55.2",
    "react-navigation": "^1.5.11",
    "react-redux": "^5.0.7"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
```

**Comment by xstable** [comment]
Found an Solution for my case... see here: 
https://github.com/facebook/react-native/issues/18209#issuecomment-382037709
