### ISSUE TITLE
There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by rainjm** [yarnpkg/yarn#4890]
```

➜  fuc git:(master) yarn install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://npm.byted.org/debug/-/debug-2.6.9.tgz: getaddrinfo ENOTFOUND npm.byted.org npm.byted.org:80".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Jimmy/reactjs/react-native/fuc/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  fuc git:(master) ✗

```

I cloned a project and I looked at the value of yarn.lock, package key 'resolved', which starts with 'http://npm.byted.org'.

I think this is the author custom **yarn registry**, but I can not visit 'http://npm.byted.org', **but yarn config did not fix it**.

**Comment by torifat** [comment]
What do you mean by "but yarn config did not fix it"? What did you try?

**Comment by rainjm** [comment]
expected:
If 'yarn.lock resolved' is unreachable, can I ignore 'resolved' in yarn.lock and install it using 'yarn config registry'.
doubt:
Or recommend me delete the lock file?

Sorry, forgive me, my English is not good.

**Comment by torifat** [comment]
> Sorry, forgive me, my English is not good.

It's not a problem as long as I can understand. And, I'm also not very good either 😄

It's not a bug. This is an expected behavior. You can either delete `yarn.lock` file and `yarn install` again. Or, if you need the exact packages then you can replace `http://npm.byted.org` with `https://registry.yarnpkg.com` in `yarn.lock` file.

**Comment by ufoqhmdt** [comment]
✘ didi@MacBook-Pro  ~/workspaces/temp/afe-auto-user-web   master  npm i

> fsevents@1.1.2 install /Users/didi/workspaces/temp/afe-auto-user-web/node_modules/fsevents
> node install

[fsevents] Success: "/Users/didi/workspaces/temp/afe-auto-user-web/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> pre-commit@1.2.2 install /Users/didi/workspaces/temp/afe-auto-user-web/node_modules/pre-commit
> node install.js


> spawn-sync@1.0.15 postinstall /Users/didi/workspaces/temp/afe-auto-user-web/node_modules/spawn-sync
> node postinstall


> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/didi/workspaces/temp/afe-auto-user-web/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN stylelint-config-standard@18.0.0 requires a peer of stylelint@^8.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.0.0 requires a peer of stylelint@^8.3.0 but none is installed. You must install peer dependencies yourself.

added 1629 packages in 79.925s
 didi@MacBook-Pro  ~/workspaces/temp/afe-auto-user-web   master  yarn
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
⠐ js-tokens@^3.0.0




config 

 ✘ didi@MacBook-Pro  ~/workspaces/temp/afe-auto-user-web   master  yarn config list
yarn config v1.3.2
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'http://npm.intra.xxx.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.3.2 npm/? node/v8.9.1 darwin x64',
  lastUpdateCheck: 1511927711629,
  proxy: 'http://npm.intra.xxx.com' }
info npm config
{ registry: 'http://npm.intra.xxx.com', }
✨  Done in 0.04s.



why  npm can be working. but yarn can't working

**Comment by marcelhageman** [comment]
Adding this comment for other Googlers: What worked for me was increasing the Yarn network timeout:

`yarn add YourPackageHere --network-timeout 100000`

Apparently the package I was installing was too large (or my network too slow) so it assumed it was a network problem. It might've been, but this solved it. Just took a while.

**Comment by AnthonyLamot** [comment]
I'm experiencing this issue now as well. None of the aforementioned solutions seem to be working. Internet still works fine though, and no one else in the co-working space where I'm at seem to be experiencing any network issues?

**Comment by sandinosaso** [comment]
`yarn install --network-timeout 1000000
`
Did the trick for me:

```
⇒  yarn install --network-timeout 1000000
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
warning react-native > fbjs-scripts > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "jest-expo > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 234.36s.
```

**Comment by AnthonyLamot** [comment]
Figured out was wrong. One of my dependencies (react-native itself) had the
wrong value and it got stuck there. Took me a while to realize because it
did not show in the error report but only while the yarn command was
running would it pop up for a moment.

**Comment by JochenFromm** [comment]
Same problem here, increasing the network timeout solved it 
```
yarn install --network-timeout 1000000
```
Maybe the default timeout is too small?

**Comment by HarshulSharma000** [comment]
I am facing the same issue on Windows and setting timeout does not resolve it. On the other hand npm works fine.

**Comment by anujthakwani** [comment]
> Task :wherehows-web:yarn
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-polyfill/-/babel-polyfill-6.26.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/athakwani/Desktop/WhereHows/wherehows-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


FAILURE: Build failed with an exception.

Any help here ?

**Comment by jensbodal** [comment]
Don't have a solution or why there was network issues in the first place, but the default for `NETWORK_TIMEOUT` is 30 seconds.  Note that `network-timeout` is in ms, I probably wouldn't set this to higher than 5 minutes otherwise your build will just sit there for ~16 minutes (1000000ms) is there truly is network connectivity issues.

https://github.com/yarnpkg/yarn/search?utf8=%E2%9C%93&q=NETWORK_TIMEOUT&type=

**Comment by marcelorl** [comment]
@HarshulSharma000 same issue

**Comment by HarshulSharma000** [comment]
@marcelori I tried to revert to nodejs 8.9.4(lts) and then tried with --network-timeout=99999 and it works. 
Note:- I am using yarn 1.4.0

**Comment by suhailgupta03** [comment]
Looks like yarn was trying to connect via a proxy. The following worked for me:

```
npm config rm proxy
npm config rm https-proxy
```

**Comment by raelmiu** [comment]
I'm still having this issue. Increasing network timeout did not help, nor did @suhailgupta03 's proxy removal. Right now, yarn won't install, add, or do anything. I've tried it through three different networks.

**Comment by benseitz** [comment]
same here......

**Comment by abishekrsrikaanth** [comment]
same here

**Comment by MichelDiz** [comment]
"is there truly is network connectivity issues." I don't think so. I have 100Mb of internet. No services are with trouble. Downloads are perfect, VOIP is perfect, NPM shines. Only Yarn I have this... Something dark is happening.

**Comment by adjavaherian** [comment]
Might be by design.  There's a registry in `~/.yarnrc` that's autogenerated.  Perhaps its behind a VPN or something?  
```
cat ~/.yarnrc 
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


registry "https://artifactory.some.net/api/npm"
lastUpdateCheck 1233305747

**Comment by MichelDiz** [comment]
mine (Looks like the registry address is empty - was not it supposed to contain something?):
```bash
=> cat ~/.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1523327705543
```

**Comment by raelmiu** [comment]
@adjavaherian This works! Mine was stuck to a VPN URL at my company. NO idea why it was set to that though. Because I don't use the VPN for yarn at all.

**Comment by learntoswim** [comment]
The "voodoo" trick posted above by @MichelDiz worked for me as well.

**Comment by QAQXiYangYang** [comment]
So,How to solve this problem?
same here......

**Comment by rdricco** [comment]
Same here. It's working on bash/wsl but not on windows shell.

**Comment by Ryuurock** [comment]
+1

**Comment by techani21** [comment]
I am still having the problem with yarn in visual studio code
![image](https://user-images.githubusercontent.com/26795232/41868377-38f972b0-78b6-11e8-81e5-031b60bc9570.png)

**Comment by cp1001** [comment]
this kind of error occurs when your net cannot access some package resource which yarn.lock file specified.
check your yarn.lock file or delete yarn.lock,then change npm registry to other public regitstry,then `yarn install`.

point are:
donot use private  registry.
check your network's connection to registry.

**Comment by herarya** [comment]
@sandinosaso thanks bro, working 👍

**Comment by FDiskas** [comment]
```
Yarn version: 
  1.9.4

Node version: 
  9.11.2

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/grid-styled/-/grid-styled-4.1.0.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:138095:19)
```
:iphone:

**Comment by ppozeti** [comment]
thought it was a problem with my private proxy npm, but I'm glad I'm not alone! Same problem is happening. If I copy the registry url and paste on chrome, it downloads the file.

**Comment by spitchaiah** [comment]
This worked for me:

$ yarn config delete proxy
$ yarn install --network-timeout 1000000

**Comment by Vadorequest** [comment]
Having those troubles now but https://registry.yarnpkg.com is not responding either, may be a general outage?

**Comment by FDiskas** [comment]
Why this clone of all modules is used? Why not directly from npm?
Collecting more info when and why downloading?

**Comment by somewhatabstract** [comment]
For me, this was because I had added two factor auth to my npmjs.org account.

I ran:

`npm logout`
`npm login`

Then filled out the details, including the MFA OTP request. Then everything worked again.

**Comment by bsedefian** [comment]
Vadorequest, same issue. I get back some JSON when I use my cellular network. 404 when I use my wifi network.

**Comment by jreybaylen** [comment]
@Vadorequest did you solve your problem? I encountered it too.

**Comment by Vadorequest** [comment]
Not really, can't explain it. I just switched to a mobile network and it worked. Now I'm back on my wifi and it works too. Maybe restart your network or switching to another may fix it.

**Comment by simon-robertson** [comment]
I started to encounter the same issue today. Deleting the proxy resolved the issue for me.

`yarn config delete proxy`

**Comment by bsedefian** [comment]
It works this afternoon without me having to delete proxies or adjust anything.

**Comment by melkishengue** [comment]
yarn install --network-timeout 1000000 did the trick for me.

**Comment by prasadram** [comment]
@melkishengue  it didn't worked for me
sudo yarn --network-timeout 100000 global add gulp-cli
still the same error

**Comment by melkishengue** [comment]
@prasadram  What about **yarn  global add gulp-cli --network-timeout 100000** ?

**Comment by prasadram** [comment]
@melkishengue  thanks for reply, still it didn't worked

```
[Java is awesome]:~$ sudo yarn global add gulp-cli --network-timeout 100000
[sudo] password for prasad: 
yarn global v1.10.1
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-cli: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

```

**Comment by prasadram** [comment]
@melkishengue  thanks for reply, still it didn't worked

[Java is awesome]:~$ sudo yarn global add gulp-cli --network-timeout 100000
[sudo] password for prasad: 
yarn global v1.10.1
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-cli: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by yzhe8769** [comment]
I have encountered the same issue on my Mac. But this seems to be related to the DNS setting in the machine. What I have done is to manually set my DNS server to 8.8.8.8 (Google DNS) and 208.67.222.222 (Open DNS) and now it is resolved. I can run 'yarn install' again.

**Comment by FDiskas** [comment]
I had no problems on mac and linux only on windows there was such error. It could be related to platform also.

**Comment by prasadram** [comment]
@yzhe8769 do you know how to change DNS settings in ubuntu ? i want to try that options as well, because i have tried almost all options

**Comment by prasadram** [comment]
After investigating resolved the issue. Please check below are my analysis
when i hit below i got unknow host
```

curl registry.yarnpkg.com
curl: (6) Couldn't resolve host 'registry.yarnpkg.com'
```
i am using Desktop with LAN and OS is ubuntu 16.04 but the same command is working fine in mac
then realized it's not with yarn so i have added google dsn in resolv.conf in etc folder then started working fine.
 hope it will help someone

**Comment by yzhe8769** [comment]
> After investigating resolved the issue. Please check below are my analysis
> when i hit below i got unknow host
> 
> ```
> 
> curl registry.yarnpkg.com
> curl: (6) Couldn't resolve host 'registry.yarnpkg.com'
> ```
> i am using Desktop with LAN and OS is ubuntu 16.04 but the same command is working fine in mac
> then realized it's not with yarn so i have added google dsn in resolv.conf in etc folder then started working fine.
> hope it will help someone

All good. So if anyone also encounters this issue, that is probably because the DNS setting is preventing the resolution of the yarn registry

**Comment by SkxNMDI5** [comment]
Specifying another folder for cache resolved the issue in my environment :
export YARN_CACHE_FOLDER=/tmp/.cache

**Comment by bezbahadori** [comment]
I have tried everything you guys suggested , and still get the error
 
```

> yarn install --network-timeout 1000000
> yarn install v1.7.0
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> error An unexpected error occurred: "https://registry.yarnpkg.com/aws-sdk/-/aws-sdk-2.328.0.tgz: read ECONNRESET".
> info If you think this is a bug, please open a bug report with the information provided in "C:\\Git\\broadvoice.communicator\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying..

```

**Comment by whereisaaron** [comment]
- 1Gbps Internet (tests at 900Mbit sustained, zero drops)
- Ubuntu 18.04
- yarn 1.10.1
- nodejs v8.10.0

I get these spurious network errors too.

````
$ yarn install
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.3.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "[..]/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

Repeating with a `--network-timeout` didn't help.

```
$ yarn install --network-timeout=10000
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
...
```

**Comment by kirillgroshkov** [comment]
is `network-timeout` documented anywhere? Google doesn't give me anything..

**Comment by whereisaaron** [comment]
@torifat could you consider reopening this issue. The problem here is all the 'info There appears to be trouble with your network connection. Retrying...' messages. These occur whether or not you have a lock file. If I delete my `yarn.lock` file I still get these messages. If I delete the yarn cache and lock file. I get even more.

This error message issue appears to have resurfaced by PR #6413 which recently added this message as part of a retry mechanism because or remote npm registry problems, and is usually nothing to do you 'your' end. It seems to be a congenital problem with the registry causes retries, and that being surfaced by these messages.
https://github.com/yarnpkg/yarn/pull/6413/files#diff-5d246f90b159bd84bbc99f67527b1a0eR401

It seems like the problem is actually that this message is misleading.

1Gbps Internet
Ubuntu 18.04
yarn 1.10.1
nodejs v8.10.0

No lock file:
```
$ yarn install --network-timeout=30000
yarn install v1.10.1
info No lockfile found.
[1/4] Resolving packages...
warning @vue/cli-service > webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
...
```

No cache or lock file:
```
yarn install --network-timeout=30000
yarn install v1.10.1
info No lockfile found.
[1/4] Resolving packages...
warning @vue/cli-service > webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.4.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "[..]/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
```

**Comment by whereisaaron** [comment]
@arcanis tells me that yarn 1.11+ will  have a more accurate message when the retry is caused by the npm registry, as #6413 also includes a new, more accurate message that is not in yarn 1.10.x.

`internalServerErrorRetrying: 'There appears to be trouble with the npm registry (returned $1). Retrying...'`

**Comment by torifat** [comment]
@whereisaaron Can you please create a new issue? I think it's better to create a new one instead of resurrecting an old issue with lots of comments.

**Comment by whereisaaron** [comment]
Sure @torifat; I didn't want to keep making duplicate issues. Right now though, this one might be resolved when 1.11 releases, so let's leave it closed, and if 1.11 still has any problem I'll open a new issue for that version specifically.

**Comment by TedSean** [comment]
Even i m facing the issue.

**Comment by keicoon** [comment]
Even i m facing the issue(2) in 1.12 release.

**Comment by abdennour** [comment]
It happens with me when running `docker build` where the base image was upgraded from `FROM node:10-alpine` to `node:11.1.0-alpine`.

Since I want to keep node 11 as the base image, I had to migrate my commands from `yarn` to `npm`.

**Comment by PutziSan** [comment]
I can confirm this happens under windows 10 with yarn `1.12.3` and node `11.1.0`.

When I changed node-version back to `8.12.0` everything works without problems (or "trouble"). (I changed the versions via [nvm-windows](https://github.com/coreybutler/nvm-windows))

**Comment by rexkenley** [comment]
Double confirm PutziSan

**Comment by worldkk1** [comment]
I got the same error.
try `npm config set registry=https://registry.npmjs.com/`
it's work for me.

**Comment by vipulkumarsviit** [comment]
> Looks like yarn was trying to connect via a proxy. The following worked for me:
> 
> ```
> npm config rm proxy
> npm config rm https-proxy
> ```

it worked for me yeee

**Comment by tonyatoms** [comment]
Was getting the same error. 
None of the solutions posted here helped. Rebooting my computer "fixed" it.

**Comment by stewartml** [comment]
I was getting this error too.  Rerunning the install with `--verbose` told me that it was `"https://registry.yarnpkg.com/@expo/traveling-fastlane-darwin/-/traveling-fastlane-darwin-1.7.1.tgz` the was causing the issue.

I tried visiting it in Chrome - sure enough, it downloaded - but then hung for a while at 100%.  This usually happens when it's getting scanned.

Lo and behold, disable Windows Defender real-time scanning and it works fine.  It seems that if the virus scanning takes too long, Yarn chalks it up as a network problem.

TLDR: if you're on windows, try disabling real-time scanning and reinstall.

**Comment by Ice-Hazymoon** [comment]
I also encountered this error, using `sudo yarn` after normal

**Comment by RitikaSrivastava11oct** [comment]
E:\javascript\React\confusion>yarn add moment
yarn add v1.13.0
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://registry.npmjs.org/moment: getaddrinfo ENOTFOUND domain domain:8080".
info If you think this is a bug, please open a bug report with the information provided in "E:\\javascript\\React\\confusion\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

please help.
facing the same issue.

**Comment by risda22** [comment]
if you have issue

> info There appears to be trouble with your network connection. Retrying...

i think you must configuring proxy
Use these commands ;

yarn config set proxy http://username:password@host:port
yarn config set https-proxy http://username:password@host:port

**Comment by the94air** [comment]
Changing registry seems to fix the issue for me:
```
yarn install --registry https://registry.npmjs.org
```

**Comment by RehabHussein** [comment]
I had the same problem in Windows and increasing the network timeout fixed it for me ! Thank you

**Comment by jklemm** [comment]
Same error. To solve, just erase the `yarn.lock` and run `yarn` command to recreate.

**Comment by RitikaSrivastava11oct** [comment]
> if you have issue
> 
> > info There appears to be trouble with your network connection. Retrying...
> 
> i think you must configuring proxy
> Use these commands ;
> 
> yarn config set proxy http://username:password@host:port
> yarn config set https-proxy http://username:password@host:port

solved the problem,thank you :-)

**Comment by gknapp** [comment]
I ran into this issue yesterday, I cannot retrieve `@material-ui/icons` with yarn. I've tried the suggestions on this thread (network timeout, changing registry, remove `node_modules` and install again). However, installing with npm completes successfully.

If I visit the package URL directly, I can download it in my browser (and is only 1.2MB). Not sure what's blocking yarn.

**Comment by darkliquid** [comment]
Having this exact same issue with `@material-ui/icons` too. Nothing on either windows native yarn, or yarn running under wsl with or without network timeouts extended or integrity checks disabled seems to make any difference. Likewise I can simply download the files in the browser fine. Npm installs fine.

**Comment by todorstoev** [comment]
Removing `@material-ui/icons ` from packages also resolve issue for me.

**Comment by mustaphaturhan** [comment]
I got exact same `@material-ui/icons` issue today. I deleted everything related with yarn in my project to solve this issue by doing `rm -rf node_modules yarn.lock` in bash. I ran `yarn` command after delete process is done. And issue was solved, I didn't see any errors after that.

**Comment by SpearThruster** [comment]
yea @mustaphaturhan i had exactly the same issue today with @material-ui/icons as well... solved it the same way. :\

**Comment by m-oscartong** [comment]
removing `~/.yarnrc` works for me

**Comment by PutziSan** [comment]
I think it just happens when the packages are very large or contain a lot of files (I also often see this message for the icon-packages of fontawesome). 
Maybe a time limit is not the best way to check this. You could also do a 1kb-test-ping if the time limit is exceeded. Only if it fails you can actually do a retry, otherwise everything is okay, it just takes a bit longer.

**Comment by gknapp** [comment]
I still can't install install `@material-ui/icons`. I've remove `node_modules`, `yarn.lock` and run `yarn cache clean`, upgraded node to `10.16.0` and re-installed `yarn`. I'm on Windows 10.

One oddity, I could install all packages successfully if I cloned my project fresh into a temp directory. The problem manifests in my workspace. I've looked for hidden files, couldn't see any. Still seeing:

```
Error: https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.2.1.tgz: ESOCKETTIMEDOUT`
  at ClientRequest.<anonymous> (C:\Users\<user>\AppData\Roaming\nvm\v10.16.0\node_modules\yarn\lib\cli.js:130217:19)
```
Switching my project over `npm`.

**Comment by ezfe** [comment]
I've just had the same issue because somehow `npm` configured my proxy to ready `apple.asd` (unsure how, I did not do this). I did `yarn config list` and identified the setting that way. After removing, it worked.

**Comment by adabru** [comment]
If you have ip6-only network and the error occurs, you can try to workaround with adding

```
2606:4700::6810:1723 registry.yarnpkg.com
2606:4700::6810:1723 registry.npmjs.org
2606:4700::6810:ab63 yarnpkg.com
```

to /etc/hosts. You can get the ip6 with `nslookup registry.yarnpkg.com`. <https://github.com/yarnpkg/yarn/issues/6031>

**Comment by juliehive** [comment]
I had a very similar issue that was resolved by uninstalling and reinstalling node/npm

**Comment by ryu9827** [comment]
For me, I just remove both npm and yarn lockfile and run `yarn install` again

**Comment by zeevl** [comment]
Also had problems with `@material-ui/icons` on windows 10.  Disabling real time protection from windows defender as @stewartml suggested did the trick.

**Comment by Adamkaram** [comment]
you can do 
npm config rm proxy
npm config rm https-proxy
for remove any proxy 
or if u want to use proxy u can do this 
$ yarn config set proxy http://my_company_proxy_url:port
$ yarn config set https-proxy http://localhost:3128


or to make timeout 600000 maybe z file is big 
yarn config set network-timeout 600000 -g

or do this if you want to keep the default timeout  as it being 
yarn add <yourPackage> --network-timeout 100000

**Comment by xdkaka** [comment]
`rm -rf /Users/xxx/.config/yarn/global/yarn.lock`
then done

**Comment by ibragimOnlinesup** [comment]
solved by reboot :D

**Comment by sapeyes** [comment]
In my case, it was working by turning off AdGuard and Windows Defender on Windows 10. I also use this command.

yarn install --network-timeout 1000000

**Comment by huangguorui** [comment]
> 我仍然有这个问题。增加网络超时无济于事，@ suhailgupta03的代理删除也无济于事。现在，yarn不会安装，添加或做任何事情。我已经通过三个不同的网络进行了尝试。

Adding time didn't solve my problem. It still existed and I didn't solve it

**Comment by jimmyyem** [comment]
npm config rm proxy 
npm config rm https-proxy

I hope the above commands will help.

**Comment by huangguorui** [comment]
![image](https://user-images.githubusercontent.com/29142466/77740660-97842000-704e-11ea-9acc-7f67c9089267.png)
There are still problems.

**Comment by huangguorui** [comment]
![image](https://user-images.githubusercontent.com/29142466/77740768-c69a9180-704e-11ea-8d7b-cde1f4eef7a5.png)
Network speed not acquired correctly.

**Comment by allthesignals** [comment]
Why is this closed? This continues to be an issue. Why? It has plagued my machine for weeks now, across many projects.

**Comment by ezfe** [comment]
@allthesignals Most of the issues reported here are various configuration issues. I myself had a misc. configuration issue, for example. Things like incorrectly set proxies are a big one. There's no way to easily resolve this since it's a catch-call for weird internet problems.

**Comment by allthesignals** [comment]
Okay, thank you @ezfe. I do think the info message is inaccurate for some people's situations. 

For example:

> I think it just happens when the packages are very large or contain a lot of files (I also often see this message for the icon-packages of fontawesome).
> Maybe a time limit is not the best way to check this. You could also do a 1kb-test-ping if the time limit is exceeded. Only if it fails you can actually do a retry, otherwise everything is okay, it just takes a bit longer.

**Comment by elhamzaouiaymen** [comment]
I had hhe same issue. Actually I was running the command while a streaming video process is running (netflix). So I just paused it then I ve retried again and it works without even setting timeout to infinite value.

**Comment by rbiggers** [comment]
I had the same issue, but I didn't notice it until I deleted the node_modules directory in my local repo. 
Then I started seeing the network error. Evidently there was an old package in my package.json that was referencing a package that was behind the company firewall (I was also not on the VPN). Once I deleted the offending package from my package.json everything worked correctly.

**Comment by jetonk** [comment]
I had the same issue, my solution was updating the node version and the issue disappeared.

**Comment by allthesignals** [comment]
This again.

```
verbose 0.942 Performing "GET" request to "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.4.tgz".
verbose 1.047 Performing "GET" request to "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz".
[##########################################################################################] 950/
```

It just hangs at these last two requests.

**Comment by TedSean** [comment]
I am having this issue too on yarn  version --> 1.15.2

**Comment by the-turk** [comment]
You shouldn't close issues unless you solve them.

**Comment by shanurrahman-gcsns** [comment]
Do you guys also have a private repository ?

**Comment by rotelando** [comment]
I ran yarn while building my docker image and had the same issue as mentioned. Restarting the docker daemon solved it for me.

**Comment by mirague** [comment]
@xdkaka Thanks, that worked for me! Seems that `yarn.lock` had some old private repository urls set.

**Comment by TheCoderSingh** [comment]
--network-timeout 1000000 fixed it for me but took a long time to install just one package - @material-ui/icons

**Comment by Liqiankun** [comment]
In my case, I deleted yarn.lock file. Then it works well.

**Comment by kirill-konshin** [comment]
```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/npm/-/npm-6.14.8.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/runner/work/timelapser/timelapser/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Github Actions, MacOS runner.

**Comment by LucasJesusone** [comment]
> `yarn install --network-timeout 1000000 `
> Did the trick for me:
> 
> ```
> ⇒  yarn install --network-timeout 1000000
> yarn install v1.3.2
> [1/4] 🔍  Resolving packages...
> warning react-native > connect@2.30.2: connect 2.x series is deprecated
> warning react-native > fbjs-scripts > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> warning "jest-expo > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
> [4/4] 📃  Building fresh packages...
> success Saved lockfile.
> ✨  Done in 234.36s.
> ```

IT WORKD FOR ME! THANK YOU VERY MUCH DUDE

**Comment by phyolim** [comment]
I guess there isn't "one size fit all" solution for this error. In my case there was a cyberark process on my i5 computer hogging all the resources. I force ended that process and the error went away. I think it has to do with antivirus. I'm sure it will come when i restart the pc. Such a waste of time working on windows.

**Comment by hckhanh** [comment]
I get the same problem when I try to install yarn inside docker

```
Step 6/10 : COPY package.json yarn.lock ./
 ---> 72e0f798190d
Step 7/10 : RUN yarn --frozen-lockfile --check-files
 ---> Running in de083b1b3bac
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/escape-regexp/-/escape-regexp-0.0.1.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --frozen-lockfile --check-files' returned a non-zero code: 1
Error: Process completed with exit code 1.
```

**Comment by Carreylife** [comment]
`rm -rf /Users/xxx/.config/yarn/global/yarn.lock` try it, works for me

**Comment by MeralTd** [comment]
`npx audit fix
`
Works for me.

**Comment by fast-and-curious-1910** [comment]
For me
``yarn add <yourPackage> --network-timeout 36000`` worked in almost all cases, but while installing @material-ui/icons, I get this message and it errors out. Tried adding it manually to package.json then deleting node_modules andj yarn.lock did not work either.

**Comment by merceyz** [comment]
The timeout logic is less aggressive in v2 so it will probably work for you there https://yarnpkg.com/getting-started/migration

**Comment by fast-and-curious-1910** [comment]
> --network-timeout 1000000 fixed it for me but took a long time to install just one package - @material-ui/icons

Same.

**Comment by Nguyenkhanh98** [comment]
> I am facing the same issue on Windows and setting timeout does not resolve it. On the other hand npm works fine.

The same as me
