### ISSUE TITLE
Yarn install quits silently if fetching one package times out

### ISSUE THREAD

**Issue by geropl** [yarnpkg/yarn#5491]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn install` quits silently if fetching one of the packages times out during fetch phase due to package size and/or network lag.
Result:
- yarn does quit before reaching linking phase, therefore no packages are installed
- No error message
- Return code 0

(Shortened) example output:
```
$ yarn install --verbose
yarn install v1.5.1
[...]
[1/4] Resolving packages...
warning: [...]
[2/4] Fetching packages...
verbose 1.45 Performing "GET" request to "https://registry.yarnpkg.com/envfile/-/envfile-2.3.0.tgz".
[...]
verbose 20.696 Performing "GET" request to "https://registry.yarnpkg.com/command-exists/-/command-exists-1.2.2.tgz".
$ 
```
**If the current behavior is a bug, please provide the steps to reproduce.**
1. `git clone https://github.com/theia-ide/theia-apps`
2. `cd theia-apps/theia-java-docker`
3. `mv next.package.json package.json`
4. `yarn install`

(Retry until it fails, maybe use slow internet connection)
The large package here is `@theia/java`, which clocks in at around 33MB.

**What is the expected behavior?**
`yarn install` prints an error message with the timeout, the package name and url it failed to fetch. Finally, it quits with a return code `!= 0`.

**Please mention your node.js, yarn and operating system version.**
- node `8.10`
- yarn `1.5.1`
- OS: docker image `node:8.10`
- (Host: Ubuntu `16.04`)

**Update:**
Maybe related: #5055 

**Update 2:**
Neither increasing `--network-timeout` nor setting `--mutex network` helped. Interestingly, the `yarn install` quits long before the network timeout is due (e.g., timeout 60000ms, `yarn install` quits after 35s).

**Update 3:**
I noticed that in the cases where it fails locally (via `docker run ...`), my system monitor shows a very slow download (~150Kb/s on a 50 Mb/s connection). The other runs go with ~5 Mb/s).

**Comment by rally25rs** [comment]
I attempted to reproduce this by setting the `timeout` passed to the `request` lib to `1` but it does throw an error in that case:

```
~/Projects/yarn-test 🐒   yarndev add @theia/java
yarn add v1.6.0-0
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@theia%2fjava: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jvalore/Projects/yarn-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Not sure how else to try to repro this 🤔 maybe I can simulate a slow network somehow...

**Comment by rally25rs** [comment]
Next attempt, used Apple's "Network Link Conditioner" to simulate DSL speed. This took >2min to download that package, but still finished

```
~/Projects/yarn-test 🐒   yarndev add @theia/java
yarn add v1.6.0-0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @theia/java@0.3.7
info All dependencies
└─ @theia/java@0.3.7
✨  Done in 147.88s.
```

then I tried turning off my network half way through the download. That also caught the error:

```
~/Projects/yarn-test 🐒   yarndev add @theia/java
yarn add v1.6.0-0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@theia/java/-/java-0.3.7.tgz: connect ENETUNREACH 104.16.59.173:443 - Local (0.0.0.0:49668)".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jvalore/Projects/yarn-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

There must be some really weird edge case here...

**Comment by geropl** [comment]
That's really strange. Maybe it's related to running in docker? The build is executed on a Jenkins server, but I can run the build in docker on my laptop and reproduce it in ~20% of the runs.

**Comment by cjbturin** [comment]
This may be a scenario to reproduce similar problem on Windows env: 
https://github.com/yarnpkg/yarn/issues/5512

**Comment by geropl** [comment]
> **Update 3:**
I noticed that in the cases where it fails locally (via `docker run ...`), my system monitor shows a very slow download (~150Kb/s on a 50 Mb/s connection). The other runs go with ~5 Mb/s).

We don't use a yarn cache in our environment. Could it be that npmjs throttles/terminates repeated downloads from the same IP?

**Comment by ispringer** [comment]
Several of my teammates experienced this issue on OS X 10.13.3 with Node 5.12.0 and Yarn 1.5.1. Some comments in #764, an issue with some similarity to this one, said upgrading to Node >= 6.9.5 fixes that issue. So my teammates tried upgrading Node to the latest (9.8.0), and that did the trick! My suspicion is that the DNS caching that was recently adding to Yarn (#4447) may not work correctly with Node < 6.9.5, but it's only a hunch.

**Comment by damianb** [comment]
Maybe related to #5473?

**Comment by lili21** [comment]
same issue here, run it from a docker container.

**Comment by naderman** [comment]
Same issue here, also running from a docker container, would be happy to assist you in debugging this if you let me know how I can help?

**Comment by kondei** [comment]
I have the same issue when running it on a drone.io on a docker container.

**Comment by kondei** [comment]
In my case, docker container did not know our private npm registry ip address...
it resolved.
sorry

**Comment by b1rdex** [comment]
For me problem was in wrong definition of dependency:
```
"devDependencies": {
    "gulp": "git+https://github.com/gulpjs/gulp.git"
}
```
This is acceptable for npm btw.

**Comment by rojasmi1** [comment]
I'm experiencing the same issue using `yarn 1.13.0`, node `11.9.0`, the issue seems to be caused by problems downloading a private package due to slow download speed using a VPN.

The installation was silently failing for me as well, only way I could figure the issue out was by setting `--network-concurrency` to `1`. It'd nice to catch these kind of issues out of the box without any workaround though.

**Comment by 2ZZ** [comment]
I have the same problem with yarn v1.12.3
If packages fail to install the exit code is 0 with no error output

**Comment by gaplo917** [comment]
Same problem in v1.13.0

```
Step 8/11 : RUN yarn install --frozen-lockfile
 ---> Running in 9174a622f137
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
Removing intermediate container 9174a622f137
 ---> b151f7407bd8
Step 9/11 : COPY . /app
 ---> c014809a3bce
```

The CI pipeline does not fail... the `node_modules` folder don't exist in the docker container. The docker image is corrupted 

the workaround to make the CI pipeline fail is to check whether `node_modules` is exist

```
Step 8/11 : RUN yarn install --frozen-lockfile && ls node_modules
```

**Comment by swayok** [comment]
For me the culprit was an antivirus (Dr.Web) that monitors http/https request and blocks "dangerous" domains silently.... In my case it was `https://raw.githubusercontent.com`. Adding it to whitelist of antivirus solved the issue.
Use `--verbose` to see which url is blocked and then try to open it in browser. If you see something like ERR_SSL_PROTOCOL_ERROR - then the culprit is your firewall or antivirus.

**Comment by philaw** [comment]
Had this when running docker using yarn v1.1.3.0, after upgrading to v1.17.3 (nodejs 12.7.0), it behaves normal now.

**Comment by puncha** [comment]
@philaw we also use yarn 1.13.0 and encountered this bug. I'll try to upgrade to 1.17.3.

**Comment by jamie-pate** [comment]
I thought I had a similar problem with yarn 1.22.4 and nodejs 12.13.1 while attempting an offline build.
It turned out to be an install script trying to download from the internet. (cypress) and `--silent` would hide the error message.

**Comment by merceyz** [comment]
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration

**Comment by SteffiStuffel** [comment]
Still happens for me using yarn2 and docker image cimg/node:16.13.0. Only failing in ci, working fine locally.

**Comment by BernalCarlos** [comment]
> Still happens for me using yarn2 and docker image cimg/node:16.13.0. Only failing in ci, working fine locally.

@ztefanie Where you able to solve this? This is failing for me on CI as well (CircleCI)

**Comment by iwpnd** [comment]
@BernalCarlos how about you? did you happen to solve this eventually? Same problem here for me in CircleCI. I have a monorepo and each of its packages is build, tested and deployed in a separate workflow. The build would fail on random occasion for me, on others it passes correctly. It usually happend on the fetch step of `yarn install`:

> Fetch: Then we download all the dependencies if needed, and make sure that they're all stored within our cache (check the value of [cacheFolder](https://yarnpkg.com/configuration/yarnrc#cacheFolder) in yarn config to see where the cache files are stored).

So my suspicion is that the cache im restoring from any of the other packages workflows is corrupt which causes the fetch step to fail. I'm having a hard time replicating this however. :/

**Comment by BernalCarlos** [comment]
> @BernalCarlos how about you? did you happen to solve this eventually? Same problem here for me in CircleCI. I have a monorepo and each of its packages is build, tested and deployed in a separate workflow. The build would fail on random occasion for me, on others it passes correctly. It usually happend on the fetch step of `yarn install`:
> 
> > Fetch: Then we download all the dependencies if needed, and make sure that they're all stored within our cache (check the value of [cacheFolder](https://yarnpkg.com/configuration/yarnrc#cacheFolder) in yarn config to see where the cache files are stored).
> 
> So my suspicion is that the cache im restoring from any of the other packages workflows is corrupt which causes the fetch step to fail. I'm having a hard time replicating this however. :/

Yes, I was able to solve it. In my case, the problem was not enough memory.

I  noticed a 100% memory usage, and increasing the job instance size solved the issue.

Seems like Yarn just quits, whiteout any error is when there's no enough memory. At least on CircleCI.

**Comment by iwpnd** [comment]
Ohhh, good pointer. Much appreciated.

**Comment by fantarics** [comment]
> > @BernalCarlos how about you? did you happen to solve this eventually? Same problem here for me in CircleCI. I have a monorepo and each of its packages is build, tested and deployed in a separate workflow. The build would fail on random occasion for me, on others it passes correctly. It usually happend on the fetch step of `yarn install`:
> > > Fetch: Then we download all the dependencies if needed, and make sure that they're all stored within our cache (check the value of [cacheFolder](https://yarnpkg.com/configuration/yarnrc#cacheFolder) in yarn config to see where the cache files are stored).
> > 
> > 
> > So my suspicion is that the cache im restoring from any of the other packages workflows is corrupt which causes the fetch step to fail. I'm having a hard time replicating this however. :/
> 
> Yes, I was able to solve it. In my case, the problem was not enough memory.
> 
> I noticed a 100% memory usage, and increasing the job instance size solved the issue.
> 
> Seems like Yarn just quits, without any errors, when there's not enough memory. At least on CircleCI.

Can confirm! Just ran into the issue myself and htop does show almost 100% usage of the memory before `yarn install` silently quits.

**Comment by KRBTy** [comment]
> Yarn just quits, without any errors, when there's not enough memory

Very annoying behavior in deed, and it still happens in the latest yarn version (4.1.1).

Your comment saved my day (and what's left of hair on my head).
Thank you
