### ISSUE TITLE
yarn 1.9.2 takes a long time on linking dependencies

### ISSUE THREAD

**Issue by kenips** [yarnpkg/yarn#6177]
Hello yarn team,

Just upgraded to 1.9.2 and running `yarn add next-images` in my app it took a long time at "Linking dependencies...". Reverting back to 1.7.0 is fine.

yarn 1.9.2: Done in 375.98s
yarn 1.7.0: Done in 36.15s

Attached my [package.json](https://gist.githubusercontent.com/kenips/087237e5cf2d9f783399d7387bae15f1/raw/7139c47a224a3778561d5ee205fb9452d8bb407a/package.json) here for reference.

Steps to reproduce:
1. `mkdir -p test`
2. Copy in package.json
3. Run `yarn`
4. Run `yarn add next-images`

**Comment by domiSchenk** [comment]
same with version 1.9.1

**Comment by arcanis** [comment]
I'll take a look today

**Comment by alvr** [comment]
Yeah, I got this problem too on Windows 10. I just tried with this:

`yarn add -D superagent`

Yarn 1.7.0: 

> info All dependencies
├─ asynckit@0.4.0
├─ combined-stream@1.0.6
├─ cookiejar@2.1.2
├─ delayed-stream@1.0.0
├─ form-data@2.3.2
├─ formidable@1.2.1
├─ mime@1.6.0
└─ superagent@3.8.3
Done in 4.11s.

Yarn 1.9.2:

> info All dependencies
├─ asynckit@0.4.0
├─ combined-stream@1.0.6
├─ cookiejar@2.1.2
├─ delayed-stream@1.0.0
├─ form-data@2.3.2
├─ formidable@1.2.1
├─ mime@1.6.0
└─ superagent@3.8.3
Done in 283.12s.

**Comment by arcanis** [comment]
Did it happen to anyone on Linux or osx, by any chance?

**Comment by alvr** [comment]
On the same computer and command above but running Ubuntu 18.04 on WSL:

> info All dependencies
├─ asynckit@0.4.0
├─ combined-stream@1.0.6
├─ cookiejar@2.1.2
├─ delayed-stream@1.0.0
├─ form-data@2.3.2
├─ formidable@1.2.1
├─ mime@1.6.0
└─ superagent@3.8.3
Done in 8.96s.

**Comment by arcanis** [comment]
So Windows adds 275s? o_O I have an idea what might cause this (https://github.com/yarnpkg/yarn/pull/6010), I'll test this as soon as I get on my Windows laptop.

**Comment by maiis** [comment]
@arcanis I can confirm, the same problem occurs on MacOS

**Comment by arcanis** [comment]
Hm, I just tried on OSX and didn't reproduce this issue 😞 0.90s with both `superagent` and `next-images`

**Comment by domiSchenk** [comment]
just testet with a new angular project:

> ng new test-app --skip-git --skip-install
> npx yarn@1.9.2 install 
>  ─> 63.77s (as expected ok for first time)
> npx yarn@1.9.2 add superagent   
> ─> hangs at linking 0/1118
> Done in 379.69s.

**Comment by arcanis** [comment]
While I don't have the same variation as you (I respectively get 4s vs 10s), I do get a significant delta increase. I'm almost positive that this is due to #6010, and some debug seem to confirm this. Seems like the check was heavier than I anticipated.

The fix will involve setting the timestamp to something sane at unpack time. What's annoying is that it will require to bump the cache version, since the old one has "corrupted" dates ...

**Comment by kenips** [comment]
@arcanis my original reproduction was on macOS 10.13.6. Let me see if I can test without #6010.

**Comment by kenips** [comment]
@aracarie I can confirm that reverting #6010 on 1.9.2 fixes the issue on macOS.

**Comment by SEAPUNK** [comment]
Likewise; #6010 completely wrecked our install times, esp. considering we install a lot of modules across a few workspaces. A few of my coworkers also report that node completely hangs for a good while before it's able to continue installation.

**Comment by arcanis** [comment]
Thanks everyone. I'll make a priority of fixing this issue, and hopefully a fix will land in 1.9.3, by friday at the latest (we can't just revert it, since the underlying problem is arguably worse, causing wrong packages to be installed).

**Comment by arcanis** [comment]
I've opened #6204 that should fix the issue. Can someone here please confirm that it clears the regression you witnessed? I don't see it as much as you, so I'd like to be sure it also fixes those horrible install time you have.

**Comment by rfuhrer** [comment]
@arcanis How would I install that branch to test?  I tried `npm i -g https://github.com/arcanis/yarn.git#fix-perfs` but I get `Error: Cannot find module '../lib/cli'` whenever I try to run yarn.

**Comment by arcanis** [comment]
You can use the prebuilt `yarn-1.10.0-0.js` file from the following zip:

[artifacts.zip](https://github.com/yarnpkg/yarn/files/2251068/artifacts.zip)

Something like `node ~/yarn-1.10.0-0.js install` should do the trick.

**Comment by rfuhrer** [comment]
1. I tried to install a small library on 1.9.2 and it took 405 seconds.
2. used your branch to removed it which triggered a whole cache redo, which was slow but you mention that in your pull request that we can't trust the cache timestamps
3. used the branch again to add that same library: 17 seconds.

Looks like this approach is the way to go on Windows 10 anyways

**Comment by arcanis** [comment]
Yep, the integrity line is a new change that'll get added in a later release (not entirely sure whether it'll be the 1.10 or 2.0). It won't be part of the 1.9.3, which will simply cherry-pick #6204.

**Comment by kenips** [comment]
@arcanis confirm that this fixes the issue for me

**Comment by stevethatcodes** [comment]
Can confirm this is also impacting OSX with Yarn 1.9.2

`yarn add redux-devtools -D --verbose` completing in between 88 - 120 seconds.

**Comment by peroperje** [comment]
Debian 8
node v8.11.3
yarn 1.9.2
[3/4] Linking dependencies - sometimes take a lot of time, sometimes even completely frozen.

**Comment by acao** [comment]
Still having this issue with:

- OSX High Sierra `10.13.6`
- Node `8.11.3`
- Yarn `1.10-x` nightly (in my case, `1.10.0-20180802.0946`)

**Comment by SEAPUNK** [comment]
@acao I'm pretty sure that nightlies are built off latest master, and the fix is still in a PR (hasn't been merged yet). Try the explicitly built version: https://github.com/yarnpkg/yarn/issues/6177#issuecomment-409715910

**Comment by acao** [comment]
@SEAPUNK ah yes that does work, thanks! Here are some explicit instructions for this temporary workaround for folks who are less shell-savvy, and not using windows.

1. Download / curl/ https://github.com/yarnpkg/yarn/files/2251068/artifacts.zip to `~/` (aka `/Users/myuser/` or `/user/myuser/` for osx/linux)
1. unzip to `~/artifacts`
1. `mv ~/artifacts/yarn-1.10.0-0.js ~/yarn/bin/yarn`
1. `rm -rf ~/artifacts ~/artifacts.zip`
4. `source ~/.bashrc`, or `.zshrc` or reset your shell session however.
5. now, `yarn` commands should work. `yarn -v` will resolve to `1.10.0-0`

**Comment by arcanis** [comment]
Fixed in the 1.9.4, now available! Let me know if that fixes the issue for you 🙂

**Comment by weishijun14** [comment]
I can't update to 1.9.4!!!

Why I did this:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```
and I update like this :
```
sudo apt-get update
```
result:
 
![_20180806112354](https://user-images.githubusercontent.com/20705423/43695581-1e6b395c-996c-11e8-9ea0-0d8dae6eb5c0.png)

**Comment by rictorres** [comment]
tried with `v1.9.4` and also with [`v1.10.0`](https://github.com/yarnpkg/yarn/issues/6177#issuecomment-409715910) and still having the same issues.

```
yarn install v1.10.0-0
// ...
success Saved lockfile.
✨  Done in 318.50s.
```

```
npm install
// ...
added 1588 packages in 62.024s
```

**Comment by kthakore** [comment]
Yeah it is still having a huge problem on v1.9.4

**Comment by chriswatrous** [comment]
If anyone still having problems, check the yarn version that's actually being run with `yarn -v`.

On my system (macOS) I had yarn@1.9.2 installed at `~/.yarn/bin/yarn` and that was shadowing the yarn@1.9.4 installed at `~/.nvm/versions/node/v8.11.4/bin/yarn`.

Use `which -a yarn` to see if you have more than one installed.

**Comment by pihyper** [comment]
Still having a problem with 1.10.0 . Very frustrating, and my boilerplate is tightly tied to the yarn system.  Im stuck with this stupid thing. npm was far better.

**Comment by arcanis** [comment]
Then use it, or help us understand what causes the slowdown you're experiencing. Noone will fix a problem without clear reproduction steps.

Also please open a new issue if you wish to help us. The issue described in this thread has been solved quite some time ago.

**Comment by bkoprivi** [comment]
> Then use it, or help us understand what causes the slowdown you're experiencing. Noone will fix a problem without clear reproduction steps.
> 
> Also please open a new issue if you wish to help us. The issue described in this thread has been solved quite some time ago.

you failed miserably with yarn 1.10.1. How about you perform some testing of the tool for a change?

**Comment by bkoprivi** [comment]
No, nothing has been solved. On the contrary, it's even worse now. yarn is broken.

**Comment by arcanis** [comment]
Locking this issue. If someone reads this and still get slowness with the 1.10 and above and is interested into mutual collaboration to fix it (that includes either a reproduction or an explanation as to where the problem comes from on your machine), please open a new issue.
