### ISSUE TITLE
postinstall hook doesn't appear to be run

### ISSUE THREAD

**Issue by wavded** [yarnpkg/yarn#721]
**Do you want to request a *feature* or report a *bug*?**

Not sure if its a feature or a bug, but I was expecting my `postinstall` hook to run after `yarn` was executed and it did not.

**What is the current behavior?**

`yarn` installs dependencies but does not run `postinstall` hook in the `package.json` file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Sample `package.json`:

```json
{
  "name": "hi",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "echo hi"
  },
  "dependencies": {
    "lodash": "*"
  },
  "main": "index.js",
  "license": "MIT"
}
```

Run `yarn`.  Do not see `hi` echoed.

**What is the expected behavior?**

Node 6.7.0 and Yarn 0.15.1 and macOS 10.12

**Please mention your node.js, yarn and operating system version.**

**Comment by wavded** [comment]
I noticed this comment from TC that may shed some light?

> By default, npm also allows developers who write these packages to execute other code that’s needed as part of the install process. That creates security issues, though, so Yarn does not have this feature.

-- [Source](https://techcrunch.com/2016/10/11/facebook-partners-with-google-others-to-launch-a-new-javascript-package-manager/)

Perhaps `postinstall` was removed intentionally?  It is handy when someone is setting up a project on their machine to have any additional setup stuff done at that point.

**Comment by Restuta** [comment]
It's handy in few other cases as well, e.g. on heroku it's a recommended way to customize build process https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process

**Comment by rjmunro** [comment]
This is strange, because in my experience, I found that the postinstall script was run for a package I was installing, but it didn't work for some reason, which I have documented in  https://github.com/yarnpkg/yarn/issues/614.

**Comment by shiftkey** [comment]
@rjmunro I also see the `postinstall` hooks working fine for installed packages, but any `postinstall` command defined in my `project.json` are ignored.

**Comment by rjmunro** [comment]
@shiftkey That sounds exactly backwards if the intention is to prevent third party code running on install unnecessarily.

**Comment by glebmachine** [comment]
Looks the same issue here: https://github.com/yarnpkg/yarn/issues/614

**Comment by kittens** [comment]
Fixed via #800.

**Comment by henev** [comment]
Still reproducible with Angular 2 Quickstart tutorial as described here: #818

**Comment by vith** [comment]
@karneaud Looks like it's working but terminal output is hidden. Currently open issue is here: https://github.com/yarnpkg/yarn/issues/5476
