### ISSUE TITLE
Failed to install dependencies in workspace: expected workspace package to exist

### ISSUE THREAD

**Issue by zamotany** [yarnpkg/yarn#7807]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn install` fails with:
```
error An unexpected error occurred: "expected workspace package to exist for \"@babel/template\"".
```

The error started occurring after upgrading yarn to `1.19` and it still persists in latest stable version `1.21.1`

Similar errors can be observed in #7797 and #7734 

**If the current behavior is a bug, please provide the steps to reproduce.**
The error can be reproduced when installing dependencies in https://github.com/callstack/haul

1. `git clone git@github.com:callstack/haul.git`
2. `cd haul`
3. `yarn install`

**What is the expected behavior?**

`yarn install` should successfully install dependencies.

**Please mention your node.js, yarn and operating system version.**
- Node: `12.14.1` / `13` (reproducible on both)
- yarn: `1.21.1`
- OS: macOS 10.15.2

**Comment by samrose3** [comment]
Experiencing the same behavior:

`error An unexpected error occurred: "expected workspace package to exist for \"@babel/highlight\"".`

Similar details

```
Yarn version: 
  1.21.1

Node version: 
  10.17.0

Platform: 
  darwin x64

OS
  macOS 10.15.2
```

**Comment by klaasman** [comment]
Experiencing the same issue with node@10:
```
An unexpected error occurred: "expected workspace package to exist for \"lru-cache\"".
```

```
Node: 10.15.3
yarn: 1.21.1
OS: macOS 10.15.1
```

I found a workaround by running the [policies feature](https://yarnpkg.com/lang/en/docs/cli/policies/) of yarn in my repo:
```
> yarn policies set-version 1.18.0
```
> Under the hood, the command will simply download the single-file release from the GitHub repository, store it inside your project (inside the .yarn/releases folder), then finally update your configuration to point to the new file (using yarn-path).

**Comment by schmod** [comment]
Also seeing this in Yarn 1.21.1.  I can reproduce the error in my repository when running `yarn upgrade-interactive`, _but_ manually bumping versions in `package.json` still works fine for some reason.

**Comment by mgcrea** [comment]
Encountering this as well:

```js
error An unexpected error occurred: "expected workspace package to exist for \"string-length\"".
```

When trying to add an unrelated dependency inside one on my workspace packages `yarn add @reduxjs/toolkit`. Manually adding the dep to package.json followed by a `yarn` does work.

**Comment by necrifede** [comment]
Same error here:

```bash
$ yarn workspace @scope/web add ramda
error An unexpected error occurred: "expected workspace package to exist for \"chalk\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/projects/web/apps/web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
```


Adding yarn-error.log

```
Arguments: 
  /home/user/.nvm/versions/node/v10.13.0/bin/node /home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js add ramda

PATH: 
  /home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.yarn/bin:/home/user/.config/yarn/global/node_modules/.bin:/home/user/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/user/Android/Sdk/emulator:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/tools/bin:/home/user/Android/Sdk/platform-tools:/home/user/Android/Sdk/emulator:/home/user/Android/Sdk/tools:/home/user/Android/Sdk/tools/bin:/home/user/Android/Sdk/platform-tools

Yarn version: 
  1.21.1

Node version: 
  10.13.0

Platform: 
  linux x64

Trace: 
  Invariant Violation: expected workspace package to exist for "chalk"
      at invariant (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:2314:15)
      at _loop2 (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:94898:9)
      at PackageHoister.init (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:94957:19)
      at PackageLinker.getFlatHoistedTree (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:48743:20)
      at PackageLinker.<anonymous> (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:48754:27)
      at Generator.next (<anonymous>)
      at step (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:310:30)
      at /home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/home/user/.nvm/versions/node/v10.13.0/lib/node_modules/yarn/lib/cli.js:5301:28)

npm manifest: 
{
   ...
}
```

**Comment by raspo** [comment]
I have been experiencing the same issues since `v1.19`.
`yarn upgrade-interactive` became unusable; It would fail to apply the version updates.

After updating to `v1.21` I'm not able to `yarn install` anymore. It always throws this error:
> expected workspace package to exist for ...

Downgrading to `1.18` fixed both issues.

I should point out that these problems only occur on one project, which is a monorepo that uses `lerna` and `yarn workspaces`.

**Comment by wesgro** [comment]
Same experience as @raspo 
Can't install packages from the command line anymore in my workspace enabled monorepo.

**Comment by nerdyman** [comment]
I didn't want to have to downgrade yarn since it comes from my package manager so I used npx as a terrible workaround.

```
npx yarn@1.19.0 add my-deps-here
```

**Comment by mayteio** [comment]
Also get this 1.17 through 1.22. It seems to be a handful of packages - starting with `istanbul-lib-instrument`. Then `jest-snapshot` then `cssstyle` repeatedly.

```
Invariant Violation: expected workspace package to exist for "istanbul-lib-instrument"
    at invariant (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:2314:15)
    at _loop2 (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:94959:9)
    at PackageHoister.init (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:95018:19)
    at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:48743:20)
    at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:48754:27)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:5301:28)
```

lerna.json
```
{
  "packages": [
    "packages/*",
    "apps/*"
  ],
  "version": "1.0.17",
  "npmClient": "yarn",
  "useWorkspaces": true
}

```

`package.json:`

```
{
...
"workspaces": {
    "packages": [
      "apps/*",
      "packages/*"
    ],
    "nohoist": [
      "**/webpack-dev-server"
    ]
  },
...
}
```

**Comment by pitops** [comment]
I am also getting this regression any news?

**Comment by OzzyCzech** [comment]
same here, monorepo and yarn interactive upgrade on mac

```
Invariant Violation: expected workspace package to exist for "stack-utils"
    at invariant (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:2314:15)
    at _loop2 (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:94959:9)
    at PackageHoister.init (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:95018:19)
    at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:48743:20)
    at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:48754:27)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:5301:28)
```

```
$ yarn lerna --version
3.20.2
$ yarn version
1.22.0
$ node --version
v13.8.0
```

**Comment by pitops** [comment]
As a temp solution use something `yvm` and use version `1.18.0`. Works for me

**Comment by export-mike** [comment]
```yarn policies set-version 1.18.0``` works for me - yarn will automatically switch to this version just for the project! so neat! 
https://classic.yarnpkg.com/en/docs/cli/policies/

**Comment by LasaleFamine** [comment]
I just had the same problem on a monorepo Lerna + Yarn (v1.22). Solved re-creating the `yarn.lock`.

**Comment by smith** [comment]
This looks like a duplicate of #7734.

**Comment by mhuggins** [comment]
Running into this for @storybook/api.  @nerdyman's workaround appears to have worked for me in the interim.

**Comment by xiaoTuiMao** [comment]
> I didn't want to have to downgrade yarn since it comes from my package manager so I used npx as a terrible workaround.
> 
> ```
> npx yarn@1.19.0 add your-deps-here
> ```

it's work for me

**Comment by americos** [comment]
I had this same problem and although deleting `yarn.lock` and running `yarn install` (or `yarn workspace some-workspace bla bla bla`) worked, the problem was that I was using a newer version of yarn compare to my team members.

So the solution was to use `yarn policies`. You basically run `yarn policies set-policy` and this will download the latest stable version of yarn and save it in `.yarn/` and also update your `.yarnrc` to point to downloaded yarn version. This way you can ensure everyone is using the same yarn version and avoid this kind of isues.

More info here: https://classic.yarnpkg.com/en/docs/cli/policies#toc-policies-set-version

**Comment by remorses** [comment]
So the solution to this problem is downgrading `yarn`, yarn 2.0 will be fun

**Comment by tilgovi** [comment]
@remorses apologies if I incorrectly read sarcasm in your reply. I haven't seen anyone submit a PR to fix this in 1.x. It's possible that, in other issues, folks have submitted fixes for this or other bugs that have been rejected, and that would make me sad. If there are abundant PRs for 1.x that are being ignored, I would hope that the maintainers would welcome community members who want to help maintain 1.x. Without PRs and maintenance from the community, it's hard to fault anyone for wanting to focus on their active development branch.

**Comment by abdullahceylan** [comment]
This usually happens if you are using a different version of the same npm package in workspaces.

Let's say you have `@scope/www` and `@scope/api` workspaces and both are have `eslint` npm package. But `@scope/www` is using `eslint@6.5.1` whereas `@scope/api` is using `eslint@5.12.1`. Also, you have `eslint@6.8.0` in the root `packages.json`.

Then if you try to install a package to one of the workspaces, you will get `error An unexpected error occurred: "expected workspace package to exist for \"eslint\"".` error. Because none of your `eslint` versions are identical.

Once you make them identical then you shouldn't get any error.

**Comment by friederbluemle** [comment]
That's interesting, thanks for the additional details @abdullahceylan - Just curious: How did Yarn before 1.19.2 (no error) handle this situation?

**Comment by abdullahceylan** [comment]
It also gives the same error to me @friederbluemle

**Comment by mkhbragg** [comment]
I was experiencing this issue because I had different versions of `@babel/core` in my workspaces, just as @abdullahceylan said. Updating `@babel/core` to the same version solved the problem for me! 🙏

**Comment by vandamm** [comment]
I wish there was a more specific message for this error.

**Comment by feedm3** [comment]
Also had this problem but could solve it:
The reason was that I had a package (eslint) in one of my packages and in the root workspace. Removed it from the root workspace and everything was working again.

**Comment by dxit** [comment]
That's interesting.
I had the same problem with, I got the error `An unexpected error occurred: "expected workspace package to exist for \"eslint\"".`
I've checked all my dependencies and devDependencies and there weren't duplicated. I've tried to recreate the `yarn.lock` but it didn't work for me.

I don't know why, but for me the problem was `react-scripts`. Since I've removed it, `yarn` was working again.
Hope it can help :)

**Comment by LennardWesterveld** [comment]
Found out that my issues came from that `@babel/core` in nextjs was fixed on `7.7.7` and some other modules were requiring `^7.10.0` so that why yarn puts extra node_modules folder inside your package to resolve the dependencies conflicts.

I solved it use `resolutions` by doing 
```
  "resolutions": {
    "**/@babel/core": "7.10.2"
  },
```

And did a `yarn install` / `npx lerna bootstrap`

**Comment by mmun** [comment]
In the application I am working on I was able to resolve this bug by changing

```json
"workspaces": [
  "packages/**/*"
],
```

to

```json
"workspaces": [
  "packages/@org1/*",
  "packages/@org2/*",
  "packages/*",
],
```

**Comment by havenchyk** [comment]
what worked for me is

`yarn lerna add npmpackage --scope=@scope/my-package`

you can use `npx` instead of `yarn` here

**Comment by jwaldrip** [comment]
Same here `yarn add` completely blows up on trying to do any package. Please fix 🙏

**Comment by Slapbox** [comment]
Suddenly running into this absolutely out of the blue. No idea how to remedy it.

**Comment by dxit** [comment]
I had the same issue with `yarn add`. In my case, it was complaining for `eslint`. I manually set the `eslint` version to `7.2.0`.
I went through my `yarn.lock` to check which dependencies were asking a different version of `eslint` (just used the "Find" tool with the `eslint` keyword).
I realized that lots of dependencies were requiring the version `6.8.0` and they were trying to install it.

I've solved the issue setting the `eslint` version to `6.8.0`.
Either you can choose to set add the `resolutions` parameter to your `package.json` file. In my case, it would have been like
```
"resolutions": {
  "eslint": "6.8.0"
}
```

Hope it can help someone.

**Comment by nathanielks** [comment]
Many thanks @dxit, that helps me 😄

**Comment by aecorredor** [comment]
Has anyone been able to pinpoint what exactly causes this? Will there be a fix included in v1? 

Running into the same thing on a monorepo that uses hoisting. Working around it with the npx hack for installing deps.

**Comment by kylemh** [comment]
@mmun your fix may be related to an incorrect resolution order regarding packages that rely on one another. See [here](https://github.com/lerna/lerna/issues/2009) for more details.

**Comment by ralphilius** [comment]
I had this error with below environment:

```
Node: 10.20.1
Yarn: 1.22.4
```
It was working with below setting.

```
Node: 10.15.3
Yarn: 1.13.0
```
I've tried to set Yarn to `1.18.0` but it seemed it doesn't work with Node `10.20.1`

**Comment by dkempner** [comment]
Note to self: revisit this once the next version of `yarn` is released.

**Comment by kylemh** [comment]
@dkempner yarn 1 wont be having new versions I don't think... If they are, it's awful quiet in this repo. You can try with yarn@berry tho

**Comment by thefat32** [comment]
After testing each release, bug starts in 1.19.2, at least for Windows. So some change between 1.19.1 - 1.19.2 breaks

**Comment by friederbluemle** [comment]
@thefat32 - Yup, that's correct. Not just on Windows. I have this command in my history that I use quite often as a workaround whenever I see the error:

```
npx yarn@1.19.1 upgrade-interactive
```

**Comment by heavenkiller2018** [comment]
I have the same problem.
```
error An unexpected error occurred: "expected workspace package to exist for \"jest\"".
```

**Comment by willemdjong** [comment]
Hi guys, we had the same issue! 

`An unexpected error occurred: "expected workspace package to exist for \"@jest-cli"".
`
I was experiencing this issue because I had different version of jest-cli in my workspace. **Resolved** it by upgrading all packages to latest version.

**Comment by customcommander** [comment]
@abdullahceylan Do you know if that's still the case though with _transitive_ dependencies? I've the same failure as everybody else but in my case the dependency isn't mine so I don't know how I could upgrade it.

**Comment by abdullahceylan** [comment]
@customcommander TBH I haven't encountered a situation like yours but the first thing I would try in such a situation  would be to use something like `"**/pagkage-name"` for `nohoist` option.

**Comment by customcommander** [comment]
Posted on Stack Overflow; just in case
https://stackoverflow.com/q/64060218/1244884

**Comment by zhiqingchen** [comment]
> @customcommander TBH I haven't encountered a situation like yours but the first thing I would try in such a situation would be to use something like `"**/pagkage-name"` for `nohoist` option.

why?

**Comment by mattvb91** [comment]
Currently experiencing this with lerna

**Comment by knowroozi** [comment]
We have narrowed this down to begin happening for us in `v1.19.2` 

Node: v12.13.0
yarn: works <= v1.19.1
OS: macOS 10.15.6

**Comment by Mancier** [comment]
Change the yarn policies to `yarn policies set-version 1.18.0` worked for me too.
I was in:
**Yarn**: 1.22.5
**Node**: 10.21
**OS**: Arch Linux (x64)

**Comment by smably** [comment]
I don't have a solution beyond the ones already suggested in this thread, but it seems that PR https://github.com/yarnpkg/yarn/pull/7289 is where the regression was introduced, and specifically, [these lines](https://github.com/yarnpkg/yarn/pull/7289/files#diff-b2f66a3a90f678d376e7e548e1983e7fe544eeb99d32b15d70eea6ebca48a544R859-R861).

The version of this bug that I've been experiencing is especially confusing because the dependency shown in the error message was only installed in the workspace root, and not in any of the nested workspaces.

I created a minimal repro here: https://github.com/smably/yarn-workspaces-hoisting-bug. In this case, I was getting `expected workspace package to exist for "pretty-quick"` even though `pretty-quick` only appears once in the tree. The actual error seems to be happening when yarn tries to hoist the transitive dependencies of `pretty-quick`.

I tried poking around in the yarn codebase to see if I could fix the issue, but quite a few of the unit tests are failing on my machine, the ["contributing" link in the README](https://github.com/yarnpkg/yarn#contributing-to-yarn) is broken, and I had a lot of trouble debugging because I wasn't able to get `console.log` or `debugger` statements to work (I'm guessing because `yarn` spawns child processes and they don't inherit node's `--inspect` flag). Sad to say that it seems like yarn 1 is no longer maintained by the original authors, nor is it easy an easy codebase for a new contributor to jump into.

**Comment by day-scene** [comment]
In my case, it might be the version confilcts of  `@babel/core`. I solved it by: check out the version installed by `yarn why @babel/core`,  add resolution to the package which is not the the same version to unify the version.

**Comment by danvoyce** [comment]
Adding this incase someone else (god help them) has a similar issue as I've just spent half my weekend debugging / basically reformatting my computer...

I set`yarn policies set-version 1.19.1` thinking everything was fine. A few hours later I did a build of my Next.js app and was getting this `Error occurred prerendering page...`. I literally tried everything under the sun, and have just realised that doing `yarn policies set-version 1.19.1` was the cause. 

What's even stranger is it destroys my local project. If I switch to a stable branch, delete all the node modules, yarn.lock etc etc, switch back to the latest version yarn, and run `yarn install`, then build my Next.js app again, I get the same error. 

I've no idea what's going on tbh. I literally re-installed node, yarn etc. The only solution was to delete the app and clone it again.

**Comment by xddz9** [comment]
I had the same issue with `eslint` package. Turns out the problem was my workspace root had eslint as a dev dependency, but I also had a workspace package that depended on an npm package that depended on a different version of eslint, which I assume ended up breaking the hoisting process somehow. All I did was make sure all packages depended on the same version of eslint and the error went away.

**Comment by pyramation** [comment]
also experiencing this issue. @export-mike 's solution works as a hotfix, thank you

**Comment by thefat32** [comment]
Is there any official response/fix roadmap from yarn dev team about this?

**Comment by danvoyce** [comment]
My solution was to switch to pnpm. Highly recommend it!

**Comment by schmod** [comment]
I'm 99% sure this is the same issue as #7734 – can we please close this as a duplicate?

**Comment by customcommander** [comment]
> I'm 99% sure this is the same issue as #7734 – can we please close this as a duplicate?

I would prefer if we could keep it open. It has some valuable information about how to reproduce. The other issue feels more like a _"i have the same issue"_ and _"downgrading worked for me"_ kind of thread in comparison.

Linking the two and possibly getting similar issues under a common label would help but closing this isn't going to revive the discussion on the other one.

**Comment by pyramation** [comment]
agree @customcommander and FWIW, this issue is the one that google continues to bring up when googling the error since I literally run into this problem every other day 😂  

I am working in many workspaces and this issue has for some reason, become more prevalent lately.

**Comment by programmer-yang** [comment]
node:v14.15.0
yarn:1.22.10

I also encountered this problem, and my solution was to delete the `yarn.lock` file and re-execute the `yarn install` command, and the problem was solved
> ps: I had this problem after upgrading my MAC system to Big Sur

**Comment by jamesdbruner** [comment]
@programm

> node:v14.15.0
> yarn:1.22.10
> 
> I also encountered this problem, and my solution was to delete the `yarn.lock` file and re-execute the `yarn install` command, and the problem was solved
> 
> > ps: I had this problem after upgrading my MAC system to Big Sur

Deleting your `yarn.lock` isn't a valid solution, you should never delete your `yarn.lock` without knowing exactly what you're doing. I learned this one the hard way.

**Comment by thefat32** [comment]
To extend @jamesdbruner warning, deleting your `yarn.lock` file will cause yarn to update all your packages. If dependency versions where not locked down, then every time the dependencies are installed through yarn install, the fetched dependencies may be different. If one of the dependencies has a new version available and the available version is within the specified version range in the package.json, then the newest dependency will be installed. This could be very dangerous, mostly if your  version range in the package.json allows major update (because this updates can have public API changes), but sometimes you can find a new bug when updating minor versions too. The nature of `yarn.lock` is to have complete control over which version of a dependency is used to have a stable enviroment for development.

**Comment by FrozenKiwi** [comment]
a slightly simpler workaround: directly add your dependency to package.json and then run `yarn` in the project root.

worked for me, yarn 1.22.4 on monorepo/lerna

**Comment by joeyfigaro** [comment]
Any updates or progress on investigating this? Using `yarn policies set-version` to rollback/specify a different version does not fix the issue for us. Only workaround currently is to add packages to package.json by hand prior to install.

**Comment by MKruschke** [comment]
Hi, unfortunately we encountered the same issue after upgrading to a newer babel version and adding on or two additional eslint plugins. The package that is doing a violation is already added in the package.json on the root level. 

As workaround I downgraded to v1.18.0. We used before 1.22.10 and also 1.19.2 had the same issue (see screenshot)

<img width="1022" alt="yarn-error_log_—_move-dealer-webapp__Workspace_" src="https://user-images.githubusercontent.com/1651782/104220404-b9b12800-543f-11eb-8dfe-7677e19dfa4e.png">

**Comment by bitjoo** [comment]
> Hi, unfortunately we encountered the same issue after upgrading to a newer babel version and adding one or two additional eslint plugins. The package that is doing a violation is already added in the package.json on the root level.
> 
> As workaround I downgraded to v1.18.0. We used before 1.22.10 and also 1.19.2 had the same issue (see screenshot)
> 

@MKruschke This bug can be fixed, without downgrading to v1.18.0, if you add the following to your package.json
```
"resolutions": {
    "**/@babel/traverse": "PLACE_YOUR_BABEL_TRAVERSE_VERSION_HERE"
  },
```

**Comment by joartola** [comment]
> I just had the same problem on a monorepo Lerna + Yarn (v1.22). Solved re-creating the `yarn.lock`.

THANKS! Delete root yarn.lock!

**Comment by nikaupp** [comment]
deleting yarn.lock helped to solve this for me.

**Comment by bryanvaz** [comment]
Just an FYI to anyone who hits this problem and is on `yarn > 1.18` and it happens after running `yarn upgrade`,
this is how you fix the issue without destroying your entire monorepo:
1. **DO NOT DELETE YOUR `yarn.lock`!!**
  This will likely cause a cascade of compatibility issues for you app _(issues scale exponentially based on the number of dependancies you have and how large/old your app is)._
2. Stash your changes with `git stash` or what ever code versioning you use if you have other changes beside the `yarn upgrade`. Your `yarn.lock` is corrupted beyond repair at this point.
3. Hard reset back to before you ran `yarn upgrade`. - This restores the `yarn.lock` that is correct and still works.
4. _Optional:_ Reset your `node` environment. I use `nvm`, so I just bumped up to the newest LTS release. You don't have to do this, but if you're paranoid, it doesn't hurt.
5. Remove your `yarn > 1.18` and install `yarn 1.18` globally. For some reason, just setting the `yarn policy` for the monorepo may not work (caused by certain operations using the global version, not the local policy version - I don't know which ones, but there's no margin for error when you are in this situation as you will have to start again if the wrong version of `yarn` runs even once during the upgrade operation).
  If you reset your `node` environment like me, you can just run `npm i -g yarn@1.18`.
6. Optional: Run `yarn policies set-version 1.18.0`. We did this to ensure all developers are running `1.18` minimizing the chance of the lock file corrupting.
7. Perform your `yarn upgrade` operations. Remember that if you upgrade the version of a dependency in one workspace, **YOU MUST** upgrade the dependency version in all workspaces, if you want to go back to a new version of `yarn` after upgrading. 
  Even if you do not go back to a newer version of `yarn` this is still recommended to prevent mismatched dependency versions from running. We suspect that `yarn workspaces` is not resolving dependency trees correctly when different top level dependencies are specified across workspaces.
8. Optional: Restore the newer version of `yarn` if you need to.
9. Apply your `git stash`, but reject all `yarn.lock` and `package.json` changes in your stash as those are corrupted.

Anyone who is currently running `lerna` and `yarn workspaces` should roll back to `yarn 1.18` when performing upgrades just as a precaution. This issue seems to appear when you have multiple large projects in a single monorepo that share the same "complex" dependencies (with at least 2+ levels of dependencies below). When upgrading the dependencies in a single project, if the new version of the dependency has a **new sub-dependency**, `yarn >= 1.19` does not resolve the new dependency tree correctly. Yarn's workspace checker appears to expects that all occurrences of the dependency throughout the monorepo to have the new sub-dependency, even though the other projects are using an older version that does not require it - at which point `yarn` breaks and refuses to perform any new upgrades.

Upgrading all instances of the dependency to the same new version using `yarn 1.18` allows the `yarn.lock` file to be structured correctly. Then after the upgrade, you can switch back to the newest version of yarn and everything should work fine. 

For larger teams, I recommend performing the upgrades in a container (e.g. `docker`.) This ensures the environments are clean and the `yarn.lock` files resolve and generate correctly, without having to alter your local environment.

**Comment by thefat32** [comment]
Does yarn team acknowledge this as a bug? Or we are doom to use older yarn version in our repos?

**Comment by kylemh** [comment]
I think the guidance from the yarn team is to move to yarn 2.

**Comment by bryanvaz** [comment]
Not sure if it is a bug present in `yarn@2`, but we're testing `yarn@2` next week under the same conditions to see if the same error crops up.

If anyone else has encountered this error, try upgrading to `yarn@2`. It would be useful to have more than 1 datapoint.

Cheers,
Bryan

**Comment by schmod** [comment]
If you're one of the many who are impacted by this issue, don't get your hopes up for a bugfix – [Yarn 1 appears to have been quietly deprecated](https://raw.githubusercontent.com/yarnpkg/yarn/master/.github/ISSUE_TEMPLATE/bug_report.md), and the maintainers no longer appear to be reviewing pull-requests in this repository.

If Yarn 2 doesn't work for you, consider switching to npm or pnpm.

**Comment by mike-marcacci** [comment]
FWIW I've slowly come to understand this bug more. It's very much still alive.

In particular the flaw appears to be a discrepancy between yarn planning dependencies and then executing. On a multi-workspace repo, I _often_ run into this when performing a `yarn upgrade-interactive --latest`. However, running a `yarn upgrade` followed by another `yarn upgrade-interactive --latest` will almost always allow it to proceed. Interestingly, running _another_ `yarn upgrade` often updates the lockfile further.

Essentially, my workaround is to alternate between `yarn upgrade-interactive --latest` and `yarn upgrade` until they succeed and make no further changes.

What I think is happening:
1. yarn calculates its target optimized directory structure based on the latest matching versions
2. yarn then plans its order of installation based on the assumption that transitive dependencies will exist at the "optimal" (flattest) level
3. yarn executes upgrades on each workspace, one-at-a-time and the mismatches between the some-new/some-old workspaces results in nested dependencies (instead of the optimized "flatter" structure it was expecting), which are not available to subsequent workspaces

This is all speculation based on behavior and without _any_ understanding of yarn's internals... but it follows what I imagine could be an easy false assumption when writing an optimizer, and I figured I would toss this here in case it nudges somebody more familiar with the codebase toward a solution.

**Comment by elado** [comment]
Another workaround:
I noticed this happens when I `yarn add ...` or `yarn workspace x add`. My solution is to revert yarn.lock to a working state, and instead of using `yarn` CLI to add/remove/upgrade packages, just change the package.json directly and run `yarn`.

**Comment by vitorgt** [comment]
> Not sure if it is a bug present in `yarn@2`, but we're testing `yarn@2` next week under the same conditions to see if the same error crops up.

@bryanvaz do you have any update on this? How did it went?

**Comment by varl** [comment]
Your mileage may vary on this one.

We've had success using `yarn-deduplicate` to "solve" this situation: https://github.com/atlassian/yarn-deduplicate

Eventually the `yarn.lock` grows in complexity again and the problem pops up, so then we need to run `npx yarn-deduplicate yarn.lock` again to resolve it.

It changes your lockfile so some form of regression testing is necessary.

**Comment by giautm** [comment]
> 200 IQ "fix": instead of using `yarn add`, manually add the dependency to `package.json` :shipit:

I ran into this issue when running `expo upgrade` in a mono-repo, which upgrades ~30 packages for given SDK version. I can't change every package version. So, only way to do is downgrade yarn to `1.18.0` with `yarn policies set-version 1.18.0`

**Comment by prkeshri** [comment]
Did npm install at the end. Phew!

**Comment by dwiyatci** [comment]
> I have been experiencing the same issues since `v1.19`. `yarn upgrade-interactive` became unusable; It would fail to apply the version updates.
> 
> After updating to `v1.21` I'm not able to `yarn install` anymore. It always throws this error:
> 
> > expected workspace package to exist for ...
> 
> Downgrading to `1.18` fixed both issues.
> 
> I should point out that these problems only occur on one project, which is a monorepo that uses `lerna` and `yarn workspaces`.

Updating to **`1.22.17`** seems to fix this `yarn upgrade-interactive` issue for me. I'm also in a monorepo project of `lerna` with `yarn` as its `npmClient` and `workspaces`. 🚝

**Comment by richardvanbergen** [comment]
Downgrading also works for me although I decided that it'd be better to upgrade to berry in the end. Works fine as long as you're not using zero-installs which I have never managed to make work.

**Comment by denik1981** [comment]
An external but simple _workaround_ would be to use a **volta** which is a toolchain manager and pin to the package the downgrade yarn version you need.

**Comment by denissabramovs** [comment]
This is still reproduced in latest `yarn v1.22.17`

```
error An unexpected error occurred: "expected workspace package to exist for \"@typescript-eslint/eslint-plugin\"".
info If you think this is a bug, please open a bug report with the information provided in "/var/local/acp/dashboards/packages/vpn/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by ashalfarhan** [comment]
> 200 IQ "fix": instead of using `yarn add`, manually add the dependency to `package.json` :shipit:

Still facing the same issue here, this is the only workaround that I've tried and works perfectly fine.

yarn: `1.22.17`
node: `16.13.2`

**Comment by cliffordfajardo** [comment]
> instead of using yarn add, manually add the dependency to package.json :shipit:
Resolved by doing this ^, same as last comment ^

yarn: 1.22.17
node: 16.13.2

**Comment by tbergquist-godaddy** [comment]
`yarn upgrade-interactive` is still failing for me

yarn: 1.22.17
node: 16.13.2 && 16.14.0

**Comment by aclopezffdc** [comment]
Still failing for me...
`yarn workspace test add chance`
`error An unexpected error occurred: "expected workspace package to exist for \"@jest/core\"".`
Yarn: 1.22.17
Node: 16.14.0

**Comment by askreet** [comment]
Is downgrading `yarn` three minor versions using `yarn policies` still the workaround for this? Worked for me, but seems "bad".

**Comment by mattvb91** [comment]
just as an fyi for people still posting in here. This repo is abandoned by the devs and the new "yarn" is over here: https://github.com/yarnpkg/berry

we had to drop yarn completely due to no longer having an upgrade path

**Comment by rogerprz** [comment]
I deleted my yarn.lock file and and re-installed. That worked for me.

**Comment by see** [comment]
same issue

**Comment by dwiyatci** [comment]
> I deleted my yarn.lock file and and re-installed. That worked for me.

Avoid deleting/re-creating `yarn.lock` file (_it's there for a reason_). Instead, try to dedupe its entries and then (re-)install.

```sh
npx yarn-dedupe && yarn install
```

**Comment by as-zlynn-philipps** [comment]
> Avoid deleting/re-creating `yarn.lock` file (_it's there for a reason_). Instead, try to dedupe its entries and then (re-)install.
> 
> ```shell
> npx yarn-dedupe && yarn install
> ```

I have been a full-stack developer for 10 years. I only ever delete my `yarn.lock` as an absolute last resort. Trust me. And, in the last two months, I've encountered about 5 separate situations where that was the only thing that fixed a work-blocking issue. The issue in this thread is the latest one. The fix is as inexplicable as each issue itself.

So, at this point, I'm pretty desensitized to it. If deleting the yarn.lock saves hours of scouring GitHub issues, docs, and StackOverflow, just heckin' do it. If all your deps are following semver and your ranges are properly scoped in package.json, shouldn't break anything to just get the latest acceptable version of everything. That's my two cents. 🤷‍♂️

Re: deduping, this package actually dedupes: https://medium.com/@bnaya/yarn-deduplicate-the-hero-we-need-f4497a362128

**Comment by askdesigners** [comment]
It's almost like all this javascript tooling is insane :)

**Comment by Devp00l** [comment]
I had this problem and could solve it by setting all corresponding packages in all Workspaces to the same version.

**Comment by Slapbox** [comment]
@as-zlynn-philipps the package you mentioned `yarn-dedupe` is probably not the one you meant to mention `yarn-deduplicate`: https://www.npmjs.com/package/yarn-deduplicate

**Comment by dwiyatci** [comment]
> @as-zlynn-philipps the package you mentioned `yarn-dedupe` is probably not the one you meant to mention `yarn-deduplicate`: https://www.npmjs.com/package/yarn-deduplicate

@Slapbox That was my mistake. He actually corrected it :)

**Comment by elenamik** [comment]
It stopped failing for me once I fixed my workspace names.

```
package.json
packages/
    hardhat/
        package.json
     ui/
        package.json
```


root package.json:

```
  "name": "web3-boilerplate",
  "private": true,
  "workspaces": ["packages/ui", "packages/hardhat"],
   //etc
```


packages/hardhat/package.json:
```
    "name": "@web3-boilerplate/hardhat",
    "version": "1.0.0",
    //etc
```


I previously had named the packages just `hardhat` and `ui` and this seems to have been causing the issue. **Changing to `@web3-boilerplate/hardhat` and `@web3-boilerplate/ui` seems to have fixed it!!**

**Comment by kelzenberg** [comment]
Instead of downgrading yarn to `1.18.0`, @elenamik solution fixed it for us. It was a workspace `package.json` naming issue. Thanks!

**Comment by leonheess** [comment]
How can this be? Yarn is broken for 8 months now and nothing is happening? Is the project dead?

**Comment by Slapbox** [comment]
@leonheess they're trying to push everyone over to `2.x` for most issues, presumably to minimize the load on the development team, but `2.x` is wildly different and incompatible all over the place still, so it's pretty rough.

**Comment by glensc** [comment]
<details>
<summary>Rant about yarn 2.x</summary>

the most blocking of yarn 2.x, 3.x is that it's inoperable, i.e you need to use a new lock file format and they require you to commit dependencies to the repository.

if yarn >=2 would support old lock file format and not require to commit tar.gz to repository the migration would be more smoother.

for example, I would switch CI jobs immediately and let developers take their own pace to switch.
</details>

**Comment by leonheess** [comment]
well we will switch our project to npm

**Comment by schmod** [comment]
>How can this be? Yarn is broken for 8 months now and nothing is happening? Is the project dead?

Yes.  This project is officially dead, because the (one) maintainer lost interest and stopped considering bugfix PRs from the community.

They quietly deprecated Yarn 1.x a few months back.  From the README:

> The 1.x codebase is fairly old and will only accept security fixes

**Comment by khaledosman** [comment]
This is what happens when you switch to the cool new thing instead of sticking with the community standard (npm) 🤷 
PS:[ npm now supports workspaces too](https://docs.npmjs.com/cli/v8/using-npm/workspaces), give them a try

**Comment by ajoslin103** [comment]
in order to get my project going again I had to use yarn 1

I installed corepack (suggested from the [deprecated] yarn version manager)

made sure I had entries in my package.json (and deleted a .yarnrc file asking for yarn 3)

```
  "packageManager": "yarn@1.22.19",
  "engines": {
    "node": ">=14.19 <=16.x",
    "yarn": "=1.22.19"
  },
```

Then activated the yarn I wanted

corepack prepare yarn@1.22.19 --activate

and then everything worked again

**Comment by sivaraj-v** [comment]
https://sebhastian.com/npm-err-cbapply-is-not-a-function/ Solved with help of nvm 16

**Comment by t-yng** [comment]
In my case, this problem is happened when I use same workspace name to external package.
I fixed by changing workspace name.

**bad**

root/package.json
```json
{
  "workspaces": ["packages/*"],
  "devDependencies": {
    "electron": "^13.1.5"
  }
}
```

root/packages/electron/package.json
```json
{
  "name": "electron",
}
```

**fixed**

root/packages/electron/package.json
```json
{
  "name": "app",
}
```

**Comment by git-lucky** [comment]
> > This is what happens when you switch to the cool new thing instead of sticking with the community standard (npm) 🤷 PS:[ npm now supports workspaces too](https://docs.npmjs.com/cli/v8/using-npm/workspaces), give them a try
> 
> Your comment is rude and unhelpful. I'm not even the person who chose to use Yarn on the project I'm having trouble with.

I thought this perspective was interesting and useful. Its good to remember the tradeoffs we make and the costs associated.

**Comment by HarikrishnanBalagopal** [comment]
> 

Tried deduping and it did not fix the issue.

What I am trying is `yarn workspace '@console/app' add react-markdown' in this repo https://github.com/openshift/console/tree/master/frontend

```
$ yarn workspace '@console/app' add react-markdown
yarn workspace v1.22.15
yarn add v1.22.15
[1/4] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "glob-parent@^3.1.0". Ignoring it.
warning Lockfile has incorrect entry for "postcss@^8.2.15". Ignoring it.
warning Lockfile has incorrect entry for "hosted-git-info@^2.1.4". Ignoring it.
warning Lockfile has incorrect entry for "glob-parent@^2.0.0". Ignoring it.
warning Lockfile has incorrect entry for "minimist@~0.0.1". Ignoring it.
[2/4] 🚚  Fetching packages...
warning Pattern ["asn1js@latest"] is trying to unpack in the same destination "/Users/user/Library/Caches/Yarn/v6/npm-asn1js-2.0.26-0a6d435000f556a96c6012969d9704d981b71251-integrity/node_modules/asn1js" as pattern ["asn1js@^2.0.26"]. This could result in non-deterministic behavior, skipping.
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.3: The engine "vscode" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning " > focus-trap-react@6.0.0" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning " > focus-trap-react@6.0.0" has incorrect peer dependency "react-dom@0.14.x || ^15.0.0 || ^16.0.0".
warning " > formik@2.0.3" has incorrect peer dependency "react@^16.8.0".
warning " > react-copy-to-clipboard@5.0.1" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning " > react-monaco-editor@0.41.2" has unmet peer dependency "@types/react@^17.x".
warning " > react-tagsinput@3.19.0" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning " > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @cypress/webpack-preprocessor@5.5.0" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @testing-library/user-event@13.1.9" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > cypress-axe@0.12.0" has unmet peer dependency "axe-core@^3 || ^4".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > cypress-axe@0.12.0" has incorrect peer dependency "cypress@^3 || ^4 || ^5 || ^6".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > cypress-multi-reporters@1.4.0" has unmet peer dependency "mocha@>=3.1.2".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > eslint-plugin-cypress@2.11.1" has unmet peer dependency "eslint@>= 3.2.1".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > eslint-plugin-import@2.22.1" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > mocha-junit-reporter@1.23.3" has unmet peer dependency "mocha@>=2.2.5".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > mochawesome@6.1.1" has unmet peer dependency "mocha@>=7".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > monaco-editor-webpack-plugin@1.9.0" has unmet peer dependency "monaco-editor@0.19.x || 0.20.x".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > ts-jest@21.2.4" has incorrect peer dependency "typescript@2.x".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > eslint-plugin-console > eslint-config-airbnb@18.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@^1.7.0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @patternfly/react-topology > mobx-react@6.2.5" has incorrect peer dependency "react@^16.8.0 || 16.9.0-alpha.0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @patternfly/react-topology > mobx-react > mobx-react-lite@2.0.7" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning "workspace-aggregator-e2343549-0680-43d4-8fc0-bd66fb5d3be6 > @graphql-codegen/typescript > @graphql-codegen/visitor-plugin-common > @graphql-tools/relay-operation-optimizer > relay-compiler@10.0.0" has incorrect peer dependency "graphql@^15.0.0".
warning " > react-markdown@8.0.5" has unmet peer dependency "@types/react@>=16".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
error An unexpected error occurred: "expected workspace package to exist for \"ts-node\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/user/Documents/code/remote/github.com/openshift/console/frontend/packages/console-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/user/.nvm/versions/node/v16.17.0/bin/node
Arguments: /Users/user/Documents/code/remote/github.com/openshift/console/frontend/.yarn/releases/yarn-1.22.15.js add react-markdown
Directory: /Users/user/Documents/code/remote/github.com/openshift/console/frontend/packages/console-app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**Comment by Elmhaf** [comment]
A quick hack to bypass the issue when installing any package is to manually type the desired package in the package.json file . Make sure you verify the version needed in the npm site. Good luck!

**Comment by rogerprz** [comment]
Still experiencing this issue now :/ 

`error An unexpected error occurred: "expected workspace package to exist for \"@testing-library/jest-dom\"".`

**Comment by gsben** [comment]
if your project has lerna and used it, you can use lerna to install package instead of yarn.
such as: lerna add xxx(package name) --scope=your subproject name(if exist subproject)

**Comment by gruckion** [comment]
The above suggestion of using npx works

```
npx yarn@1.19.1 workspace your-deps-here
```

The suggestion to rename the root `package.json` `name` made no difference.

The issue was introduced with [Yarn 1.19.2](https://www.npmjs.com/package/yarn/v/1.19.2). Using [Yarn 1.19.1](https://www.npmjs.com/package/yarn/v/1.19.1) works fine. Looking at what was introduced in this version [here](https://github.com/yarnpkg/yarn/releases/tag/v1.19.2).

The part of the code that mentions `expected workspace package to exist for` was modified here [src/package-hoister.js](https://github.com/yarnpkg/yarn/blob/158d96dce95313d9a00218302631cd263877d164/src/package-hoister.js#L829)

This change was introduced with this [PR on May 20, 2019](https://github.com/yarnpkg/yarn/pull/7289/files) which was addressing the following `Dependencies not symlinked when root package depends on older version of packages from npm, reported [here](https://github.com/yarnpkg/yarn/issues/4289).

Based on the code here, it is forcing us to list the package we want in the workspace as well as the root. It escape the hoisting logic which results in the package not being placed into the child workspace.

**Comment by mattvb91** [comment]
> just as an fyi for people still posting in here. This repo is abandoned by the devs and the new "yarn" is over here: https://github.com/yarnpkg/berry
> 
> we had to drop yarn completely due to no longer having an upgrade path

Not sure why this repo is not archived at this point.

**Comment by pg328** [comment]
What worked for me:
1. Renaming `package.json` name field worked for me
  - I had a name that conflicted with an npm package (I'd called it "astro" and in the example above, they called it "electron")
2. Ensure that in `package.json` the `private` field is `true`.

**Comment by sheetalmjkrishna** [comment]
I was able to overcome this using a similar workaround:
_First:_
`yarn policies set-version 1.19.0`
_And then:_
`yarn add <your dependency>`

**Comment by aprilmintacpineda** [comment]
I'm getting the same error:

```
yarn add @total-typescript/ts-reset
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-a7929ca9-ae57-448a-adbb-5f1081fea51c > mymonorepo > gatsby > eslint-config-react-app@6.0.0" has unmet peer dependency "babel-eslint@^10.0.0".
warning "workspace-aggregator-a7929ca9-ae57-448a-adbb-5f1081fea51c > mymonorepo > gatsby > react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825" has incorrect peer dependency "react@0.0.0-experimental-c8b778b7f-20220825".
warning Workspaces can only be enabled in private projects.
error An unexpected error occurred: "expected workspace package to exist for \"@typescript-eslint/visitor-keys\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/aprilmintacpineda/projects/mymonorepo/apps/api/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Any help?

**Comment by andersondanilo** [comment]
Removing the yarn.lock and the node modules, and then doing an yarn install again, solved it to me

**Comment by ccpu** [comment]
For my removing duplicates from yarn.lock always solves the problem, here is the package i am using:
[https://github.com/scinos/yarn-deduplicate](https://github.com/scinos/yarn-deduplicate)

**Comment by zhanghengxin** [comment]
delete yarn.lock!! this allows you skip the question.

**Comment by zhanghengxin** [comment]
it is easy! you can use yarn@3.5.1

For monorepos, the best version of Yarn to use is 3.5. 

```shell
corepack enable

corepack prepare yarn@latest --activate
```

**Comment by korpiq-tiketti** [comment]
We have an nx monorepo. I get `error An unexpected error occurred: "expected workspace package to exist for \"@jest/types\""` for `yarn add ...` in many of its project subdirectories ("workspaces").

Removing the root `yarn.lock` file changed that to `error An unexpected error occurred: "expected workspace package to exist for \"ts-jest\""`. Running `npx yarn-deduplicate yarn.lock` did not change that.

`yarn-error.log` attached.

[yarn-error.log](https://github.com/yarnpkg/yarn/files/13377413/yarn-error.log)

**Comment by mvanzoest** [comment]
I recently upgraded lerna to 7.4.2 and nx to 17.1.3 and started seeing this error. None of the workarounds posted helped me because the package requires yarn 1.22.21+ (The engine "yarn" is incompatible with this module. Expected version ">=1.22.21". Got "1.19.0”). The only workaround I could find was manually adding the package to the package.json and running yarn, which seemed to work for me.

**Comment by zhanghengxin** [comment]
> I recently upgraded lerna to 7.4.2 and nx to 17.1.3 and started seeing this error. None of the workarounds posted helped me because the package requires yarn 1.22.21+ (The engine "yarn" is incompatible with this module. Expected version ">=1.22.21". Got "1.19.0”). The only workaround I could find was manually adding the package to the package.json and running yarn, which seemed to work for me.我最近将 lerna 升级到 7.4.2，将 nx 升级到 17.1.3，并开始看到此错误。发布的任何解决方法都没有帮助我，因为该软件包需要 yarn 1.22.21+（引擎“yarn”与此模块不兼容。预期版本“>=1.22.21”。得到“1.19.0”）。我能找到的唯一解决方法是手动将包添加到package.json并运行yarn，这似乎对我有用。

看看你的 package.json

**Comment by iway1** [comment]
> it is easy! you can use yarn@3.5.1. For monorepos, the best version of Yarn to use is 3.5.

Yarn 3.5 is not a viable option for a lot of people. For example Expo for React Native doesn't use it. I think a lot more people are on yarn v1 still than v3, it'd be nice if this bug was fixed

**Comment by aribakker** [comment]
In my case I noticed that in two of the workspaces I had a newer version of a package than in the root package.json (specifically I had @storybook/react@^7.2.1 in the workspaces and @storybook/react@6.3.4 in the root). When I changed these to all have the same version and removed the yarn.lock file it started working. I was able to identify this package by searching for the package name in the error (webpack in this case) in the yarn-error.log.

**Comment by ps-scottmurray** [comment]
Through experimentation, I suspect that this may be caused by a version conflict between your workspace dependency version and the root version though what specifically is causing it may depend on your circumstance.  In one case, I was able to address duplicates in the yarn.lock.  In another case, I realized that the library was redundant in the root package.  In both cases, different workspaces held different versions (I'm in the process of upgrading them)

**Comment by mattvb91** [comment]
> > just as an fyi for people still posting in here. This repo is abandoned by the devs and the new "yarn" is over here: https://github.com/yarnpkg/berry
> > we had to drop yarn completely due to no longer having an upgrade path
> 
> Not sure why this repo is not archived at this point.

### Yearly reminder THAT THIS PROJECT IS ABANDONED 

https://github.com/yarnpkg/berry

**Comment by its-dibo** [comment]
try deleting `yarn.lock` and run `yarn workspace <app< add <package>` again

**Comment by iway1** [comment]
Is there a petition for yarn maintainers to abandon yarn berry in favor of continuing maintenance on this version?
