### ISSUE TITLE
Yarn 1.22.8 preinstall script fails on GitHub actions with bad file descriptor number

### ISSUE THREAD

**Issue by agrobbin** [yarnpkg/yarn#8360]
### Bug description

When Yarn 1.22.8 hit the NPM registry, GitHub Actions started installing it when running `npm install -g yarn`, and we started seeing failures.

**Command**

```sh
> yarn@1.22.8 preinstall /opt/hostedtoolcache/node/12.16.3/x64/lib/node_modules/yarn
> :; (node ./preinstall.js >& /dev/null || true)

sh: 1: Syntax error: Bad fd number
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! yarn@1.22.8 preinstall: `:; (node ./preinstall.js >& /dev/null || true)`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the yarn@1.22.8 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**What is the current behavior?**
`npm install -g yarn` fails when running the preinstall script.

**What is the expected behavior?**
`npm install -g yarn` successfully runs the preinstall script.

**Steps to Reproduce**

1. `npm install -g yarn`

**Environment**

- Node Version: `12.16.3`
- Yarn v1 Version: `1.22.8` 
- OS and version:  Ubuntu 18.04.5 LTS

**Comment by alexbikazzan** [comment]
We had the same problem on our build server inside a docker container. We had to run `npm install -g yarn@1.22.7` and it worked, so I guess there is something in the latest version.

**Comment by gonzaloaune** [comment]
Seems it's fixed now

**Comment by jorrit91** [comment]
@gonzaloaune Can confirm, seems to be fixed.

**Comment by laander** [comment]
We're still experiencing the issue with the latest version (as of writing) `v1.22.9`. Seems fishy since latest tag in this repo is `v1.22.5` - where does the latest 4 patch versions come from?

**Comment by ClemArt** [comment]
Resolved with the 1.22.10.
Just as @laander asked, where does the last 5 patch come from ? Are they released from specific commits ?

**Comment by alexbikazzan** [comment]
They are tracked on npm:
[https://www.npmjs.com/package/yarn](https://www.npmjs.com/package/yarn)

Maybe just not tagged on github I guess?

**Comment by arcanis** [comment]
Going to close as duplicate of https://github.com/yarnpkg/yarn/issues/8358, which has more details (basically, the patches don't reflect at the moment the releases due to an infra problem. Those commits were published on the `1.22-stable` branch.).
