### ISSUE TITLE
Add postupgrade hook after yarn upgrade is run

### ISSUE THREAD

**Issue by matty-liu** [yarnpkg/yarn#8498]
**Bug Description**

Sorry if I am not following procedure, was looking at this issue
https://github.com/yarnpkg/yarn/issues/2878 
and saw a note that if the issue still exists to create a new ticket.

After running `yarn upgrade`, my postinstall script is not run.

**Command**

`yarn upgrade`

**What is the current behavior?**

`yarn upgrade` runs without trigger the postinstall script after it runs

**Steps to Reproduce**

Add the below script into package.json
```
{
  "scripts": {
    "postinstall": "echo post install script ran"
  }
}
```
Execute yarn upgrade.

Either behavior of having the postinstall script run after `yarn upgrade` or if a postupgrade hook was added that I could use to run my script would be desirable.

**Environment**
Node Version: 14.6.0
Yarn v1 Version: v1.22.4
OS and version: MacOS Catalina 10.15.7

**Comment by jlurena** [comment]
The same should be applied for `yarn remove`

**Comment by merceyz** [comment]
Closing as fixed in v2 where the `postinstall` script is called whenever your dependency tree changes

https://yarnpkg.com/getting-started/migration

**Comment by klemenoslaj** [comment]
@merceyz could we get the fix to v1 as well?

A lot of repositories are still unable to move to v2 so I wonder if such issues should really be just closed?
In other words, you're alienating a lot of repositories, forcing people to work around `yarn` v1 issues or alternatively migrate back to `npm`.
