### ISSUE TITLE
Can't install package globally on Windows

### ISSUE THREAD

**Issue by wtchangdm** [yarnpkg/yarn#859]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
unable to install package globally

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn global add pm2`

```
c:\>yarn global add pm2
yarn global v0.15.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error ENOENT: no such file or directory, open 'C:\Users\***\AppData\Local\Yarn\.global\node_modules\abbrev\abbrev.js'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**What is the expected behavior?**
install package like `npm install -g pm2`

**Please mention your node.js, yarn and operating system version.**
Windows 10 x64 Enterprise, version 1607 (build 14393.321)
node js 6.7.0
yarn 0.15.1

**Comment by kevincaradant** [comment]
Hi

Same problem with Windows 7(x64)

**Comment by gavinbarron** [comment]
Seems to be happening where there's a dependency on abbrev as this is also impacting installing yo

```
> yarn global add yo
yarn global v0.15.1
warning No license field
[1/4] Resolving packages...
warning yo > fullname > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
[2/4] Fetching packages...
[3/4] Linking dependencies...
error ENOENT: no such file or directory, open 'C:\Users\gavinb\AppData\Local\Yarn\.global\node_modules\abbrev\abbrev.js'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.
> node -v
v4.5.0
```
Windows 10 Build 14396

**Comment by keysona** [comment]
Also in window10 (x64) , I can't globally install.

In linking dependencies.

This error:
```
[3/4] Linking dependencies...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
error ENOENT: no such file or directory, open 'C:\Users\keypy\AppData\Local\Yarn\.global\node_modules\abbrev\abbrev.js'
    at Error (native)
```

```
# yarn -v
v0.15.1

# node -v
v4.5.0
```

**Comment by davewallace** [comment]
Same here; Win10x64, node -v `v6.7.0`, yarn -v `v0.15.1`, chokes on `.global\node_modules\abbrev\abbrev.js`.

**Comment by altyne** [comment]
same here when installing karma global.

> yarn global add are-we-there-yet
yarn global v0.15.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
[3/4] Linking dependencies...
error ENOENT: no such file or directory, open 'C:\Users\myUsername\AppData\Local\Yarn\.global\node_modules\abbrev\abbrev.js'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/global for documentation about this command.

windows 8.1 enterprise x64
node 4.5.0
npm 2.15.9

**Comment by altyne** [comment]
source: [https://github.com/yarnpkg/yarn/issues/1073#issuecomment-254158785]

It resolve by modifying the registry:
old value: https://registry.yarnpkg.com
new value (fixed): https://registry.yarnpkg.com//

add the double backlashes in registry. (yarn config set registry https://registry.yarnpkg.com//)

**Comment by dheerajbhaskar** [comment]
@altyne that didn't work got a error 500 on packages and install failed

**Comment by jamesdixon** [comment]
I can also confirm this issue.

Node 6.9.1
Yarn 0.16.1
Windows Server 2012 R2 (x64)

**Comment by dheerajbhaskar** [comment]
#1600 might be related

**Comment by busches** [comment]
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest Yarn `v0.17.10`.

```sh
yarn global add pm2
yarn global v0.17.10
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/3] ⢀ waiting...
[2/3] ⠠ fsevents: gyp info using node@6.9.1 | win32 | x64
[-/3] ⠠ waiting...
[-/3] ⠠ waiting...
error Error running install script for optional dependency: <fsevents truncated>
success Installed pm2@2.1.6 with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
warning No license field
Done in 92.80s.
```

**Comment by xt0rted** [comment]
Still unable to install global packages with `0.17.10`

```
[4/4] Building fresh packages...
success Installed gulp@3.9.1 with binaries:
      - gulp
warning No license field
error An unexpected error occurred: "EPERM: operation not permitted, open 'C:\\Program Files\\nodejs\\gulp.cmd'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\brian\\AppData\\Local\\Yarn\\config\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

```
[4/4] Building fresh packages...
success Installed bower@1.8.0 with binaries:
      - bower
warning No license field
error An unexpected error occurred: "EPERM: operation not permitted, open 'C:\\Program Files\\nodejs\\bower.cmd'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\brian\\AppData\\Local\\Yarn\\config\\global\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by busches** [comment]
@xt0rted that's a different error, as you're attempting to install into `Program Files` which requires admin access. You can run `cmd` as admin or change the prefix for `yarn`. Something like `yarn config set prefix %AppData%\yarn`.

**Comment by wtchangdm** [comment]
Hi, I've installed to yarn@latest. pm2 was installed along with several errors but I can't use pm2 command at all.

I've upgrade node js to 7.2.0 though, not sure if it's related.

`c:\>yarn --version
0.17.10`

`
c:\>yarn global add pm2
yarn global v0.17.10
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⢀ fsevents: C:\Users\**username**\AppData\Local\Yarn\config\global\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Users\**username**\AppData\Roaming\npm\node_modules\yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
error Error running install script for optional dependency: "C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-pre-gyp install --fallback-to-build\nDirectory: C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.29\nnode-pre-gyp info using node@7.2.0 | win32 | x64\nnode-pre-gyp info check checked for \"C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-win32-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-win32-x64.tar.gz\nnode-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-win32-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-win32-x64.tar.gz \n\r\nC:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents>if not defined npm_config_node_gyp (node \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" clean )  else (node  clean ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@7.2.0 | win32 | x64\ngyp info ok \n\r\nC:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents>if not defined npm_config_node_gyp (node \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" configure --fallback-to-build --module=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64 )  else (node  configure --fallback-to-build --module=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64 ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@7.2.0 | win32 | x64\ngyp info spawn C:\\Python27\\python.exe\ngyp info spawn args [ 'C:\\\\Users\\\\**username**\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\**username**\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\**username**\\\\.node-gyp\\\\7.2.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\**username**\\\\.node-gyp\\\\7.2.0',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\**username**\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nTraceback (most recent call last):\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 16, in <module>\r\n    sys.exit(gyp.script_main())\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 545, in script_main\r\n    return main(sys.argv[1:])\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 538, in main\r\n    return gyp_main(args)\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 523, in gyp_main\r\n    generator.GenerateOutput(flat_list, targets, data, params)\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 2003, in GenerateOutput\r\n    sln_projects, project_objects, flat=msvs_version.FlatSolution())\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1762, in _GatherSolutionFolders\r\n    return _DictsToFolders('', root, flat)\r\n  File \"C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1715, in _DictsToFolders\r\n    for folder, contents in bucket.iteritems():\r\nAttributeError: 'MSVSProject' object has no attribute 'iteritems'\r\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (C:\\Users\\**username**\\AppData\\Roaming\\npm\\node_modules\\yarn\\node_modules\\node-gyp\\lib\\configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\**username**\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\yarn\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v51-win32-x64\\\\fse.node\" \"--module_name=fse\" \"--module_path=C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v51-win32-x64\"\ngyp ERR! cwd C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\ngyp ERR! node -v v7.2.0\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\\Users\\**username**\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\lib\\util\\compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:106:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)\nnode-pre-gyp ERR! System Windows_NT 10.0.14393\nnode-pre-gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\**username**\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnsuccess Installed pm2@2.1.6 with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
warning No license field
Done in 6.51s.`


try to use pm2:
`c:\>pm2 list
'pm2' is not recognized as an internal or external command`

**Comment by zaggy** [comment]
I get the same error as @wtchangdm 

```
λ yarn --version
0.17.10
```
```
λ yarn global add pm2
yarn global v0.17.10
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⠈ waiting...
[-/4] ⠁ waiting...
[3/4] ⠁ fsevents: Failed to execute 'C:\Apps\nodejs\node.exe C:\Users\User.Name\AppData\Local\Yarn\
[-/4] ⠁ waiting...
error Error running install script for optional dependency: "C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents: Command failed.\nExit code: 1\nCommand: C:\\Windows\\system32\\cmd.exe\nArguments: /d /s /c node-pre-gyp install --fallback-to-build\nDirectory: C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.29\nnode-pre-gyp info using node@7.2.0 | win32 | x64\nnode-pre-gyp info check checked for \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-win32-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-win32-x64.tar.gz\nnode-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-win32-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-win32-x64.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@7.2.0 | win32 | x64\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@7.2.0 | win32 | x64\ngyp info spawn C:\\Python27\\python.exe\ngyp info spawn args [ 'C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=2015',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\User.Name\\\\.node-gyp\\\\7.2.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\User.Name\\\\.node-gyp\\\\7.2.0',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\nTraceback (most recent call last):\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\gyp_main.py\", line 16, in <module>\r\n    sys.exit(gyp.script_main())\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 545, in script_main\r\n    return main(sys.argv[1:])\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 538, in main\r\n    return gyp_main(args)\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\__init__.py\", line 523, in gyp_main\r\n    generator.GenerateOutput(flat_list, targets, data, params)\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 2003, in GenerateOutput\r\n
  sln_projects, project_objects, flat=msvs_version.FlatSolution())\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1762, in _GatherSolutionFolders\r\n    return _DictsToFolders('', root, flat)\r\n  File \"C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\gyp\\pylib\\gyp\\generator\\msvs.py\", line 1715, in _DictsToFolders\r\n    for folder, contents in bucket.iteritems():\r\nAttributeError: 'MSVSProject' object has no attribute 'iteritems'\r\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\lib\\configure.js:305:16)\ngyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack
at ChildProcess.emit (events.js:191:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)\ngyp ERR! System Windows_NT 6.1.7601\ngyp ERR! command \"C:\\\\Apps\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v51-win32-x64\\\\fse.node\" \"--module_name=fse\" \"--module_path=C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\lib\\\\binding\\\\Release\\\\node-v51-win32-x64\" \"--python=C:\\\\tools\\\\Python27\\\\python.exe\" \"--msvs_version=2015\"\ngyp ERR! cwd C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\ngyp ERR! node -v v7.2.0\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'C:\\Apps\\nodejs\\node.exe C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js configure --fallback-to-build --module=C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node --module_name=fse --module_path=C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64 --python=C:\\tools\\Python27\\python.exe --msvs_version=2015' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\lib\\util\\compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:106:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)\nnode-pre-gyp ERR! System Windows_NT 6.1.7601\nnode-pre-gyp ERR! command \"C:\\\\Apps\\\\nodejs\\\\node.exe\" \"C:\\\\Users\\\\User.Name\\\\AppData\\\\Local\\\\Yarn\\\\config\\\\global\\\\node_modules\\\\fsevents\\\\node_modules\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\nnode-pre-gyp ERR! node -v v7.2.0\nnode-pre-gyp ERR! node-pre-gyp -v v0.6.29\nnode-pre-gyp ERR! not ok \nFailed to execute 'C:\\Apps\\nodejs\\node.exe C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\node-gyp\\bin\\node-gyp.js configure --fallback-to-build --module=C:\\Users\\User.Name\\AppData\\Local\\Yarn\\config\\global\\node_modules\\fsevents\\lib\\binding\\Release\\node-v51-win32-x64\\fse.node --msuccess Installed pm2@2.1.6 with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
warning No license field
Done in 26.08s.
```

I have Windows 7 x64 / Node 7.2.0

**Comment by dheerajbhaskar** [comment]
Errors from @zaggy and @wtchangdm seem to be from node-gyp. Last Two Stack Traces might not be a Yarn Error Do The packages Work Ehrn Installed With Npm? 

Ps: Sorry About The Weird Capitalization. Something Is Not Working Well With Swiftkey And This Comment BOx On Github

**Comment by wtchangdm** [comment]
@dheerajbhaskar Hi, as far as I know, that fsevents is not available on windows, if I install pm2 via npm, it would be skipped.

```
C:\Users\**username**>npm -g i pm2
C:\Users\**username**\AppData\Roaming\npm\pm2-dev -> C:\Users\**username**\AppData\Roaming\npm\node_modules\pm2\bin\pm2-dev
C:\Users\**username**\AppData\Roaming\npm\pm2 -> C:\Users\**username**\AppData\Roaming\npm\node_modules\pm2\bin\pm2
C:\Users\**username**\AppData\Roaming\npm\pm2-docker -> C:\Users\**username**\AppData\Roaming\npm\node_modules\pm2\bin\pm2-docker
C:\Users\**username**\AppData\Roaming\npm\rundev -> C:\Users\**username**\AppData\Roaming\npm\node_modules\pm2\bin\rundev
C:\Users\**username**\AppData\Roaming\npm
`-- pm2@2.1.6
  +-- async@1.5.2
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.0.0
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- chokidar@1.6.1
  | +-- anymatch@1.3.0
  | | +-- arrify@1.0.1
  | | `-- micromatch@2.3.11
  | |   +-- arr-diff@2.0.0
  | |   | `-- arr-flatten@1.0.1
  | |   +-- array-unique@0.2.1
  | |   +-- braces@1.8.5
  | |   | +-- expand-range@1.8.2
  | |   | | `-- fill-range@2.2.3
  | |   | |   +-- is-number@2.1.0
  | |   | |   +-- isobject@2.1.0
  | |   | |   +-- randomatic@1.1.6
  | |   | |   `-- repeat-string@1.6.1
  | |   | +-- preserve@0.2.0
  | |   | `-- repeat-element@1.1.2
  | |   +-- expand-brackets@0.1.5
  | |   | `-- is-posix-bracket@0.1.1
  | |   +-- extglob@0.3.2
  | |   +-- filename-regex@2.0.0
  | |   +-- kind-of@3.0.4
  | |   | `-- is-buffer@1.1.4
  | |   +-- normalize-path@2.0.1
  | |   +-- object.omit@2.0.1
  | |   | +-- for-own@0.1.4
  | |   | | `-- for-in@0.1.6
  | |   | `-- is-extendable@0.1.1
  | |   +-- parse-glob@3.0.4
  | |   | +-- glob-base@0.3.0
  | |   | `-- is-dotfile@1.0.2
  | |   `-- regex-cache@0.4.3
  | |     +-- is-equal-shallow@0.1.3
  | |     `-- is-primitive@2.0.0
  | +-- async-each@1.0.1
  | +-- glob-parent@2.0.0
  | +-- inherits@2.0.3
  | +-- is-binary-path@1.0.1
  | | `-- binary-extensions@1.7.0
  | +-- is-glob@2.0.1
  | | `-- is-extglob@1.0.0
  | +-- path-is-absolute@1.0.1
  | `-- readdirp@2.1.0
  |   +-- graceful-fs@4.1.11
  |   +-- minimatch@3.0.3
  |   | `-- brace-expansion@1.1.6
  |   |   +-- balanced-match@0.4.2
  |   |   `-- concat-map@0.0.1
  |   +-- readable-stream@2.2.2
  |   | +-- buffer-shims@1.0.0
  |   | +-- core-util-is@1.0.2
  |   | +-- isarray@1.0.0
  |   | +-- process-nextick-args@1.0.7
  |   | +-- string_decoder@0.10.31
  |   | `-- util-deprecate@1.0.2
  |   `-- set-immediate-shim@1.0.1
  +-- cli-table@0.3.1
  | `-- colors@1.0.3
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- cron@1.1.1
  | `-- moment-timezone@0.5.10
  +-- debug@2.3.3
  | `-- ms@0.7.2
  +-- eventemitter2@1.0.5
  +-- fclone@1.0.10
  +-- gkt@1.0.0
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- moment@2.17.0
  +-- nssocket@0.6.0
  | +-- eventemitter2@0.4.14
  | `-- lazy@1.0.11
  +-- pidusage@1.1.0
  +-- pm2-axon@3.0.2
  | +-- amp@0.3.1
  | +-- amp-message@0.1.2
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | `-- escape-regexp@0.0.1
  +-- pm2-axon-rpc@0.4.5
  | `-- fclone@1.0.8
  +-- pm2-deploy@0.3.3
  | `-- tv4@1.2.7
  +-- pm2-multimeter@0.1.2
  | `-- charm@0.1.2
  +-- pmx@0.6.8
  | `-- json-stringify-safe@5.0.1
  +-- semver@5.3.0
  +-- shelljs@0.7.5
  | +-- glob@7.1.1
  | | +-- fs.realpath@1.0.0
  | | +-- inflight@1.0.6
  | | | `-- wrappy@1.0.2
  | | `-- once@1.4.0
  | +-- interpret@1.0.1
  | `-- rechoir@0.6.2
  |   `-- resolve@1.1.7
  +-- source-map-support@0.4.6
  | `-- source-map@0.5.6
  +-- vizion@0.2.13
  `-- yamljs@0.2.8
    `-- argparse@1.0.9
      `-- sprintf-js@1.0.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\pm2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

```

**Comment by zaggy** [comment]
I have probably found what is the issue. It appears that when yarn installs modules globally it puts executables to this location: `C:\Users\User.Name\AppData\Local\Yarn\config\global\node_modules\.bin`
And somehow when yarn was installed this location was not added to PATH (maybe because yarn was added using npm in my case). Adding mentioned folder to the PATH fixed the issue with missing executables issue for me.

**Comment by dylanparry** [comment]
The above fix by @zaggy worked for me too.

What I noticed with the `PATH` on my laptop was that it contained `C:\Users\User.Name\AppData\Local\Yarn\.bin`, which in my case at least is a directory that doesn't exist and isn't created when adding new packages.

I should also note that I installed Yarn using the `.msi` file, so it's not just installing it via npm that causes this.

**Comment by yanxyz** [comment]
@zaggy, if the installation command is run as administrator, it would be found that *.cmd files are put together with `node.exe` in `c:\Program Files\nodejs`。#1407

**Comment by skhamoud** [comment]
@yanxyz  Same thing happens with gulp-cli , if installed w/ admin rights , any gulp command crashes the terminal in my case

**Comment by timfish** [comment]
This is fixed in the pre-release 0.19.0

**Comment by wtchangdm** [comment]
Thanks for your efforts!

**Comment by ForsakenHarmony** [comment]
yeah, it tries to install into `C:\Program Files\nodejs` for me as well by default

**Comment by Daniel15** [comment]
This should be fixed in 0.24.x

**Comment by wtchangdm** [comment]
Hi, I just installed 0.24.5 by npm. It can install global package now but still not executable.

```
C:\>yarn --version
0.24.5

C:\>yarn global add pm2
yarn global v0.24.5
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░[4/4] Building fresh packages...
success Installed "pm2@2.4.6" with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
warning No license field
Done in 1.57s.

C:\>pm2 -v
'pm2' is not recognized as an internal or external command, operable program or batch file.

C:\>
```

**Comment by Daniel15** [comment]
If you install Yarn via npm, you'll need to manually add
%LocalAppData%\Yarn\bin to your path.

Sent from my phone.

On May 27, 2017 4:13 AM, "W.T. Chang" <notifications@github.com> wrote:

Hi, I just installed 0.24.5 by npm. It can install global package now but
still not executable.

C:\>yarn --version
0.24.5

C:\>yarn global add pm2
yarn global v0.24.5
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed
compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░[4/4] Building fresh
packages...
success Installed "pm2@2.4.6" with binaries:
      - pm2
      - rundev
      - pm2-dev
      - pm2-docker
warning No license field
Done in 1.57s.

C:\>pm2 -v
'pm2' is not recognized as an internal or external command, operable
program or batch file.

C:\>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/859#issuecomment-304352555>, or mute
the thread

**Comment by milesje** [comment]
Using Yarn installed via .msi installer, then ran `yarn add global polymer-cli` it installs fine but get error when trying to use polymer-cli.
![image](https://user-images.githubusercontent.com/537359/27302026-f00370b8-54fa-11e7-981b-b1eb2ad8153e.png)

**Comment by AvinashGandhasiri** [comment]
Installing npm modules globally din't work for me.
I tried installing then in project folder and they worked fine.
config:
windows 10
node.js 4.5.0
npm 2.15.9
run cmd as an administrator and look if the versions are latest.

**Comment by lewisl9029** [comment]
In my case, my path variable was set at `%LocalAppData%\Yarn\.bin`, when the actual folder was `%LocalAppData%\Yarn\bin` (without the `.` in front of `bin`).

After removing the `.` everything worked fine again.

**Comment by Daniel15** [comment]
@lewisl9029 - Which version of Yarn do you have? That should have been fixed in 0.24.0: https://github.com/yarnpkg/yarn/commit/5fc8539bcd68266fd50802bacc295990444ea664

**Comment by lewisl9029** [comment]
@Daniel15 That makes sense. I installed Yarn quite a while ago so I wouldn't be surprised if I used an installer version prior to 0.24.0.

**Comment by dandv** [comment]
This doesn't appear to be fixed. I've installed polymer-cli globally on a Linux box, but `polymer` isn't in the path.

```
~ yarn global add polymer-cli
yarn global v1.3.2
[1/4] Resolving packages...
warning polymer-cli > bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
warning polymer-cli > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning polymer-cli > polyserve > @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "polymer-cli@1.5.7" with binaries:
      - polymer
Done in 25.08s.
➜  19:17 polymer
zsh: command not found: polymer
➜  19:17 polymer-cli init
zsh: command not found: polymer-cli
➜  19:17 yarn --version
1.3.2
```

**Comment by Daniel15** [comment]
@dandv - This issue is specific to Windows.

**Comment by Daniel15** [comment]
@dandv - This issue is specific to Windows, as it was an issue with the MSI installer. Any Linux issues are unrelated. Please file a separate one.
