### ISSUE TITLE
Error: Invalid hosted git fragment (package installed from branch)

### ISSUE THREAD

**Issue by pomek** [yarnpkg/yarn#979]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn` breaks work.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add into `package.json` the following line: `"benderjs-coverage": "benderjs/benderjs-coverage#t/4",`
2. Run the `yarn`.

**What is the expected behavior?**

`Yarn` should install all dependencies. Instead of I've got an error:

![image](https://cloud.githubusercontent.com/assets/2270764/19342954/66537dfc-9134-11e6-858b-bdeb2a511d3b.png)

With `npm` it works well.

**Please mention your node.js, yarn and operating system version.**
![image](https://cloud.githubusercontent.com/assets/2270764/19343012/b4deacbc-9134-11e6-9de7-aa49b3a6bcdc.png)

**Comment by kittens** [comment]
Fixed via #1023.

**Comment by pomek** [comment]
Unfortunately, it still does not work as it should. 

When I pass the branch for a specified package, I expect that the package will be installed directly from this branch. Instead of the package is installed from default branch (most probably it is `master`). 

I guess it should be reported in another ticket. WDYT?
