### ISSUE TITLE
Can't install scrypt on Ubuntu

### ISSUE THREAD

**Issue by laggingreflex** [yarnpkg/yarn#984]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

```
$ yarn add scrypt
yarn add v0.15.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠂ scrypt: gyp ERR! not ok
error /test/test/yarn/node_modules/scrypt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /test/test/yarn/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.7.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/share/yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/test/test/yarn/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/test/.node-gyp/6.7.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/test/.node-gyp/6.7.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/test/test/yarn/node_modules/scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/test/test/yarn/node_modules/scrypt/build'
SOLINK_MODULE(target) Release/obj.target/copied_files.node
COPY Release/copied_files.node
CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
start: invalid option: -D
Try `start --help' for more information.
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Error 1
gyp ERR! build error
make: Leaving directory `/test/test/yarn/node_modules/scrypt/build'
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/yarn/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.7.0-x86_64-linode72
gyp ERR! command "/usr/bin/nodejs" "/usr/share/yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /test/test/yarn/node_modules/scrypt
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
    at SpawnError (/usr/share/yarn/lib/errors.js:18:1)
    at ChildProcess.proc.on.code (/usr/share/yarn/lib/util/child.js:107:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn add scrypt
```

**What is the expected behavior?**

It should install scrypt. It installs ok with npm.

**Please mention your node.js, yarn and operating system version.**

Node: v6.7.0
yarn: 0.15.0
Ubuntu 14.04.5 LTS

**Comment by laggingreflex** [comment]
Hmm it works with `sudo add scrypt`

**Comment by markstos** [comment]
This worked for me on Ubuntu 16.04 using the latest version of yarn from Git. Please try again with the current version in Git and see if you still experience the issue. I did not use `sudo`.

```
$ yarn add scrypt
yarn add v0.15.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ nan@2.4.0
└─ scrypt@6.0.3
Done in 15.43s.
```

**Comment by busches** [comment]
@kittens no response in over a month.

**Comment by markstos** [comment]
@busches Can you reproduce with the current version of `yarn`? On With what versions of Node and on what OS and version?

**Comment by busches** [comment]
@markstos I did not try. I was basing closing the issue on no responses to your comment that the issue was fixed back with `v0.15.1`

**Comment by laggingreflex** [comment]
Still not working for me with 0.16.1, but feel free to close. I'm on a fairly outdated  Ubuntu 14 (a remote server, locally I'm on Windows), and if it seems to works with `sudo` it's probably some other issue than yarn itself. Couldn't find much info on the error
```
make: Entering directory `/home/flin/test/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
start: invalid option: -D
Try `start --help' for more information.
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Error 1
gyp ERR! build error
```

**Comment by bestander** [comment]
Looks like it is closed now.
Please reopen if can it is still broken in 0.23
